### ISSUE TITLE
recordDemo broken?

### ISSUE THREAD

**Issue by michaellarabel** [RobertBeckebans/RBDOOM-3-BFG#127]
Robert, I've been working on incorporating RBDOOM-3-BFG into the Phoronix Test Suite. I've been trying to record a time demo but whenever doing so the game just locks up... Basically loading any map, then typing e.g. "recordDemo pts1", and immediately then it just hangs.... Any ideas?

**Comment by mcrapet** [comment]
That's really a nice feature. I know nothing about engine/rendering, any ways I can help on this?

**Comment by RobertBeckebans** [comment]
I will try to fix this next month. I want this feature in the next stable release and then it is very likely that I will start porting the renderer to Vulkan. I'm very interested in RBDOOM-3-BFG benchmarks between OpenGL and Vulkan.
