### ISSUE TITLE
GLSL 1.50 not supported

### ISSUE THREAD

**Issue by malariax** [RobertBeckebans/RBDOOM-3-BFG#137]
I'm using mesa-10.2.2 drivers. When I try to launch the game the terminal shows the next error:

error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, and 1.00 ES

The sound works but the screen don't show anything. Does the game work with mesa drivers? Is the GLSL the problem? How can I change the GLSL version?

Thanks

**Comment by shmerl** [comment]
> Is there a plan to eventually update the legacy stuff to OpenGL core and then just drop GLDRV_OPENGL_MESA and use GLDRV_OPENGL32_CORE_PROFILE for it?

I'd second that. There is no need for core profile anymore.

**Comment by myousefi2016** [comment]
Your suggestions helped me a lot to solve a problem!
