### ISSUE TITLE
[Enhancement] Graphics improvement

### ISSUE THREAD

**Issue by johnyukon** [RobertBeckebans/RBDOOM-3-BFG#145]
I see graphics are already being improved, we have better shadows now.

There are many mods created for DOOM 3 that may help in this task because they already have shaders and other stuff:

http://www.moddb.com/mods/sikkmod
http://www.moddb.com/mods/perfected-doom-3-version-500
http://www.moddb.com/mods/parallax-mapping-mod-10
http://www.moddb.com/mods/g-t-x-d3
http://doom3.gamebanana.com/gamefiles/3756

There are probably many other mods around but I think that the most famous one is sikkmod. It comes with source code.

Also I don't know if this might help, but the Tesseract engine, based on cube 2 engine, implements some neat graphics effects, like real time global illumination:

http://tesseract.gg

I don't think graphics are the most important aspect of a game but it's needed to compete with proprietary engines and attract developers.

**Comment by johnyukon** [comment]
Just for you guys to know!

A new low level API called Vulkan from Khronos Group may replace OpenGL, and is being used in Source Engine 2.
Vulkan has better performance and portability than OpenGL.

Check it out:
https://www.khronos.org/vulkan
https://en.wikipedia.org/wiki/Vulkan_%28API%29
https://www.youtube.com/watch?v=qKbtrVEhaw8

**Comment by BielBdeLuna** [comment]
Vulkan will be made ready to the public in October or something like this, Valve is using it already because they are a member from Khronos, only after the specification is out can we start using it.

I think Robert already said he is interested in Vulkan.
and I hope the Vulkan driver in Mesa will be out as quick as they can, Intel already said they are working on it (as they are also in Khronos)

I think SPIR-V is already out isn't it? Would it be wise to start a GLSL exporter for SPIR-V if RbDoom3BFG already has a CG to GLSL exporter?

**Comment by Anthony-Gaudino** [comment]
We should wait for Vulkan and see how it works.

I have read on the Internet that recent versions of OpenGl add some features that greatly improve performance, getting closer to Vulkan's.

As Vulkan is a lower level API (runs closer to hardware) it will require more coding compared to OpenGL, also we already have access to a lot of OpenGl resources (code/documentation) around in the Internet, see bellow.

Please see https://github.com/tobspr/RenderPipeline/, its for Panda 3D (panda3d.org), and runs on OpenGl 4.x.

**Comment by BielBdeLuna** [comment]
There will be three versions of Vulkan so you could use Vulkan as a simple Graphics library like OpenGL, but if you want to go further down in the drivers code you can, so let's wait and see before judging it.
