### ISSUE TITLE
BFG doesn't have OGG support

### ISSUE THREAD

**Issue by BielBdeLuna** [RobertBeckebans/RBDOOM-3-BFG#172]
i have a map with some music referenced as ogg files, I have a copy of the music in wav, the map plays the ogg music in dhewm3 as usual. but when it comes to d3 it can't play the music and instead it plays the default sound, if I change the sound shader reference to the wav file, it plays it correctly.

here is the shader (it's a normal shader, it works ok in dhewm3 )

```
Egypt_intro {
	global
	volume		6
		
	music/egypt/egypt.ogg
}
```

I have the ogg file besides the wav file, and the name is correct and the folder is also correct.

I get the following statement:

```
WARNING: Starting defaulted sound sample music/egypt/egypt
```

if I change it to the *.wav file it doesn't fail. maybe it ignores the ".ogg" part? because in the warning message it doesn't specify that the file that defaults the sound is a *.ogg file.

**Comment by romulus2k4** [comment]
I vote for .ogg support, that would help maintaining compatibility of Vanilla DOOM 3 mods without having to go through the painful process of converting audio, and also, waste space, as .wav takes much more space than .ogg. Just my opinion.
