### ISSUE TITLE
shadows still calculated even when r_skip***shadows is on

### ISSUE THREAD

**Issue by BielBdeLuna** [RobertBeckebans/RBDOOM-3-BFG#177]
someone prompted me that after a profiling of the code, it seems that even if you skip the shadows, or you have a noShadows mterial, the shadows still get calculated (although not shown) so resources get wasted. 
and I was thinking that this could bring problems with big maps, where shadows could be disabled at the distance, and so if the engine still calculates them, the it could represent a problem

what do you guys think? is there a way to strictly stop the shadows-caculating-job to start when those situations are met?

**Comment by revelator** [comment]
Got a working example in vanilla but needs porting to BFG, maybe RB can have a look ?
