### ISSUE TITLE
Lubuntu 14.04.1 LTS - Can't launch after compile

### ISSUE THREAD

**Issue by TLOFelda** [RobertBeckebans/RBDOOM-3-BFG#189]
I compiled the engine using script "cmake-linux-release.sh". Engine compiled successfully, but when I try to launch it, it only flash the screen and won't launch at all.

I tried to compile it using SDL2 too (I changed parameter as README said...), deleted build folder (just to be sure...) and launched the script again. Then, I compiled it, with same result. 

I have all dependencies for compiling installed. Is there any other dependencies whose am I missing?

If you need some log or sth then write me which one and where I can find it and I'll post it here...

**Comment by TLOFelda** [comment]
Leave a comment

**Comment by RobertBeckebans** [comment]
If glxinfo doesn't report GL_EXT_texture_compression_s3tc then it indicates that your driver does not support DXT compression and the engine requires it. It looks like that you patched Mesa with a custom build. 
I get on Kubuntu 14.10 on Sandybridge
OpenGL version string: 3.0 Mesa 10.3.0
OpenGL shading language version string: 1.30
and 
$ glxinfo | grep s3
    GL_EXT_texture_compression_s3tc, GL_EXT_texture_filter_anisotropic, 
    GL_S3_s3tc
    GL_EXT_texture_compression_rgtc, GL_EXT_texture_compression_s3tc, 
    GL_S3_s3tc, GL_SGIS_generate_mipmap, GL_SGIS_texture_border_clamp,

The master branch works here no matter wether SDL 1.2 or SDL 2 are used.
