### ISSUE TITLE
[Enhancement] GL_EXT_polygon_offset_clamp

### ISSUE THREAD

**Issue by nbohr1more** [RobertBeckebans/RBDOOM-3-BFG#203]
GL_EXT_polygon_offset_clamp

https://www.opengl.org/registry/specs/EXT/polygon_offset_clamp.txt

This new extension may improve some shadow acne cases for shadow maps.

**Comment by revelator** [comment]
Got it working in vanilla but was a bit more work than ljbades initial port atleast on AMD cards (else major shadow fuckup).
No shadowmapping in my engine though but could be interresting to see if it fixes the acne in the BFG version. Would need some porting though as i had to modifiy a few other things to even get it running 
correctly on vanilla (Z values).
