### ISSUE TITLE
Joystick LS and RS do not work in PDA screen

### ISSUE THREAD

**Issue by EricxDu** [RobertBeckebans/RBDOOM-3-BFG#214]
I'm using an Xbox 360 wireless controller with RBDoom3 as per the included instructions. The gamepad works fine while playing and in menus. When I activate PDA the left and right sticks do nothing, even though screen shows LS and RS corresponding to certain actions.

**Comment by BielBdeLuna** [comment]
does this also happen when using https://github.com/Wintermute0110/RBDOOM-3-BFG ?

**Comment by EricxDu** [comment]
Yes. I just built the Wintermute fork, and it still happens.

**Comment by RobertBeckebans** [comment]
Should work now :+1: F

**Comment by EricxDu** [comment]
Perfect! It does work now.
