### ISSUE TITLE
3D TV black screen

### ISSUE THREAD

**Issue by mike44** [RobertBeckebans/RBDOOM-3-BFG#217]
Hi
as soon as I set 3D on I get a black screen on my 3D TV. Now back on my PC doom3bfg is still black. What config to reset? Thanks. Would be fun to play on a 4k 3D LG TV.

**Comment by RobertBeckebans** [comment]
What GFX card do you have? You can set it back by starting the engine with RBDoom3BFG +set stereoRender_enable 0

**Comment by mike44** [comment]
Asus GTX 770 2GB
Thanks for the setback. Could I get 3D to work somehow?

**Comment by mike44** [comment]
PS: Reset only works with that command. Even later starting normally I get a black in game screen.

Asus GTX 770 2GBThanks for the setback. Could I get 3D to work somehow?

**Comment by valgusk** [comment]
got the same problem with GTX660 would love to have the 3d. What can i do to help debugging?

**Comment by RobertBeckebans** [comment]
I can't redproduce the problem here although I have no 3D TV. Only the Oculus DK1.

**Comment by valgusk** [comment]
Ok, the separations are broken. Easy bypass if you want to play the game is to just set stereoRender_convergence to 0.
Then engine then chooses head mount separation calculations and works fine. To fix the issue will need a deeper look at the code, I do not know if I personally will do it.

**Comment by valgusk** [comment]
update, calculations are ok, the issue can also be fixed by setting r_forceScreenWidthCentimeters to some value, eg 50
