### ISSUE TITLE
"Failed saving settings to profile."

### ISSUE THREAD

**Issue by JadedCtrl** [RobertBeckebans/RBDOOM-3-BFG#218]
Whenever I try to save something, (Or the game does) I get the error "Failed saving settings to profile. Please make sure storage devices are properly connected and have sufficient storage available."
There's certainly enough room on my hard-drive and such...
The game works perfectly, except for saving.
Running Trisquel 7 GNU/Linux (Based on Ubuntu), Intel.
http://pastebucket.com/80278
Anyone happen to know what the root of the problem is?
Thank you!

**Comment by DanielGibson** [comment]
The error you mentioned is not even in the log?
Otherwise, does the following directory (and all its parent directories incl. `/home/jade`) exist and are they writable: `/home/jade/.rbdoom3bfg/base/`?

**Comment by JadedCtrl** [comment]
Thank you, Daniel- I just needed to make /home/jade/* and sub-directories writable for RBD3 just as you said.

**Comment by RobertBeckebans** [comment]
I had a similar problems once I started the engine with sudo :)

2015-02-21 16:07 GMT+01:00 JadedCtrl <notifications@github.com>:
