### ISSUE TITLE
Game doesn't load in CDE

### ISSUE THREAD

**Issue by Silent-Hunter** [RobertBeckebans/RBDOOM-3-BFG#219]
I used to play this quite often, but I just cloned the latest version and rebuilt, and now when I try to launch it in CDE the Workspace Manager immediately crashes. I can restart it and then kill the game to get my desktop back, but this no longer works for me. Using MATE I can get it to start, but I hate using MATE for games because it has more overhead.

**Comment by DanielGibson** [comment]
Have you considered filing a bug at CDE then?

(If you just want low overhead consider xfce or lxde.. CDE is really obscure in this century.)

**Comment by Silent-Hunter** [comment]
I have considered, yes, but I don't know what's causing it, so I don't know if they will be able to figure it out.

( It's not just low overhead, it's the entire thing. It feels more comfortable to use for me. I like the CUA model it uses, it's similar to OS/2 which I used for so long. )

**Comment by DanielGibson** [comment]
For us debugging this will be even harder, because we don't use CDE (and Debian and Ubuntu don't even have it in their repos).

Does the problem also happen when starting the game in from terminal (like xterm)?

Have you tried any other games in CDE, especially games using SDL and OpenGL?  
(OpenArena may be a good test case because it's free)

**Comment by Silent-Hunter** [comment]
Well, I know Unreal Tournament 2004 works, because I used to play it all the time.

Doom 3 works in TWM, so unlike Borderlands 2 it is a CDE specific problem. I already reported it there. Most games work, SuperTuxKart works as well, and so does Minetest, and Minecraft.

**Comment by DanielGibson** [comment]
maybe it's SDL1 vs SDL2?

**Comment by Silent-Hunter** [comment]
Maybe? I could try and find out, but I wouldn't know how.

**Comment by DanielGibson** [comment]
`cmake -DSDL2=ON ..` vs `cmake -DSDL2=OFF ..`

**Comment by Silent-Hunter** [comment]
That seems to have worked for me!

**Comment by DanielGibson** [comment]
what worked, SDL2=OFF?
Then maybe SDL2 does something differently to SDL1 for fullscreen.. uses something newer not supported by CDE
