### ISSUE TITLE
segfault on loading cpuboss level

### ISSUE THREAD

**Issue by barfingskull** [RobertBeckebans/RBDOOM-3-BFG#224]
Up until this level, cpuboss, everything from compile to gameplay has worked perfectly.  Now that I'm at this level, it segfaults when trying to load.  This happens whether I continue my campaign, and click the bay door to leave CPU, or when I load the level directly not as part of a campaign.  Here's the console output.  Let me know if any further information would be helpful.

----------------------------------------
map bounds are (9232.0, 11584.0, 4016.0)
max clip sector is (577.0, 362.0, 502.0)
    1 KB passage memory used to build PVS
    0 msec to calculate PVS
   44 areas
   88 portals
    9 areas visible on average
  352 bytes PVS data
[Load AAS]
loading maps/game/cpuboss.aas48
done.
[Load AAS]
loading maps/game/cpuboss.aas96
WARNING: Couldn't load AAS file: 'maps/game/cpuboss.aas96'
[Load AAS]
loading maps/game/cpuboss.aas_guardian
WARNING: Couldn't load AAS file: 'maps/game/cpuboss.aas_guardian'
[Load AAS]
loading maps/game/cpuboss.aas_mancubus
WARNING: Couldn't load AAS file: 'maps/game/cpuboss.aas_mancubus'
[Load AAS]
loading maps/game/cpuboss.aas_sabaoth
done.
[Load AAS]
loading maps/game/cpuboss.aas_cyberdemon
WARNING: Couldn't load AAS file: 'maps/game/cpuboss.aas_cyberdemon'
Entering doom_main()
Exiting doom_main()
Spawning entities
WARNING: file def/gibs.def, line 77: Couldn't load anim 'models/md5/gibs/leftleggib.md5anim'
WARNING: idAF::Load: articulated figure 'env_gibs_leftleg' for entity 'env_gibs_leftleg_1' at (-678 2128 182) has no or defaulted modelDef ''
TODO: Sys_SetClipboardData
--------- Game Map Shutdown ----------
--------------------------------------
********************
ERROR: idAFEntity_Base::LoadAF: Couldn't load af file 'env_gibs_leftleg.af' on entity 'env_gibs_leftleg_1'
********************
--------- Game Map Shutdown ----------
--------------------------------------
Loaded FFMPEG file: 'video/intro/introloop.bik', looping=1512x512, 30.000000 FPS, 360.000000 sec
Loaded FFMPEG file: 'video/mars1.bik', looping=0512x512, 30.000000 FPS, 965.000000 sec
Loaded FFMPEG file: 'video/mars_rotation.bik', looping=11567x406, 30.000000 FPS, 3000.000000 sec
----- idRenderModelManagerLocal::EndLevelLoad -----
signal caught: Segmentation fault
si_code 1
Trying to exit gracefully..
session->GetSaveGameManager().CancelToTerminate();
soundSystem->StopAllSounds();
Stop();
--------- Game Map Shutdown ----------
--------------------------------------
CleanupShell();
delete loadGUI;
delete renderWorld;
delete soundWorld;
delete menuSoundWorld;
session->ShutdownSoundRelatedSystems();
session->Shutdown();
game->Leaderboards_Shutdown();
uiManager->Shutdown();
soundSystem->Shutdown();
usercmdGen->Shutdown();
eventLoop->Shutdown();
declManager->Shutdown();
renderSystem->Shutdown();
idRenderSystem::Shutdown()
Shutting down OpenGL subsystem
commonDialog.Shutdown();
UnloadGameDLL();
------------ Game Shutdown -----------
--------- Game Map Shutdown ----------
--------------------------------------
Shutdown event system
--------------------------------------
saveFile.Clear( true );
stringsFile.Clear( true );
CloseLogFile();
fileSystem->Shutdown( false );
Sys_Shutdown();
console->Shutdown();
idKeyInput::Shutdown();
cvarSystem->Shutdown();
cmdSystem->Shutdown();
ClearWarnings( GAME_NAME " shutdown" );
warningCaption.Clear();
errorList.Clear();
idLib::ShutDown();
shutdown terminal support

**Comment by barfingskull** [comment]
I should add that I'm on Mint 17.1, nVidia drivers.  Though I assume since it's particular to this level, it's not necessarily a graphics issue, but something in how it handles loading the assets.  Both levels before and after it seem to load just fine.

**Comment by kortemik** [comment]
WARNING: file def/gibs.def, line 77: Couldn't load anim
'models/md5/gibs/leftleggib.md5anim'
Means that your assets, game files under base/ directory, are incomplete.

However the game should not segfault from that, just exiting map should be
enough or shutdown. I know there are quite many bugs in there. We have a
static code analysis for OpenTechBFG project which is forked from RBDoom3
here https://scan.coverity.com/projects/4341?tab=overview it has around 700
defects, less or more deadly.

The values might be bit more lower for RBDoom3 but still there is work to
be done.

Let me take the top ones here:

Memory - corruptions 113
Memory - illegal accesses 33
Uninitialized variables 19
Null pointer dereferences 83
Control flow issues 16
Error handling issues 14

In case someone is willing to take on fixing these it would be really nice.
I will grant access to that tool, please just sign-in/up and request. It's
really handy and fixing shouldn't be that bad.

Easiest way to implement them is to fork either RBDoom3 or OpenTechBFG,
establish own branch and we will merge them between the projects.

-Mikko

**Comment by coldtobi** [comment]
Quoting barfingskull <notifications@github.com>:

> I should add that I'm on Mint 17.1, nVidia drivers.  Though I assume  
> since it's particular to this level, it's not necessarily a graphics  
> issue, but something in how it handles loading the assets.  Both  
> levels before and after it seem to load just fine.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/224#issuecomment-94375727

Can you try to get an backtrace, e.g by running it under gdm and when  
crashed entering
"bt" in the console?

**Comment by kortemik** [comment]
> Can you try to get an backtrace, e.g by running it  from a shell under gdb and when
crashed entering "bt" in the shell?

If you compiled with DEBUG this should be even more handy, as it shows us the symbols
(gdb) info stack full

**Comment by barfingskull** [comment]
What, Sarge actually needs his left leg?  I downloaded the game from Steam on Windows.  I wanted to try and see if it ran natively under Win7 as part of this exercise, but apparently my old MB Pro (running Windows) doesn't have the video hardware to handle it.  I never really intended to play the game there, though.  Anyway, I copied the base directory from there when I first set things up.  So I'm not sure what I could be missing, or where I might find that? I'd like to continue the game if possible.  I suppose I can check them again against what got downloaded, or try and re-install the game and re-copy.

I recompiled it with debug.

I'm assuming @coldtobi meant 'gdb' since the 'gdm' display manager wouldn't seem to be much help.

Here's some of the stack trace info:

https://gist.github.com/barfingskull/a4d638673b06307b6e96

**Comment by kortemik** [comment]
data = 0xaf8f1c0
"generated/images/models/mapobjects/doors/techdoor1/techdr1rt_d#__0100.bimage",
allocedAndFlag = 96,

I'd first try to move the generated directory under the base to
generated_backup and see if the problem persists.

-Mikko

**Comment by barfingskull** [comment]
Okay, deleting the generated files had no effect.

So I re-downloaded from Steam on my Windoze box, and copied 'base' over again.  Other than a couple possibly corrupted save files, it seems to work now.  Luckily my quicksave seemed to load.  So I'm content to chalk it up to missing assets, or perhaps something that didn't get generated or saved correctly, which could be an RBDoom3 problem, dunno.  Other than that it could be a download or transfer problems, but those seem relatively rare these days.

Anyway, thanks for the pointers.  But yes, the game should do something other than segfault on those errors.
