### ISSUE TITLE
No speaking sound (Ubuntu 14.10)

### ISSUE THREAD

**Issue by FanatoniQ** [RobertBeckebans/RBDOOM-3-BFG#226]
Hi,
I installed RBDOOMM3BFG today on my Ubuntu 14.10 pc and was very exited because what you did is really good work, but the are no sounds from people speaking, are those files supposed to be in Program Files (x86)/ Steam/SteamApps/Doom 3 BFG Edition/base or in another directory (which files are they) ? Is it a problem with my drivers configuration ? (I used Nvidia Binary Driver 331.113 and should have Open GL and Open AL active).
If Open AL isn't installed how do I install it ?

My config : 
-8 GB RAM DDR3
Processor : Intel Core i5-4460S CPU 2.9GHz x 4
Graphical Card : Nvidia Geforce GT 720 2GB DDR3
OS : Ubuntu 14.10 (64 bits)

**Comment by RobertBeckebans** [comment]
Do you use a non-English installation?

2015-05-06 15:58 GMT+02:00 FanatoniQ <notifications@github.com>:

**Comment by FanatoniQ** [comment]
French version.

**Comment by FanatoniQ** [comment]
I found the problem it comes for the fact of copying the french.lang into english.lang.
Thanks a lot for the awesome work you did !
