### ISSUE TITLE
Soft Shadows, flashlight issues

### ISSUE THREAD

**Issue by Yetta1** [RobertBeckebans/RBDOOM-3-BFG#227]
Source Version built from: 7 March 2015 - RBDOOM-3-BFG 1.0.3

Soft Shadows enabled causes textures to become completely black and removes the flashlight lighting. Disabling the Soft Shadows stops the issue. Source build on VS 2013, running on BFG Steam version. 

![2015-06-08_00002](https://cloud.githubusercontent.com/assets/8399958/8031688/c3468678-0dd0-11e5-8498-de0bba1b5229.jpg)
![2015-06-08_00003](https://cloud.githubusercontent.com/assets/8399958/8031691/c82a81a8-0dd0-11e5-85f4-90d506e44813.jpg)
![2015-06-08_00004](https://cloud.githubusercontent.com/assets/8399958/8031693/cc672938-0dd0-11e5-8452-7a832c2fdb2a.jpg)

![2015-06-08_00005](https://cloud.githubusercontent.com/assets/8399958/8031702/d2c6598e-0dd0-11e5-8add-350074f27e27.jpg)
![2015-06-08_00006](https://cloud.githubusercontent.com/assets/8399958/8031707/d7e4df30-0dd0-11e5-98e7-740c5203f58f.jpg)
![2015-06-08_00007](https://cloud.githubusercontent.com/assets/8399958/8031708/dd550008-0dd0-11e5-9ec8-8eac1db8295f.jpg)

![2015-06-08_00008](https://cloud.githubusercontent.com/assets/8399958/8031715/e4d0c114-0dd0-11e5-9690-8304d620ae1e.jpg)
![2015-06-08_00009](https://cloud.githubusercontent.com/assets/8399958/8031719/ebe2bb9c-0dd0-11e5-9097-3856dc1c7b53.jpg)
![2015-06-08_00010](https://cloud.githubusercontent.com/assets/8399958/8031724/f79182ca-0dd0-11e5-8a67-933265e57fe2.jpg)
![2015-06-08_00011](https://cloud.githubusercontent.com/assets/8399958/8031727/fc028d4a-0dd0-11e5-8817-96b75b025af6.jpg)

Another glitch occurs when a level is reloaded which causes a trailing effect.

![2015-06-08_00012](https://cloud.githubusercontent.com/assets/8399958/8031729/03fd129a-0dd1-11e5-84b5-0e2824660d0e.jpg)

Hardware used, Celeron Dual Core, Geforce GT 630, 4GB DRR2. RBDooM-3-BFG runs at a stable 60-70 fps with Soft shadows enabled or disabled.

Additional mods used on RBDooM-3-BFG: Monoxead, Phrozo and Wulfen Textures.

Other than that, Great Source, keep up the good work. Would be great to get a GtkRadiant version for RBDoom-3-BFG. Thank you Robert and the other contributers.

**Comment by BielBdeLuna** [comment]
maybe it has to do with the other mods? does an unmoded game behaves the same way?

**Comment by Yetta1** [comment]
@BielBdeLuna I tested the game with both the vanilla textures and modded textures. The problem seems to arise with soft shadows enabled. As for the strange trailing effect glitch, it only seems to happen if a level was loaded at first, then reloaded again, e.g reload after death or loading from a save game. All my systems drivers are up to date.

I'm going to rebuild the source again on VC 2013. I just read the readme file, I will use the RBDoom3BFG.exe +set developer 1 +set logfile 2 command line as instructed to give further details on the problem.

The current build I'm using used SDL2 and the latest ffmpeg files.

I'll try build the game on my Mint Linux which is currently using the Linux Kernel 4.0

**Comment by RobertBeckebans** [comment]
I think it is an installation problem. I can't reproduce it

**Comment by Yetta1** [comment]
@RobertBeckebans Please excuse the late reply. I redownloaded BFG on steam and did a clean install, the issue appeared again on a nw compile with VS express 2013 as well with Eclipse cpp Mars. It only seems to be happening with soft shadows enabled. I've also tested with the latest nVidia 353.30 drivers. Seems the logfile wasn't written out to the hard drive. Any advice if it might be another installation issue on my end? Going to try the OpenTech fork as well.

**Comment by Yetta1** [comment]
@RobertBeckebans I got the soft shadows working, I removed the DX SDK June 2010 and the C++ redistributable packages installed, then reinstalled DX SDK June 2010, the build was successful and soft shadows works beautifully. The only issue I came across was an old save file crashing the when I tried to load, but starting a new game seems to have worked.

**Comment by RobertBeckebans** [comment]
Hmm makes no sense to me :) but nice that it works!

2015-07-01 22:34 GMT+02:00 Yetta1 <notifications@github.com>:
