### ISSUE TITLE
Cannot set fullscreen mode

### ISSUE THREAD

**Issue by Ansa89** [RobertBeckebans/RBDOOM-3-BFG#233]
I'm trying to start rbdoom 3 bfg edition in fullscreen mode without success.
I can start it in windowed mode ("+set r_fullscreen 0"), but when I try to launch it with "r_fullscreen" set to 1, or 2, or 3, or 4, I get the message "Doom3 bfg.exe has stopped working" from windows.

System info:
- Windows 8.1 pro 64bit
- Intel Core i5-3470
- nVidia GeForce GTX 650
- no screens connected
- tightvnc server

I tried also using the original doom 3 exe (from steam) but I get the same results.

**Comment by BielBdeLuna** [comment]
maybe it has to do with the drivers?

**Comment by Ansa89** [comment]
I don't think it's a driver issue.
My guess: the problem relies in tightvnc server and how it manages virtual screens (somewhere I read it sometimes messes up with screen detection of other applications).

However I'm not an expert and I'm open to every comment/idea.

Just for reference: my drivers are the GeForce Game Ready Driver version 353.30 and I'm using GeForce Experience version 2.4.5.57.

**Comment by RobertBeckebans** [comment]
I think the problem is that there are no screens connected. The engine
collects all available fullscreen resolutions from all connected screens
and chooses one of it.
Maybe this case was never foreseen and the code crashes with an empty list.

2015-07-10 10:32 GMT+02:00 Ansa89 <notifications@github.com>:

**Comment by Ansa89** [comment]
> I think the problem is that there are no screens connected. The engine collects all available fullscreen resolutions from all connected screens and chooses one of it.

Ok, can you fix this on rbdoom?
Moreover is there a way to have this fixed on official doom 3 on steam (AKA: how can I contact official devs)?
