### ISSUE TITLE
Soft Shadows not working properly?

### ISSUE THREAD

**Issue by TyrannWright** [RobertBeckebans/RBDOOM-3-BFG#235]
Having soft shadows enabled gives me this ugly coloring on polygons that ruins the gameplay. Any solutions???

http://i.imgur.com/dUYC5Bd.jpg

**Comment by DanielGibson** [comment]
Update your GPU drivers.

If that doesn't help at least tell us what operating system, GPU and driver version you're using and what version of rbd3bfg (latest git compiled yourself? binaries from a release? ...)

**Comment by TyrannWright** [comment]
Windows 8.1 64 bit
AMD R9 200 Series (Fully Updated 15.7)
RBDoom3 1.0.3

**Comment by TyrannWright** [comment]
My wonder is... Does this have to do with AMD's Catalyst AI as vanilla Doom 3 had problems with?

**Comment by RobertBeckebans** [comment]
This looks like a new issue. Could you make a shortcut to the .exe and start it with +set logfile 2, please? You can attach the qconsole.log here so I get a better insight if the shader compiler failed.
You can find your qconsole.log in C:\Users\<your user name>\Saved Games\id Software\RBDOOM 3 BFG/base

**Comment by TyrannWright** [comment]
http://www.filedropper.com/qconsole
(Couldn't attach the file.)

**Comment by RobertBeckebans** [comment]
There is something wrong with the pixel shader. Please delete all
base/renderprogs/ files and try again.
It looks like yours aren't up to date with the latest version. If you
delete them then the engine will fall back to the builtin shaders baked
into the .exe.

2015-07-21 8:09 GMT+02:00 TyrannWright <notifications@github.com>:

**Comment by TyrannWright** [comment]
Awesome, it's working! Thanks a lot.
