### ISSUE TITLE
soft shadows extremely dark

### ISSUE THREAD

**Issue by zaphodphillips** [RobertBeckebans/RBDOOM-3-BFG#236]
Hello.  I'm a first-time poster, here.  So, I apologize if I was supposed to add this to a pre-existing issue.  I've seen postings related to this issue, but nothing quite like what I've got.  I've built the 32- and 64-bit versions, and used the pre-compiled RBDoom3BFG as well.  (I have both the 32-bit, and 64-bit ffmpeg files to switch between game versions.)  Enabling soft shadows makes the game unplayably dark in every case, though the game works well without them.  (I have also verified the game cache through Steam.  It was fine, though I didn't think it was a likely suspect.)

Here are my system specs.

CPU: core i7 2670QM, 2.2GHz (on an Asus laptop),  16GB system ram.
GPU: Nvidia GTX-560M, 2GB vram, 353.30 driver
OS: Windows 7, SP1

P.S. The 1.0.3 version of RBDoom3BFG crashes when I use the mod launcher (version 1.2), but works fine when run directly.  That is, it runs fine until the first map starts to load, then dies every time.  (Yeah, a separate issue, I suppose.  But not as significant to me.  Just thought you might want to know.)

Thank you for creating RBDoom3BFG, and thanks for your help.

**Comment by zaphodphillips** [comment]
Ugh.  I finally saw that #176 is pretty much the same problem.  Sorry.

**Comment by zaphodphillips** [comment]
However, I only use the nvidia driver.  The gtx-560m is the only gpu on the machine.

**Comment by kortemik** [comment]
@zaphodphillips I wonder if you got this fixed or was it just that it's a duplicate and wanted to close?

**Comment by DanielGibson** [comment]
he wrote that it's a duplicate of #176

**Comment by zaphodphillips** [comment]
Yes.  Thank you for responding.  The only difference I saw from #176 is that I don't use an intel driver.  They said there was no problem when using the nvidia driver which is not the case for me.  Thanks again.
