### ISSUE TITLE
exe size, what am I doing wrong?

### ISSUE THREAD

**Issue by y2keeth** [RobertBeckebans/RBDOOM-3-BFG#242]
Trying to figure out what I am doing wrong.  When I build the game exe its roughly 3 time larger than the released version.

**Comment by DanielGibson** [comment]
maybe it contains debug symbols?

**Comment by y2keeth** [comment]
So its a debug version?  I must have something set for that I do not see.

**Comment by Calinou** [comment]
Be sure to strip debug symbols. On GNU/Linux, you can use the `strip file_name` command.

If you want minimal size for your binaries, compress them using [UPX](http://upx.sourceforge.net/). This has minimal overhead, but saves a lot of space on large binaries.

**Comment by y2keeth** [comment]
Thanks, I set it to have no debug symbols but Its still the same size.  Twice the size of Trebors build, not sure why.  I'll try the UPX I guess.

**Comment by RobertBeckebans** [comment]
I did nothing special. I compiled the binaries with VS 2013 in Release mode on Windows 7.

**Comment by y2keeth** [comment]
Release mode, maybe that's what I am doing wrong.  I'll try that.

**Comment by y2keeth** [comment]
Totally what it was, thanks. I Increase the STATIC_VERTEX_MEMORY liked you said on ModDB from 31 * 1024 * 1024 to 62 * 1024 * 1024.  DOubling it seems to work just curious if I did it right.
