### ISSUE TITLE
Unable to Compile on Mac OS X

### ISSUE THREAD

**Issue by ghost** [RobertBeckebans/RBDOOM-3-BFG#244]
I've downloaded RBDOOM-3-BFG commit "cb4e301bdc" via git and have been able to use CMake (ver 3.2.2) to create an Xcode project. However, when I compile I get the following error: 

error: Microsoft inline asm blocks was disabled in PCH file but is currently enabled

I have used both OS 10.10 with Xcode 6 and OS 10.11 with Xcode 7 and receive the same error. I've also tried unchecking USE_PRECOMPILED_HEADERS in CMake and after fixing several issues; I end up back with the same error. I've also looked though the CMake files but haven't spotted anything that looks like it would change anything. However, I'm not very familiar with CMake.

The full output is listed below:

CompileC build/idlib/RBDoom3BFG.build/Debug/idlib.build/Objects-normal/x86_64/Heap.o idlib/Heap.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/johnh/src/RBDOOM-3-BFG/neo
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DCMAKE_INTDIR=\"Debug\" -DUSE_INTRINSICS -DUSE_EXCEPTIONS -DGLEW_STATIC -D__IDLIB__ -D__DOOM_DLL__ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -mmacosx-version-min=10.11 -g -Wno-sign-conversion -I/Users/johnh/src/RBDOOM-3-BFG/neo/build/idlib/Debug/include -I/Users/johnh/src/RBDOOM-3-BFG/neo/libs/zlib -I/Users/johnh/src/RBDOOM-3-BFG/neo/libs/png -I/Users/johnh/src/RBDOOM-3-BFG/neo/libs/jpeg-6 -I/Users/johnh/src/RBDOOM-3-BFG/neo/libs/glew/include -I/Users/johnh/src/RBDOOM-3-BFG/neo/idlib -I/Users/johnh/src/RBDOOM-3-BFG/neo/build/idlib/RBDoom3BFG.build/Debug/idlib.build/DerivedSources/x86_64 -I/Users/johnh/src/RBDOOM-3-BFG/neo/build/idlib/RBDoom3BFG.build/Debug/idlib.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/Users/johnh/src/RBDOOM-3-BFG/neo/build/idlib/Debug -D_DEBUG -fno-strict-aliasing -Wno-pragmas -Wno-unused-variable -Wno-switch -Wno-unused-value -Winvalid-pch -Wno-multichar -Wno-local-type-template-args -Wno-unknown-warning-option -Wno-inline-new-delete -Wno-switch-enum -pipe -Werror=format-security -Werror=format -mmmx -msse -msse2 -march=native -include /Users/johnh/src/RBDOOM-3-BFG/neo/idlib/precompiled.h -MMD -MT dependencies -MF /Users/johnh/src/RBDOOM-3-BFG/neo/build/idlib/RBDoom3BFG.build/Debug/idlib.build/Objects-normal/x86_64/Heap.d --serialize-diagnostics /Users/johnh/src/RBDOOM-3-BFG/neo/build/idlib/RBDoom3BFG.build/Debug/idlib.build/Objects-normal/x86_64/Heap.dia -c /Users/johnh/src/RBDOOM-3-BFG/neo/idlib/Heap.cpp -o /Users/johnh/src/RBDOOM-3-BFG/neo/build/idlib/RBDoom3BFG.build/Debug/idlib.build/Objects-normal/x86_64/Heap.o

error: Microsoft inline asm blocks was disabled in PCH file but is currently enabled
1 error generated.

**Comment by JanSimek** [comment]
If you generate "Unix Makefiles" from CMake instead of an Xcode project it compiles (after a few tweaks). Strange.

**Comment by kalibannez** [comment]
To solve "error: Microsoft inline asm blocks was disabled in PCH file but is currently enabled
" error just remove "-fasm-blocks" from clang arguments. If you building from Xcode- just set "CodeWarrior-Style Inline Assembly" property in "Build Settings" for all targets to NO.
