### ISSUE TITLE
erebus3 error?

### ISSUE THREAD

**Issue by y2keeth** [RobertBeckebans/RBDOOM-3-BFG#247]
--------- Execute Map Change ---------
Map: game/erebus3
Loaded resource file maps/erebus3.resources
--------- Game Map Shutdown ----------
## WARNING: idClipModel::FreeTraceModel: tried to free uncached trace model

```
43 msec to unload map
65 msec to free assets
```

WARNING: Couldn't load image: } : }#__0200
Preloading images...
WARNING: ASSERTION FAILED! ../idlib/Str.h(451): 'amount <= GetAlloced()'
signal caught: Trace/breakpoint trap
si_code -6
Trying to exit gracefully..
session->GetSaveGameManager().CancelToTerminate();
soundSystem->StopAllSounds();
Stop();
## --------- Game Map Shutdown ----------

CleanupShell();
delete loadGUI;
delete renderWorld;
delete soundWorld;
delete menuSoundWorld;
session->ShutdownSoundRelatedSystems();
session->Shutdown();
game->Leaderboards_Shutdown();
uiManager->Shutdown();
soundSystem->Shutdown();
AL lib: (WW) FreeDevice: (0x72e3db0) Deleting 255 Buffer(s)
usercmdGen->Shutdown();
eventLoop->Shutdown();
declManager->Shutdown();
renderSystem->Shutdown();
idRenderSystem::Shutdown()
Shutting down OpenGL subsystem
commonDialog.Shutdown();
UnloadGameDLL();
------------ Game Shutdown -----------
## Shutdown event system

saveFile.Clear( true );
stringsFile.Clear( true );
CloseLogFile();
fileSystem->Shutdown( false );
Sys_Shutdown();
console->Shutdown();
idKeyInput::Shutdown();
cvarSystem->Shutdown();
cmdSystem->Shutdown();
ClearWarnings( GAME_NAME " shutdown" );
warningCaption.Clear();
errorList.Clear();
idLib::ShutDown();
shutdown terminal support

**Comment by y2keeth** [comment]
why it pasted like that I have no idea lol

**Comment by aFoxNamedMorris** [comment]
That's part of why I use pastebin. XD

**Comment by y2keeth** [comment]
its your error I posted lol

**Comment by aFoxNamedMorris** [comment]
Oh. O.o Well... Uh... Oops. This happened whilst using the TrentPhrozo mod... not sure if it happens in base game... should probably give it a good old go.

**Comment by BielBdeLuna** [comment]
I think idTechX loading the assets differently than idTech4 added this problem, all assets not loaded on level start tend to generate an error. but this is problematic because some entities generate new entities than need assets ( the muzzle flash use the texture for the light and this might not be loaded)

**Comment by aFoxNamedMorris** [comment]
Is there no workaround? I'm stuck at the end zone in Erebus 2.

**Comment by y2keeth** [comment]
Hmmm, if I can figure out which one it is there is another way to preload it.

**Comment by RickSanchez86** [comment]
If you delete the "zombified_jumpsuit" texturefolder in base/models/characters you won't crash when loading the Erebus 3 level.
