### ISSUE TITLE
Compile with ffmpeg 2.9 (Debian Bug #803857)

### ISSUE THREAD

**Issue by coldtobi** [RobertBeckebans/RBDOOM-3-BFG#249]
Hi,

FYI, https://bugs.debian.org/803857 has a patch for the upcoming ffmpeg 2.9 transition.

(As soon as I get along to test the patch I'll create a pull request.)

**Comment by coldtobi** [comment]
See also Pull Request #271

**Comment by RobertBeckebans** [comment]
This is already merged.
