### ISSUE TITLE
might have some OpenGL extensions changed names?

### ISSUE THREAD

**Issue by BielBdeLuna** [RobertBeckebans/RBDOOM-3-BFG#256]
On Mesa 11.1.0-devel on a intel Sandy Bridge chipset, when I try to force the engine load the core profile with " +set r_useOpenGL32 2" I usually end up with this message:

```
----- R_InitOpenGL -----
Initializing OpenGL subsystem
Using 8 color bits, 24 depth, 8 stencil display
Using GLEW 1.10.0
Sys_InitInput: Joystick subsystem init
Sys_InitInput: Joystic - Found 0 joysticks
OpenGL Version  : 3.3
OpenGL Vendor   : Intel Open Source Technology Center
OpenGL Renderer : Mesa DRI Intel(R) Sandybridge Mobile 
OpenGL GLSL     : 3.3
   maxTextureAnisotropy: 16.000000
...using GL_EXT_texture_lod_bias
X..GL_GREMEDY_string_marker not found
X..GL_EXT_framebuffer_object not found
...using GL_EXT_framebuffer_blit
--------- Game Map Shutdown ----------
--------------------------------------
Setup OpenAL device and context... Done.
OpenAL vendor: OpenAL Community
OpenAL renderer: OpenAL Soft
OpenAL version: 1.1 ALSOFT 1.16.0
OpenAL extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length
********************
ERROR: GL_ARB_texture_compression or GL_EXT_texture_compression_s3tc not available
********************
Sys_Error: Error during initialization
```

now, "GL_EXT_texture_compression_s3tc" is available in compat and in core as it's mentioned as completed in this page: http://people.freedesktop.org/~imirkin/glxinfo/glxinfo.html#v=Mesa%2011.0.0&p=compat
and "GL_ARB_texture_compression" it's already finished in compat but it's not actually called in core

also what I found strange is those two:

```
X..GL_GREMEDY_string_marker not found
X..GL_EXT_framebuffer_object not found
```

about the first one I couldn't find any reference, but on the second I could find a "GL_ARB_framebuffer_object" not EXT but ARB (in OpenGL3.0) could it be that some of those extensions have changed name?

**Comment by kortemik** [comment]
You need to install s3tc package from nonfree repository of your
distribution.

http://askubuntu.com/questions/56379/is-there-an-easy-way-to-enable-s3tc-on-intel-graphics

**Comment by BielBdeLuna** [comment]
if doom3 already works without it ( with OpenGL3.0 ) could we pass without that extension? it's not necessary for OpenGL3.2 core profile isn't it? what functionality would we loose?

**Comment by RobertBeckebans** [comment]
We could skip the extension checks if the run a core profile because core
means it has to be implemented but I'm not sure if GLEW has valid function
pointers then.
GL_EXT_framebuffer_object has the same function addresses as
GL_ARB_framebuffer_object and could be replaced. It is very annoying that
Mesa handles the core profile extensions differently than the proprietary
drivers.

2015-11-18 17:02 GMT+01:00 Biel Bestué de Luna <notifications@github.com>:

**Comment by BielBdeLuna** [comment]
does the engine have a way to handle the skipping of an extension in case it ends up being useful?

Is it Mesa or that the extension changed with the more recent versions of OpenGL?
Is there any way to maybe get all the extension required for an specific profile instead of having to name them, like literally selecting a revision of OpenGL and it handling which extensions are used and which don't?

**Comment by kortemik** [comment]
https://www.opengl.org/wiki/OpenGL_Loading_Library alternatives
