### ISSUE TITLE
Some guy can tell me where can I find the game data?

### ISSUE THREAD

**Issue by haolly** [RobertBeckebans/RBDOOM-3-BFG#257]
The README said:

> Note that Doom 3 BFG Edition is available from the Steam store at
> http://store.steampowered.com/app/208200/

but there is no download or buy button on the stream store

**Comment by BielBdeLuna** [comment]
you know the "add to cart" button in that page, it's the button that makes all excuses go away

**Comment by spannerman79** [comment]
I'd buy it from https://isthereanydeal.gamesrepublic.com/game/action,doom-3-bfg-edition,1988.html as its cheaper there - even with the supposed sale on

**Comment by bryansee** [comment]
I'm interested in creating free assets using this engine, without having to buy that game.

The WAD I can use with this is [FreeDoom](http://freedoom.github.io/) for the Doom Classic.

However, as for replacing the main Doom 3 assets with free ones, it's still a question on how to get started.

**Comment by BielBdeLuna** [comment]
the resource files contain all the game data, you can extract it with the command:
`extractResourceFile`

check out the extract_resources cfg file in base from RBDoom3BFG

you can also checkout the [Open Tech Engine](https://github.com/OpenTechEngine/OpenTechBFG), a variation of RBDoom3BFG, which already contains a lot of free assets for doom3 if you want to use the 3d engine.
