### ISSUE TITLE
Flash light does not cast shadows

### ISSUE THREAD

**Issue by EmptyHelmet** [RobertBeckebans/RBDOOM-3-BFG#258]
After changes Robert made november 17 and 23, i recompiled engine. Now flash ligt does not cast shadows anymore. Its hapening on Intel and nvidia graphics cards. Ubuntu 14.04

**Comment by BielBdeLuna** [comment]
On my Intel with mesa drivers (stable and oibaf) and Ubuntu 15.10 it displays shadows form the flashlight ok.

Maybe, have you checked if r_shadows is 1? are you using r_useOpenGL32 2? I've checked and without OpenGL 3.2 the shadows also show up on my machine.
are you using soft shadows?

**Comment by Mensons** [comment]
r_shadows 1 does not work. I find out that if you use old ./rbdoom3 folder then shadows work. If remove it and let engine generstr new one.... shadows disapear.

**Comment by RobertBeckebans** [comment]
Make sure that the flash light shadows are set in the game options.

**Comment by Mensons** [comment]
My fault.:) Cheked and yes. It was disabled. At begining i looked in wrong section, in video settings. Thanks Robert.
