### ISSUE TITLE
Suggestion: Create inclusive "dummy" internal shader for loading other external shaders.

### ISSUE THREAD

**Issue by aFoxNamedMorris** [RobertBeckebans/RBDOOM-3-BFG#262]
As nice as SweetFX or ReShade can be on Windows, Linux and OSX users are left without the ability to inject or load external shaders into the game.

Example: http://www.moddb.com/mods/doom-3-bfg-hi-def/addons/immersive-reshade-for-doom3-bfg

I propose (if this is even possible without breaking vanilla saves or what-have-you.) an internal "dummy" shader of sorts which allows loading of custom shader files at runtime from an external folder. 

If possible, then one could in theory add a CVAR for controlling which shader folder is used. (Similar in behavior to the fs_game CVAR, but for shaders.)

Just a thought. I hope I've not put this in the wrong place or have wasted anyone's time.

Regards,

~SteamFox

**Comment by BielBdeLuna** [comment]
nice idea

**Comment by RobertBeckebans** [comment]
I just uploaded a HDR branch that implements bloom. It is a very good base for further post process effects including lens flares and film grain. If you want different effects then you could simply override the renderprogs/tonemap.pixel and renderprogs/hdr_glare_chromatic.pixel.

See https://github.com/RobertBeckebans/RBDOOM-3-BFG/commit/37005ba506743711608e9801573a087cdded05fb for more details

**Comment by aFoxNamedMorris** [comment]
@RobertBeckebans So by that, do you mean that one could re-write those and drop them into the 'base/renderprogs' folder? Please, excuse my derpiness.

**Comment by BielBdeLuna** [comment]
great!, it works great! congratulations! :)

I see some errors on the colours of the HDR shader, but this is excelllent!
