### ISSUE TITLE
HDR issues: flickering lights

### ISSUE THREAD

**Issue by BielBdeLuna** [RobertBeckebans/RBDOOM-3-BFG#263]
the flicker of the lights seems to force the renderer to change too much, could we slow down the ticks of the sampling of the brighness, maybe 4 times a second instead of  every frame, or maybe an average of several frames (like the average of every 10 sampled frames or so) so there isn't any flicker in the sampled result?

**Comment by BielBdeLuna** [comment]
I propose this to be controlled by the player entity, or in case of the player not ocntrolling it maybe do a  r_hdrTick cvar and change that part in "RB_CalculateAdaptation()" in the beginning where it gets to change the adaptation. it establishes an adaptation rate that I think could be played upon within the player code, in a tranquil situation the adaptation rate could be far less pronounced, but amidst the heat of battle the adaptation could be per-frame.

**Comment by BielBdeLuna** [comment]
I tried adding a cvar named r_trick but it proved a bad idea, I did a tick every 10 frames but this means every 10 frames the HDR adapts it's 2% so it  shows up. no the solution might be to keep the rate to every frame but to change the percentage, this way the effect is imperceptible and the change obeys some psychological reasoning.

also there could be an attack and release of the adaptation, if the light seen represents a big step or a small step also should effect the percentage of change.

**Comment by aFoxNamedMorris** [comment]
Is there any way to poll a frame's global luminosity in a binary light/dark manner? If so, it may be possible to have 2-3 frames' values affect the effect calc. This may make the flickering light more smooth and bearable.

Just a thought.

**Comment by RobertBeckebans** [comment]
The flickering lights only boost the lighting too much because the game is
overall bad lit and too dark. Adding an ambient indirect lighting term
could help.

2015-12-24 10:56 GMT+01:00 aFoxNamedMorris <notifications@github.com>:

**Comment by BielBdeLuna** [comment]
solved
