### ISSUE TITLE
HDR issues: colour artefacts

### ISSUE THREAD

**Issue by BielBdeLuna** [RobertBeckebans/RBDOOM-3-BFG#264]
I see there are some colour artefacts mayabe due some stages superposing amongst others in the shaders?

**Comment by BielBdeLuna** [comment]
now I see, the colour artefacts occur when using r_useHalfLambert 0

**Comment by BielBdeLuna** [comment]
noted that r_useHalfLamber 0 still looks wonky, some textures show an inverted colour with r_useHDR 1 after "reloadingShaders".

also on another note, it seems that the tonemapper lets non white pure colour clip in a non HDR kind of way, example redder than pure (1.0, 0.0, 0.0) red colors don't seem to produce bloom showing areas of clipped red pixels (I wonder if this has to do with the way the engine sums the colours)

**Comment by RobertBeckebans** [comment]
The issue was that the interaction shaders didn't clamp the N dot L product for lambert. It is the cosine of the angle between those vectors and that means it ranges from -1 .. 1. Clamping it to 0..1 solved it.
