### ISSUE TITLE
HDR branch rendering glitch noise. (Linux x64 - nVidia)

### ISSUE THREAD

**Issue by aFoxNamedMorris** [RobertBeckebans/RBDOOM-3-BFG#267]
Checked out the HDR branch for testing. Compiles, runs, menus work... 

For whatever reason, the entire in-game render looks like this:

<a href="http://i.imgur.com/vHQOuGG.png">
  <img src="http://imgur.com/vHQOuGGl.png" />
</a>

Lemme know what information I need to retrieve, and I'll get straight on it.

EDIT: Only seems to happen when AA is enabled. I was playing in fullscreen, by the way.

**Comment by BielBdeLuna** [comment]
yeah AA doesn't seem to work for me, it locks off RBDoom3BFG.

**Comment by BielBdeLuna** [comment]
this is somewhat solved isn't it?

**Comment by RobertBeckebans** [comment]
Solved
