### ISSUE TITLE
Light sources penetrating through doors

### ISSUE THREAD

**Issue by ghost** [RobertBeckebans/RBDOOM-3-BFG#268]
I was testing RB with the mc underground map, I noticed lights from other rooms penetrating through doors. 
![example](https://cloud.githubusercontent.com/assets/8399958/11997332/662be1d8-aa81-11e5-88c5-656f5b8e1a49.png)

**Comment by BielBdeLuna** [comment]
is shadowmapping enabled?

**Comment by Yetta1** [comment]
@BielBdeLuna Yes it is

**Comment by BielBdeLuna** [comment]
I think this door did something like this with other mods, i guess it has to do with lights that are out of the portal that door is closing.

if you do r_useHDR 0 and r_useShadowMapping 0 you still see problems with this door? if you do r_useHDR 0 and r_useShadowMapping 1 is still there the issue?

**Comment by Yetta1** [comment]
Still the same with r_useHDR 0 and r_useShadowMapping 0 & 1. There are no mods, it's running from a fresh install.
![example2](https://cloud.githubusercontent.com/assets/8399958/11997619/dfafefc0-aa88-11e5-820f-57640e96fd26.png)

**Comment by BielBdeLuna** [comment]
so this had nothing to do with the hdr changes isn't it?

**Comment by Yetta1** [comment]
@BielBdeLuna No, doesn't seem like it, not sure what is causing it, I haven't seen this happen on vanilla BFG. I've seen it in one of the older RB builds as well. I'm using a new build which Robert linked for me earlier today.

**Comment by RobertBeckebans** [comment]
I think this was introduced by the BFG edition and I saw this in the vanilla build too.

**Comment by RobertBeckebans** [comment]
It is also annoying that only 2 doors in the entire game are affected by this.
