### ISSUE TITLE
CMAKE: Visual Studio 2015

### ISSUE THREAD

**Issue by bryansee** [RobertBeckebans/RBDOOM-3-BFG#272]
At the moment, only Visual Studio up to 2013 can be made via CMAKE. However, there are no paths for VS2015.

**Comment by RobertBeckebans** [comment]
I'm going to add VS 2015 support this week.

**Comment by bryansee** [comment]
Keep me (and others) informed.

**Comment by RobertBeckebans** [comment]
Solved.
