### ISSUE TITLE
Required XINPUT1_3.dll and X3DAudio1_7.dll are missing

### ISSUE THREAD

**Issue by bryansee** [RobertBeckebans/RBDOOM-3-BFG#273]
Hello, I'm using Windows 10, and I got two system error messages saying that XINPUT1_3.dll and X3DAudio1_7.dll are missing upon starting up RBDoom3BFG. Is there any way to solve this problem?

**Comment by RobertBeckebans** [comment]
Does the original DOOM 3 BFG .exe work?

**Comment by bryansee** [comment]
Without DirectX June 2010 installed, it won't. It's better to work independently from DirectX.

**Comment by RobertBeckebans** [comment]
Latest master branch does not require the DX 10 SDK with VS 2015.
