### ISSUE TITLE
SMAA branch: Ubuntu 15.10 Intel Sandy Bridge mesa oibaf drivers, can't start the engine

### ISSUE THREAD

**Issue by BielBdeLuna** [RobertBeckebans/RBDOOM-3-BFG#275]
I copied the base from the branch to the base folder as always.
I sarted the engine with 
```
+set r_useOpenGL32 2
```
and without it and I always get the following error:
```
----- R_InitOpenGL -----
Initializing OpenGL subsystem
No usable GL mode found: Invalid windowInitializing OpenGL subsystem
No usable GL mode found: Invalid windowUnknown command 'vid_restart'
Sys_Error: Unable to initialize OpenGL
```

**Comment by BielBdeLuna** [comment]
I tried the new branch in Windows (with the version you posted in the https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/266 issue) I can enter in the engine without any hassle, 
I can change r_AntiAliassing but after vid_restart I don't see any antialiasser applied with any of the options

**Comment by BielBdeLuna** [comment]
solved

**Comment by Yetta1** [comment]
Please keep stuff for slowpoke hardware, as I am one of those users. :P
