### ISSUE TITLE
PBR textures support with metal workflow

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#277]
PBR with the metal workflow which means diffusemap is replaced with albedo/metalcolor and specmap is replaced with RGBA = ( roughness, metalness, AO, displacement ).

I don't want to modify the existing materials to support this so I suggest to just look for a _rmaod suffix in the file names.

example:
textures/base_wall/lfwall27d_s.tga becomes

textures/base_wall/lfwall27d_s_rmaod.png for  ( roughness, metalness, AO, displacement ) if you want tesselation support

textures/base_wall/lfwall27d_s_rmao.png for  ( roughness, metalness, AO ) without displacement maps.

The albedoM maps still have to be in the sRGB format and the alpha channel is still used for opacity tests. The new specmap values have to be in linear RBG values.

This is the basic reflection map output format Quixel Suite supports in the UE4 optimized profile.
Allegorithmic Substance Designer materials can be configured the same way.

**Comment by BielBdeLuna** [comment]
great!

**Comment by HeadClot** [comment]
I just saw this and +1

**Comment by aFoxNamedMorris** [comment]
So wait... Texture packs that control the tesselation/displacement of the geometry? Or is it just a texture effect? Either way, this sounds awesome!

**Comment by RobertBeckebans** [comment]
Parallax techniques suck because they add annoying complexity to the shaders. And even if parallax mods exists they are half-assed and ignore that non-interaction shaders need the offset too.
So tesselation is the more interesting approach. AO is still very important with PBR because you want to reduce the amount of indirect light reflections on your models with it. It is only very important that AO is not baked into the albedo/diffuse texture beacuse you need AO for both, diffuse reflections and specular reflections. And having AO in a separate channel then it allows to mix it into the SSAO renderer result.

**Comment by aFoxNamedMorris** [comment]
That makes perfect sense. This also allows for monsters and other complex
objects to have a higher resolution look, without having to add more
geometry. Excellent. Would these displacement effects have a falloff value
for optimizing performance?

**Comment by Yetta1** [comment]
I've made some PBR textures, but it looks nothing like it did in AwesomeBump, most likely just lighting. Self-Shadowing Relief shaders would also be nice, I prefer them over Parallax with AO, as the shaders grab shadows from the light sources.

**Comment by aFoxNamedMorris** [comment]
Is there an ETA for these features? If so, are there any WIP screen captures to look at?

**Comment by TheNorseHorse** [comment]
I agree with Fox, how's it going? I'd love to see how it looks... and how it stacks up to id Tech 6...

**Comment by RobertBeckebans** [comment]
PBR texture support is making progess.
From left to right -> roughness
From top to bottom -> metal

http://imgur.com/a/Q0UA8

**Comment by aFoxNamedMorris** [comment]
@RobertBeckebans Nice! And once finished, this will be available through texture packs? Or is it a bit more involved than that?

**Comment by BielBdeLuna** [comment]
great! are you using a specified cubemep for those reflections or are those models getting the cubemap from an entity placed on the map?
will roughness be another blend option (maybe even replace the concept of a "specularmap" with "roughnessmap") ?
will "metalness" become the new "specularmap" maybe (or maybe maintain the name but use the specular map as a percentage value instead of a full power value)? so "matal" controls de percentage of specularity versus the albedo power (the 100% colour being from the incident light so no new light gets created), and "roughness" controls the blurring of the specularity?


anyways great work!

**Comment by RobertBeckebans** [comment]
PBR textures require IBL and I created the necessary textures with the "makeAmbient" console command.
It looks like code from Rage that was nowhere called. It was slow as hell so I optimized it with a few tricks from common PBR implementations.
See https://github.com/RobertBeckebans/RBDOOM-3-BFG/commit/7389fece98f76fff7361aeb0c58f13a3ce57ab02

PBR textures require at least one default ambient (irradiance, 128*128) and specular (irradiance, 256*256, 7 mips) cubemap.
We could use a default UAC cubemap, a default cubemap for hell maps and so on as a fallback.

This is how the new materials look like: https://github.com/RobertBeckebans/RBDOOM-3-BFG_assets_mod1/blob/master/materials/materialorb.mtr

I created the Git repo https://github.com/RobertBeckebans/RBDOOM-3-BFG_assets_mod1 for content examples. It also contains Crytek's Sponza Atrium which I customized in Blender so the meshes have proper Doom style materials names.  RBDOOM load the entire scene as a Collada mesh and ASE and LWO formats suck and I don't want to deal with outdated Blender addons anymore.

You can load it with "devmap sponza".

**Comment by BielBdeLuna** [comment]
this is great!

**Comment by Yetta1** [comment]
This is awesome.

**Comment by aFoxNamedMorris** [comment]
May I ask if/how you might implement fresnel? It would go a long way to improving the look of environments in RBDoom3BFG, if you ask me.

**Comment by Yetta1** [comment]
@aFoxNamedMorris I asked in another post about anistropic highlighting for gloss, BielBdeLuna suggested that I try fake it with normals, I've faked a fresnel effect before in Blender Game Engine with inverted normals and tweaked with a ramp node so it only effects the rim of the model. My only guess here is to make a normal map that only has higher values on the edges for the fresnel effect, then making the engine render that normal map to specular. Maybe I'm way off with it, I only model, still trying to understand the 3D rendering process.

**Comment by BielBdeLuna** [comment]
@RobertBeckebans I can't compile it I get this:

```
CMakeFiles/RBDoom3BFG.dir/d3xp/Light.cpp.o:(.rodata._ZTV10idGameEdit[_ZTV10idGameEdit]+0x30): undefined reference to `idGameEdit::ParseSpawnArgsToRenderEnvprobe(idDict const*, renderEnvironmentProbe_t*)'
collect2: error: ld returned 1 exit status
CMakeFiles/RBDoom3BFG.dir/build.make:13468: recipe for target 'RBDoom3BFG' failed
make[2]: *** [RBDoom3BFG] Error 1
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/RBDoom3BFG.dir/all' failed
make[1]: *** [CMakeFiles/RBDoom3BFG.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by RobertBeckebans** [comment]
@BielBdeLuna I fixed the CMake file. It should compile now.

**Comment by BielBdeLuna** [comment]
great! now it compiles, unfortunately when I enter the sponza map I get a segfault:

```
(...)
[Load AAS]
loading maps/sponza.aas_cyberdemon
Entering doom_main()
Exiting doom_main()
Spawning entities
signal caught: Segmentation fault
si_code 1
Trying to exit gracefully..
session->GetSaveGameManager().CancelToTerminate();
soundSystem->StopAllSounds();
Stop();
--------- Game Map Shutdown ----------
(...)
```

**Comment by Yetta1** [comment]
Hitting 3fps with the Sponza map on a GT 630 4GB. I am assuming the card struggles to render all the geometry at the same time.

**Comment by BielBdeLuna** [comment]
you can also open the sponza map with the master branch (without any of the PBR improvements), is it also hitting you on the fps?
