### ISSUE TITLE
When disabled, soft shadow

### ISSUE THREAD

**Issue by wanisea** [RobertBeckebans/RBDOOM-3-BFG#281]
When disabled, soft shadow
 The default shadow does not apply.

**Comment by kujeger** [comment]
seems that the stencil shadows don't work when HDR is enabled (use r_useHDR 0 to disable)

**Comment by RobertBeckebans** [comment]
It is correct. The HDR rendertarget has no combined depth/stencil buffer and I'm not sure if I can get it to work. Previous attempts a few years ago with OpenGL failed. Maybe we have better drivers today.

**Comment by BielBdeLuna** [comment]
@RobertBeckebans do the softshadows use the cascaded shadow method or this method it's only used for direct light shadows. if not, could the use of a LOD for shadows speed up the rendering of those accepting certain loss of precision for the farthest shadows in return?
