### ISSUE TITLE
Vulkan Support

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#287]
I hope we will get rid of most performance issues and OpenGL driver bugs with this.

**Comment by Yetta1** [comment]
I hope so too. There is a Vulkan group on Github, I remember them having some links to tutorials and news. I believe that it will also sort out some issues on Linux and run quite well with HSA hardware.

Dota 2 has Vulkan if I understand correctly, however I think devs need to ask Valve for that version.

**Comment by romulus2k4** [comment]
+1 for Vulkan!

**Comment by aFoxNamedMorris** [comment]
This is a must for efficient rendering on non-Windows platforms.

**Comment by BielBdeLuna** [comment]
@aFoxNamedMorris let's see first how the drivers come out, it seems for AMD users there is no Vulkan without the latest graphic cards, and I don't know about Nvidia or Intel. but I bet they will use Vulkan to sell more GPUs so I bet they will banish old cards from it at the beginning, let's see how long before Mesa has support for Vulkan. Which is very unfortunate!

**Comment by Yetta1** [comment]
I read somewhere that Vulkan will work with cards that has OpenGL 3.3 and up.

**Comment by DanielGibson** [comment]
On 01/20/2016 10:15 PM, Yetta1 wrote:
> I read somewhere that Vulkan will work with cards that has OpenGL 3.3
> and up.
>

Maybe it can, theoretically, from the minimal features it demands from 
hardware.

But it's up to the driver implementors (usually: GPU vendors) which GPUs 
will actually be supported.
So if AMD decides to only support the last two  generations, you're 
screwed with older hardware, until someone writes an open source vulkan 
driver for it.

**Comment by Yetta1** [comment]
Well when considering AMD's financial issues, I doubt they would go to far back in their GPU line for Vulkan support. I think Vulkan will shine on their AM1 and FM2 platforms.

**Comment by DanielGibson** [comment]
http://phoronix.com/scan.php?page=news_item&px=AMDGPU-Vulkan-Driver-Only

at least on Linux "I've just received confirmation from AMD that their 
forthcoming Vulkan driver will only work with the AMDGPU DRM kernel 
driver." "The AMDGPU driver is what currently supports the Radeon R9 285 
"Tonga", R9 Fury "Fiji" series, Carrizo, etc. Basically, GCN 1.2 and all 
future GPUs."

http://www.phoronix.com/scan.php?page=news_item&px=Help-Bring-Older-GCN-To-AMDGPU
says this will only change if "the community" patches support for older 
GPUs into the AMDGPU driver.

**Comment by chasetheswift** [comment]
https://www.khronos.org/assets/uploads/developers/library/overview/vulkan-overview.pdf

In Khronos' official PDF brief they state gpus that can run OpenGL ES 3.1, OpenGL 4, and up can run Vulkan. Any shortcomings on that is fault of the GPU manufacturer.

**Comment by Yetta1** [comment]
So the engine will have to have an upgrade on the OGL version?

**Comment by chasetheswift** [comment]
In theory, it could. Depends on the goals are when porting to Vulkan, if even that is a desire of group. It sounds like Vulkan support will be choppy for a bit on non-Intel gpus so the community may wish to stick to OpenGL for the time being.

**Comment by spannerman79** [comment]
It would be something to consider but right *now* for cross GPU support I'd say stay with OpenGL - *for now*

Until there is news from Intel in regards to Vulkan support

**Comment by Yetta1** [comment]
It should have some good support for AMD at least, since Mantle was the precursor of Vulkan. The FM2 APU's already showed what mantle was capable of, though not the performance of high end, but great performance for the price range.

**Comment by chasetheswift** [comment]
Intel seems all in and their open source driver is their linux driver. Nvidia is talking about it but behind closed doors. AMD said that the Vulkan driver was only going to be in the closed driver and only for new gpus. The linux community is not taking the news well. On windows it's all DX12, thus I haven't seen much for windows support.

**Comment by chasetheswift** [comment]
I did some digging. Nvidia is all in with Vulkan but what GPUs will get support is yet to be disclosed. They have officially added a Vulkan section to their gameworks section. They say that once Vulkan is released into the wild they will update said developer page with more presentations and whatnot. As I said before, Vulkan support will be choppy for a while.

**Comment by Yetta1** [comment]
Nvidia will have Vulkan support for Geforce 600 cards and up.

**Comment by BielBdeLuna** [comment]
does OpenGL use the Vulkan intermediate shaders for anything? the SPIR-V, maybe adopting SPIR-V and using it in OpenGL would be the first step? so it would go CG/GLSL --> SPIR-V --> OpenGL / Vulkan

**Comment by Yetta1** [comment]
If I remember correctly there will also be support to use legacy GL with Vulkan. PowerVR and Intel really need Vulkan to improve performance for real-time application.

Here they talk about SPIR-V and Vulkan with an intermediate language.
https://www.youtube.com/watch?v=qKbtrVEhaw8

**Comment by BielBdeLuna** [comment]
SPIR-V is an intermediate language based on GLSL that should do somewhat the same idTech does when compiling the CG to GLSL, but instead of the program doing it, the SPIR-V interface would do it, the benefit being that the output is already prepared for whatever graphics library we decide to use.

**Comment by Yetta1** [comment]
Never heard of IIRC.

**Comment by BielBdeLuna** [comment]
:) IIRC "if I remember correctly"

**Comment by Yetta1** [comment]
<Derp, Lol ok, that makes sense, was wondering what you meant because I couldn't find anything on a IIRC CG.

**Comment by RobertBeckebans** [comment]
You can compile any language to SPIR-V byte. It would be even possible to compile C++ to SPIR-V.
Khronos provides a GLSL to SPIR-V compiler that makes the integration process easy.

**Comment by aFoxNamedMorris** [comment]
Vulkan spec and shit just went live! Everybody hold onto your asses!

**Comment by RobertBeckebans** [comment]
Just in time for my birthday :dancer: :+1:

**Comment by Yetta1** [comment]
Yup saw the notification on the Github Vulkan page. Can't wait.

**Comment by kortemik** [comment]
https://www.khronos.org/news/press/khronos-releases-vulkan-1-0-specification

**Comment by TheNorseHorse** [comment]
Don't mean to be off-topic, but could someone tag [this](https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/295) as an Enhancement?

**Comment by BielBdeLuna** [comment]
a new renderer an enhancement? it's a feature isn't it?

**Comment by TheNorseHorse** [comment]
The enhancement was adding Depth of Field to the post processing suite.
Back on Topic, how's Vulkan?

**Comment by aFoxNamedMorris** [comment]
Necropoke. (Sorry/Not sorry.)

**Comment by Yetta1** [comment]
nVidia dropped Vulkan support for Fermi based GPU's, which sucks since my Geforce is Fermi based and I have tested Vulkan on it on Linux, but no love on Windows, just crashes.

**Comment by mhalano** [comment]
Any news on this since vkneo is coming?
