### ISSUE TITLE
Flashlight looks weird in latest master

### ISSUE THREAD

**Issue by urbenlegend** [RobertBeckebans/RBDOOM-3-BFG#290]
I just updated to the latest master and the flashlight effect seems really weird. It looks like a really bright 2D texture plane rotating in front of you. Looks really bad and also blocks your view because its so too opaque.
![screenshot from 2016-01-23 11-58-56](https://cloud.githubusercontent.com/assets/241316/12532503/c1c93af8-c1ca-11e5-9a12-91543000092a.png)

**Comment by aFoxNamedMorris** [comment]
Yeah. Noticing that here, too. It's like the blend mode is no longer set correctly. May have to do with the recent renderer changes, but I'm no expert.

**Comment by Yetta1** [comment]
I've noticed it too, the flashlight glare is quite opaque and at times the projection hit of the light at the end can be barely visible. I've disabled HDR, SSAO, SSGI and exposure, the problem doesn't seem to be related there. It may be that the textures transparency levels are too high or the material ".mtr" shaders blending code needs to be adjusted.

**Comment by kujeger** [comment]
seems to be only hdr related for me -- doing "toggle r_usehdr; reloadshaders" switched between "broken" flashlight and normal flashlight.
[HDR 1](http://kumini.kujeger.net/filedump/rbdoom-3-bfg-20160128-115508-002.png)
[HDR 0](http://kumini.kujeger.net/filedump/rbdoom-3-bfg-20160128-115511-003.png)

**Comment by RobertBeckebans** [comment]
It is probably just one shader that outputs the texture in sRGB instead of
linear RGB. I will look into it at the weekend.

2016-01-28 11:58 GMT+01:00 Nikolai Vincent Vaags <notifications@github.com>:

**Comment by kujeger** [comment]
I also see something similar with steam/smoke textures at the start of lost missions' map "exis 2". Same root cause?
[HDR 0](http://kumini.kujeger.net/filedump/rbdoom-3-bfg-20160201-183011-002.png)
[HDR 1](http://kumini.kujeger.net/filedump/rbdoom-3-bfg-20160201-183008-001.png)

**Comment by RobertBeckebans** [comment]
Maybe I need to add a hack for a better flashlight material. I looked into this issue using GLIntercept there is nothing wrong with the shaders. The flash light effect is added in linear RGB and tonemapped to sRGB like everything else in the scene later.

**Comment by BielBdeLuna** [comment]
some transparent textures act inversely, are too transparent, an example the "volumetric" lights done with particles that one can see around the teleporter to hell on Delta labs, the effect is almost invisible.
Also the cobwebs in alpha labs 2 are also almost invisible, as well as the "souls" emanating from the corpses that "the artefact" can obtain in d3xp are also almost invisible

most of those effects are particles as well as transparent surfaces

**Comment by kujeger** [comment]
imp fireballs are also a lot less visible with HDR

**Comment by jpcy** [comment]
I haven't checked, but it looks like the problem is caused by blending in linear space.

**Comment by y2keeth** [comment]
ty this lesss annoying extract to your bfg directory http://www.moddb.com/mods/doom-3-bfg-hi-def/downloads/flashlight-fix
