### ISSUE TITLE
Broken SSAO with AMD Radeon

### ISSUE THREAD

**Issue by chadady** [RobertBeckebans/RBDOOM-3-BFG#291]
Latest sources cause the display to 'smudge' as you pan the view around.  The display cleans up if you go into the console, and simply hit 'enter'.  Release 1.0.3 does not have this problem.

Ubuntu 14.04 LTS
Using radeon-crimson-15.12 video drivers.
AMD FX(tm)-8350 Eight-Core Processor
AMD Radeon HD 7900 Series video card

Thanks!

[log.txt](https://github.com/RobertBeckebans/RBDOOM-3-BFG/files/102018/log.txt)
![doom3smudge](https://cloud.githubusercontent.com/assets/16856608/12532622/7e72e01c-c1e6-11e5-997d-c65817a6f63c.png)

**Comment by romulus2k4** [comment]
I have the same issue. Enter "r_useSSAO 0" in the console and this problem will go away. It's due to SSAO implementation not working with AMD's OpenGL drivers.

**Comment by chadady** [comment]
That took care of it - thanks!

**Comment by RobertBeckebans** [comment]
Thanks for report. It shouldn't happen because I don't see any shader compile error in the log.txt.

**Comment by Eyef** [comment]
I have same bug on my Radeon R7 260x (win7 x64, latest video drivers)
https://youtu.be/ks37QIBIe3U

[qconsolelog.txt](https://github.com/RobertBeckebans/RBDOOM-3-BFG/files/129301/qconsolelog.txt)

**Comment by BielBdeLuna** [comment]
although this is a bug, is a great looking bug :) a very interesting looking bug

**Comment by RobertBeckebans** [comment]
That is interesting. Thanks for the report.

**Comment by Szalacinski** [comment]
I can report that this happens on the nouveau driver version 1:1.0.10-1ubuntu2 as well.

**Comment by wwizz** [comment]
I have the same issue on NVIDEA K1100M

**Comment by revelator** [comment]
AMD R9 390 also has this.

**Comment by romulus2k4** [comment]
I gave up on the hopes of using this feature while using this source port, and you should too. You'll be able to enjoy the game a lot more with SSAO turned off.

**Comment by revelator** [comment]
Guess we cant have it all... 
would have been nice though :/
SSAO was also a big problem with the old sikkmod implement.
