### ISSUE TITLE
Grabber distortion effect error with HDR

### ISSUE THREAD

**Issue by kujeger** [RobertBeckebans/RBDOOM-3-BFG#292]
Using the Grabber with r_useHDR = 1 results in a distortion effect that's somewhat broken.

[HDR 0](http://kumini.kujeger.net/filedump/rbdoom-3-bfg-20160128-184458-002.png)
[HDR 1](http://kumini.kujeger.net/filedump/rbdoom-3-bfg-20160128-184449-001.png)

**Comment by BielBdeLuna** [comment]
I confirm the issue, and also I would add another, that "blurring" on the sides of the screen, when the marine gets the artefact in the first level of d3xp, don't show up

**Comment by RobertBeckebans** [comment]
Should be fixed now.

**Comment by BielBdeLuna** [comment]
I confirm it, all is fixed! :)
