### ISSUE TITLE
The procedure entry point CoInitialize could not be located in the dynamic link library avcodec-57.dll. 

### ISSUE THREAD

**Issue by deuxsonic** [RobertBeckebans/RBDOOM-3-BFG#299]
After building the solution in VC++ 2010 32-bit, I copied the ffmpeg DLLs into the root of doom3bfg, but when it starts, I get the following error:

The procedure entry point CoInitialize could not be located in the dynamic link library avcodec-57.dll.

**Comment by TheLonerD** [comment]
Looks like you compiled rbdoom with old ffmpeg libs
Download **ffmpeg-dev-libs** 32 or 64 bit from zeranoe site, unzip to neo/libs/ffmpeg-win32 (or neo/libs/ffmpeg-win64) and try to recompile. That should work.

**Comment by deuxsonic** [comment]
I used the exact file that the readme links to. Should I always be using the latest one instead?

**Comment by deuxsonic** [comment]
The very newest 32-bit build fails to work on XP. "The procedure entry point _wfopen_s could not be located in the dynamic link library msvcrt.dll."

I tried building with the version listed in the last post here: https://ffmpeg.zeranoe.com/forum/viewtopic.php?t=2477

but once again I get that same original error.

**Comment by RobertBeckebans** [comment]
I think the FFmpeg binaries are compiled with VS 2012 so you need to build RBDOOM-3-BFG with at least VS 2012 or newer or rebuild FFmpeg with VS 2010.

**Comment by deuxsonic** [comment]
The ffmpeg source doesn't seem to come with any project files for building it in VC++. Am I missing something?

**Comment by TheLonerD** [comment]
@deuxsonic did you read this? https://trac.ffmpeg.org/wiki/CompilationGuide/MSVC

**Comment by deuxsonic** [comment]
I have now. This is becoming a major project.

**Comment by TheLonerD** [comment]
@deuxsonic any progress?

**Comment by deuxsonic** [comment]
Unfortunately not. :( It bothers me because I like the changes that this fork makes, but I'd like to tinker with the source and I can't really do that if I can't build it to begin with.

**Comment by RobertBeckebans** [comment]
You can upgrade to a newer Windows with VS 2013 or VS 2015 free editions. I suggest those anyway because of the C++11 support. The other option is to compile RBDOOM-3-BFG without FFmpeg support and you just miss the videos in that case. You can either change the default value in the CMakeLists.txt option(FFMPEG .. OFF) or change the appropiate cmake-vs2010-32bit.bat and append -DFFMPEG=OFF to the cmake line.
CMake makes this project highly configurable.

**Comment by deuxsonic** [comment]
Going to try compiling without FFmpeg to see if I can do that. If I can make the changes and compile like that, then maybe I can have someone else compile my code.

**Comment by deuxsonic** [comment]
Okay, it builds without issue with FFmpeg left out. I don't understand why that would keep all of this from working...
