### ISSUE TITLE
Soft Shadows induces a very consistant and reproducible 20 fps loss

### ISSUE THREAD

**Issue by DistantThunder** [RobertBeckebans/RBDOOM-3-BFG#305]
Using:

Arch Linux x86_64
GTX 780 with 358.16 drivers.
RBDOOM on latest GIT (commit 7728dc3)

Enabling Soft Shadows incurs a 20 fps loss all the way down to 40 fps in certain areas of the game, notably in many parts of the Alpha Labs Sector 3.

The framerate decrease is always immediate and very stable. It would hoover for a few seconds down to 36 but will stabilize at 40 most of the time.

As soon as the camera is away from the incriminating scene, framerate immediately bumps to 60.

When disabling vsync, if at 120 fps, the framerate will fall back to 100.

I circumvented the problem by forcing composition on the window, basically creating a border-less window mode but this is less than ideal.

**Comment by romulus2k4** [comment]
The same thing happens with AMD GPUs too, only it happens at a regular basis.

**Comment by BielBdeLuna** [comment]
I wonder if the common shadows  ( those that are not done by parallel lights which use a LOD system ) could use a LOD system also so distant lights used further scaled down shadow maps

**Comment by Yetta1** [comment]
I've also had huge fps drops with Shadows going from 60 to 15 in some areas on a nVidia card with Windows 10.

**Comment by BielBdeLuna** [comment]
I see now that the common shadows also use a LOD system

**Comment by Yetta1** [comment]
The shadows are improving, but on my side it is barely visible with r_useHDR turned on when I play D3. I'll test the shadows with various light intensities when I get the time. The HDR does brighten the scenes quite well, good for daylight scenes too, but need shadows to be more prominent when getting direct light. My settings might also be incorrect, deleted my old config to see if their is a different, did not work.

**Comment by RobertBeckebans** [comment]
I already implemented the shadow LOD system 2 years ago.
Steel Storm 2 has some interesting changes in the renderer and I just merged some shadow mapping performance improvements back to RBDOOM. You might want to check it out. Right now HDR and SSAO have still a bigger performance impact on my GTX 660 Ti. 
I have stable 110-120 fps at 1080p with shadow mapping alone.

**Comment by BielBdeLuna** [comment]
yeah and I just seen that now, I though the LOD was just for the direct light shadows, but no, it's for all lights.

**Comment by Zetchzie** [comment]
Same issue for me with my RX 480 4GB on my intel i5 6K

**Comment by Dual-Boot** [comment]
Hello,

I tested just to see enhancement and I can agree with others about it. Soft Shadows kills performances.
Windows 10 64 Bit, AMD Phenom II x4 965BE, Radeon R9 390X.

   Regards,

**Comment by Calinou** [comment]
Shadow quality can be decreased using `r_shadowMapLodBias 2` in the console (try values between 0 and 4). This should increase rendering speed significantly.

I think it'd make sense to use `2` by default.
