### ISSUE TITLE
Question About Menus

### ISSUE THREAD

**Issue by deuxsonic** [RobertBeckebans/RBDOOM-3-BFG#306]
I'm wondering how to make modifications to the game's menus. Are they in the game code?

**Comment by RobertBeckebans** [comment]
It is very difficult to change the menus because they were built with Flash and we don't have the Flash source files. However answered some questions about this stuff in this thread: http://idtechforums.fuzzylogicinc.com/index.php?topic=280.msg3340#msg3340

**Comment by deuxsonic** [comment]
Were the original release DOOM 3 menus built with Flash? I know they didn't use Bink for the videos and keeping it the same format would have removed what has been a troublesome dependency for me. I'm not clear why those needed to be changed.

**Comment by LinuxDonald** [comment]
What about recreateing the menus in native code?

**Comment by BielBdeLuna** [comment]
in vanilla Doom3 menus where done with the GUI system, in order to get the menus to work one has to enable the GUI system for the full screen. the videos in vanilla doom3 where encoded in the Quake3 *.roq format with wave files synced to the video.

GUI files are text files with tokens that define the animations and interactions of the in-game GUI

**Comment by RobertBeckebans** [comment]
The menu code is based off the menu code from Rage. However the BFG edition does not use much of the Flash functionality the engine can handle. The Flash files almost only define the sprites and how they are moved and blended. 99% of the logic behind the menus is written in C++ in the neo/d3xp/menus/* code. So the menus are in C++ and the Flash files are only accessed to know where to place the buttons and how to layout stuff.

**Comment by BielBdeLuna** [comment]
Open Tech Engine has added ceGUI to the mix, which is a new GUI layer to the engine for full screen menus https://github.com/OpenTechEngine/OpenTechBFG

**Comment by mattiascibien** [comment]
@deuxsonic I have made a new menu here which is supposed to load mods: https://github.com/mattiascibien/RBDOOM-3-BFG/tree/modmenu

**Comment by RobertBeckebans** [comment]
The new BFG mod CstDoom3BFG https://www.moddb.com/mods/cstdoom3-bfg has many custom menus and they approached it as I suggested. Export the current files to JSON, edit the JSON menus and reload them into BFG.
