### ISSUE TITLE
SSAO problem (Radeon 7859 + Catalyst 16.4)

### ISSUE THREAD

**Issue by donizettilorenzo** [RobertBeckebans/RBDOOM-3-BFG#308]
With SSAO enabled a black blob forms on glass surfaces (->shader accumulation/integration problem I think) and remains on the screen, moving around.

https://s30.postimg.org/5s6ruc741/RBDoom3BFG_2016_04_13_21_03_45_484.png

**Comment by Eyef** [comment]
https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/291

**Comment by Lullabye** [comment]
It SSAO works when "r_useHDR 0" weirdly enough.

**Comment by donizettilorenzo** [comment]
Yes, but brightness falls down to 0.

**Comment by RobertBeckebans** [comment]
If it works with r_useHDR 0 then I have an idea how to fix it. I'm going try it this week.

**Comment by donizettilorenzo** [comment]
Brightness falls down *HOT*switching (in-game) the "r_useHDR" variable.
Restarting the game the brightness is fine

**Comment by RobertBeckebans** [comment]
When you change r_useHDR then you have to recompile the GLSL shaders by the command "reloadShaders" in the console.

**Comment by wwizz** [comment]
I have the same issue on NVIDEA K1100M

**Comment by coldtobi** [comment]
I'm seeing that too on my Intel HD Graphics 4000 (embedded in an i3-3227U )

rboom3bfg is compiled  from trunk git repo, however using system libraries in Debian. 

shows errors:
`./rbdoom3bfg +set r_useSSAO 1 +set r_useHDR 1`
works fine:
`./rbdoom3bfg +set r_useSSAO 1 +set r_useHDR 0`

(reloadShaders throws plenty of errors)

You said you have an idea how to fix it: Did you come up with some patch which I could test?

**Comment by Evilbaka** [comment]
reloadShaders fix it for a second, but if I move camera, black blobs and dots appears again

**Comment by ashalkhakov** [comment]
I had a similar problem (screen blacks out after a few seconds of play). Disabling SSAO and HDR fixed it for me. `lspci | grep VGA` gives me `00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)` and I use the RBDOOM-3-BFG-1.1.0.
