### ISSUE TITLE
DOOM  1 & 2 odd texture bug

### ISSUE THREAD

**Issue by nihil-2019** [RobertBeckebans/RBDOOM-3-BFG#315]
[Screenshot](https://voatpic.me/image/EBF327AD62)

As you can see in the screenshot above, the classic DOOM games have a strange texture bug that makes them literally unplayable.

I am running Arch Linux, with beta propietary NVIDIA drivers (which are currently the same version as stable.) rbdoom3bfg was installed from AUR.

Below is a log of the output when i run rbdoom, select DOOM 1 & start a new game.

http://pastebin.com/dp13vv8d

**Comment by rbaprado** [comment]
+1

**Comment by ssv-170379** [comment]
+1

**Comment by baosen** [comment]
+1
Arch Linux, Nvidia blob
using
https://aur.archlinux.org/packages/rbdoom3-bfg-git/

**Comment by mmayfield1** [comment]
Me too
Fedora 25
Nvidia Optimus happens with both intel graphics and nvida
