### ISSUE TITLE
Weird graphical issue with Radeon driver

### ISSUE THREAD

**Issue by parkerlreed** [RobertBeckebans/RBDOOM-3-BFG#316]
![1463618994](https://cloud.githubusercontent.com/assets/841440/15379356/61c52380-1d3a-11e6-95dd-3b066d4fb805.png)

No your screen is not broken... Using an R7 260x on the open source drivers. Menu displays fine but in game it's all sorts of messed up. Disabled the extra effects in the menu but nothing helped.

Arch x86_64
rbdoom3-bfg-git r597.a884b08-1

**Comment by parkerlreed** [comment]
Seems to be the same issue as #291 and #308 but this is definitely on the OSS drivers.

**Comment by sunofsparda** [comment]
r_useHDR=0 does fix it
