### ISSUE TITLE
Update on Vulkan support?

### ISSUE THREAD

**Issue by btegs** [RobertBeckebans/RBDOOM-3-BFG#317]
There was a story a while back about this project adding Vulkan support. Since the latest AMD and Nvidia cards support it via GNU/Linux and Windows, any updates on this?

https://www.phoronix.com/scan.php?page=news_item&px=Doom3-Vulkan-Talk

**Comment by RobertBeckebans** [comment]
Unfortunately, I had no time to work on this project for the past months but Vulkan support is still on my agenda.

**Comment by y2keeth** [comment]
https://github.com/DustinHLand/vkDOOM3 has a good start on it

**Comment by RobertBeckebans** [comment]
See https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/398

**Comment by y2keeth** [comment]
well there it is lol
