### ISSUE TITLE
BFG9000 doesn't work as intended

### ISSUE THREAD

**Issue by TheVoodoo** [RobertBeckebans/RBDOOM-3-BFG#318]
Seems to be a general BFG Edition problem.
The BFG9000 projectile doesn't attack enemies automatically with beam when they come in range of the projectile AFTER shooting. The projectile beam only attacks enemies when they are already in range when shooting.
The beam also won't be interrupted, when there are obstacles between the projectile and the enemy.

Is the projectile behavior hardcoded?

**Comment by Yetta1** [comment]
I've noticed this as well on D3BFG and RB. The beam only attacks NPC's in the camera view. I still wish it had the classic Doom behaviour.
