### ISSUE TITLE
Music in Doom 1 & 2 don't loop

### ISSUE THREAD

**Issue by Szalacinski** [RobertBeckebans/RBDOOM-3-BFG#322]
I tested the first and second levels.  The music doesn't loop.  The music on the level complete screen seems to do so, however.

**Comment by Szalacinski** [comment]
I just tested Doom 2.  It does the same thing.

**Comment by Szalacinski** [comment]
This probably isn't intentional, because I just pulled up PrBoom+ with the shareware version of Doom 1, and it loops just fine.

**Comment by Szalacinski** [comment]
Unlike my other closed issue, this bug persists after the Steam integrity check.

**Comment by Szalacinski** [comment]
Also, this doesn't seem to appear in the 1.0.3 version.  Only the latest version pulled from git.

**Comment by RobertBeckebans** [comment]
Confirmed that this happens with OpenAL builds and Windows 10 XAudio builds.

**Comment by SRSaunders** [comment]
Is this still an issue?  I can't duplicate this defect in the current master.  Classic music loops properly for me for Windows XAudio and macOS OpenAL (have not tested on linux).

**Comment by RobertBeckebans** [comment]
This seems to be fixed on Linux as well.
