### ISSUE TITLE
Add support for 720p in Doom 3

### ISSUE THREAD

**Issue by Szalacinski** [RobertBeckebans/RBDOOM-3-BFG#323]
My graphics card/driver doesn't ever seem to play nicely with 1080p games, but it always seems to work fine on 720p.  Any chance that this could be added in?

**Comment by BielBdeLuna** [comment]
the engine rescales the rendering resolution to the size of the screen in real time, but in fullscreen mode you can force it to have a resolution with r_customWidth and r_customHeight, the engine will resize the rendered image to fit the screen.

**Comment by Szalacinski** [comment]
Ok.  I'll close this issue then.
