### ISSUE TITLE
Possible fix for nospecular light entity arg

### ISSUE THREAD

**Issue by nbohr1more** [RobertBeckebans/RBDOOM-3-BFG#342]
I don't have BFG yet but I fixed the nospecular light entity argument in tr_render.cpp for The Dark Mod.

It looks like the same could be done on line 1718 tr_backend_draw.cpp

Fix:

if( !surfaceRegs[ surfaceStage->conditionRegister ] || vLight->lightDef->parms.noSpecular )

**Comment by BielBdeLuna** [comment]
great! thanks!
