### ISSUE TITLE
Stereoscopic modes are glitching

### ISSUE THREAD

**Issue by mburakov** [RobertBeckebans/RBDOOM-3-BFG#343]
Hi!

I'm on 64-bit linux with amdgpu-pro drivers. Video card is Radeon R9 Fury X.
Basically none of the stereoscopic modes work properly for me. They all look more or less the same:
![glitch](https://cloud.githubusercontent.com/assets/5390386/18219304/f7ebf8f2-7168-11e6-9d7b-11006e0510cf.png)
Menu works perfectly fine. Video is glitching the same way.

Do you need any logs or additional information?

**Comment by wtfbbqhax** [comment]
_Additional info:_
On OSX stereoscopic results in a blank black screen.
