### ISSUE TITLE
Screen is black when HDR on

### ISSUE THREAD

**Issue by railfish** [RobertBeckebans/RBDOOM-3-BFG#347]
When r_useHDR set to 1, screen goes black, but the menu and UI is no problem.
Use default config and change resolution to 2560x1440

Intel Core i7 4770
NVIDIA Geforce GTX 1060 6GB (Driver version 372.70)
16GB DDR3 2400
Windows 10 Pro 64bit 1607 (14393.187)
RBDOOM-3-BFG-1.1.0-preview3-win32-20160411-git-7728dc3

**Comment by rigred** [comment]
See issue here:

https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/357
