### ISSUE TITLE
rapidjson, please exchange it with a DFSG-compatible version

### ISSUE THREAD

**Issue by coldtobi** [RobertBeckebans/RBDOOM-3-BFG#350]
Hallo Robert,

I'm in the progress of packaging a new snapshot for Debian and I just saw that rapdidjson has been added as a new external library and it is being used SWF stuff (as far I could see is)

Would it be ok to look into replacing it with e.g. https://android.googlesource.com/platform/libcore/+log/master/json, a reimplementation of the library. Reason for the request is that the license of rapidjson is not free (as per Debian defintion) due to the problematic "Good not Evil" clause.
https://wiki.debian.org/qa.debian.org/jsonevil expands on this topic. 

Many thanks for considering.

coldtobi

**Comment by coldtobi** [comment]
PS: Seems that rapidjson has fixed it [1], so alternatively please pull to a more recent version. Thanks!

[1] https://github.com/miloyip/rapidjson/issues/377

**Comment by DanielGibson** [comment]
It wasn't "fixed", it was clarified that it hasn't been an issue to begin with, as it only affected a few test .json files (JSON_checker https://github.com/miloyip/rapidjson/tree/master/bin/jsonchecker) which are not included in this project.

**Comment by coldtobi** [comment]
Yes, you're right. 
So the bug can be closed (but it would be good to update the lib to latest anyway and maybe also document that the dir has been removed...)

**Comment by DanielGibson** [comment]
yeah, upgrading to the latest version is usually a good idea :)
