### ISSUE TITLE
Visual error on Intel HD 5500

### ISSUE THREAD

**Issue by duzenko** [RobertBeckebans/RBDOOM-3-BFG#357]
I just tried to compile and run RBDoom on my laptop.
Attached screenshots show how things look with setting by default and all off.
Is it trying to simulate the look from inside the helmet or something?
<img width="641" alt="untitled" src="https://cloud.githubusercontent.com/assets/1481807/19837709/25ffb864-9ec8-11e6-9972-150bc69d5feb.png">
<img width="641" alt="untitled2" src="https://cloud.githubusercontent.com/assets/1481807/19837743/c1408376-9ec8-11e6-9226-91757d8ea39f.png">

**Comment by y2keeth** [comment]
turn off ssao

**Comment by rigred** [comment]
It's as of now only possible to have either 
```
r_useSSAO 0 with r_useHDR 1
or
r_useSSAO 1 with r_useHDR 0
```
Having r_use SSAO 1 with r_useHDR 1 causes problems since the shaders are not set up correctly.

**Comment by BielBdeLuna** [comment]
@rigred in your opinion what could be improved in the shaders?

**Comment by rigred** [comment]
I'm not sure since I haven't looked into it that much. 
But the SSAO is clearly conflicting with the HDR exposure calculations if not something worse.

**Comment by mmayfield1** [comment]
using r_useSSAO 0 does not resolve it for me. Using r_useHDR 0 is the only thing that works

**Comment by uzyfeo** [comment]
I've found out it is issue with r_hdrAutoExposure set to 1 and not by r_useHDR nor r_useSSAO, at least on one of my rigs that has same issue.

**Comment by uzyfeo** [comment]
By the way, @rigred, it may be a driver bug or something, as I can run both on my GTX 1050 without issue, even on my notebook with R7 M340.

Only issue I'm experiencing releated to graphics are releated exclusively to HDR's AutoExposure option and the results of enabling it are same as duzenkos here.

NOTE: Issue only occures on my notebook's AMD GPU and I had same issue before with my older rig with 5770HD in it...
Maybe AMD and Intel both have issues with HDR's AutoExposure then?

**Comment by uzyfeo** [comment]
Hmm, found out by reading more issues it can happen on Nvidia GPUs too...
Anyway, I'm still suspecting that all issues releating to HDR are due to AutoExposure option.

**Comment by mmayfield1** [comment]
Changing AutoExposure options does not work for me.

**Comment by rigred** [comment]
I have just tested this with the new Mesa 17.2 build which appears to have solved the problem. For me everything is rendering as it should be.

**Comment by revelator** [comment]
on an AMD R9 390 the only thing that works is to totally turn of ssao, it neither works with hdr off or anything else for that matter on this card. Not really sure what might cause so differing bugs.
