### ISSUE TITLE
New Relative thumb movement feels awful(maybe bugged), please allow absolute(felt perfect) again.

### ISSUE THREAD

**Issue by kickymcassington** [RobertBeckebans/RBDOOM-3-BFG#358]
Unfortunately the new relative thumb movement feels awful(maybe bugged), please allow absolute again.

"Attempt at fixing left touchpad to use relative thumb movements for direction instead of absolute position. This may require tuning."

It may require tuning but i find this to be fundamentally worse then absolute. I've played tens of hours of Onward with the absolute control you had in version 4 without any issues.
I just tried the new system which requires me to drag my thumb to move forward, strafe and move backwards. I find this to be very nauseating compared to the "absolute" movement from version 4. The only problem with the control in version 4 was the right trackpad turning the character. 

Please let me know if there is a console command to revert to the absolute control in the meantime :)

ps- AMAZING WORK!

**Comment by Altair28** [comment]
Totally agree!

**Comment by Sjiron** [comment]
Agreed, please bring back previous movement style or allow the option.

**Comment by DanielGibson** [comment]
This is the wrong place to report that.
Apparently you're talking about 
https://github.com/Codes4Fun/RBDOOM-3-BFG/releases (or 
https://www.reddit.com/r/Vive/comments/5dqlnd/doom_3_bfg_mod_updated/ )
Which is by someone else (Codes4Fun, whoever that is).
So the corresponding github page is 
https://github.com/Codes4Fun/RBDOOM-3-BFG, but for some reason 
"Codes4Fun" seems to have no issue tracker on that project and didn't 
even bother to change the README to link to their fork instead of the 
original project.

If someone of you uses reddit, maybe try telling "Codes4Fun" there to 
change the project link in the README and open the github issue tracker.

**Comment by kickymcassington** [comment]
Thank you Daniel, sorry about sending this to the wrong place, hopefully we can track down Codes4Fun :)

**Comment by mindcode123** [comment]
Please make an Onward Style movement. Its so much better!

**Comment by jordanManfrey** [comment]
While you guys wait for an update I went ahead and made a fork with this change reverted.
https://github.com/jordanManfrey/RBDOOM-3-BFG/releases/tag/1.1.0-openvr5-x64ControllerChangeRevert

**Comment by DrRedDDS** [comment]
> While you guys wait for an update I went ahead and made a fork with this change reverted.
https://github.com/jordanManfrey/RBDOOM-3-BFG/releases/tag/1.1.0-openvr5-x64ControllerChangeRevert

@jordanManfrey , your update does not allow me to load saved games.  The load starts then goes back to the main menu.

**Comment by Codes4Fun** [comment]
Sorry, I didn't realize I had to manually enable issue tracking, but it is there now:

https://github.com/Codes4Fun/RBDOOM-3-BFG/issues

please close this issue as it doesn't belong here.

**Comment by Codes4Fun** [comment]
Also I reverted those changes also in my latest build.

**Comment by jordanManfrey** [comment]
Understood, I've deleted my fork 😉

**Comment by kickymcassington** [comment]
Thanks again, will report any further issues at **https://github.com/Codes4Fun/RBDOOM-3-BFG/issues**

**Comment by y2keeth** [comment]
"your update does not allow me to load saved games. The load starts then goes back to the main menu." old bug goes back to vanilla doom 3, certain changes and saved games are toast
