### ISSUE TITLE
Okay, I gave it some thought and figured it out.

### ISSUE THREAD

**Issue by jaymounes** [RobertBeckebans/RBDOOM-3-BFG#360]
Well, this project is the biggest dicktease ever for me now! WOWOOWOWOWO okay. I made one thread but I don't think I clearly enough communicated why none the 16 input schemes work.

Note than in Valve's examples, the touch pad is used as 4-button switch, a sort of variable D-pad, NOT an analog stick. You can put a lot more there like SPT's flyouts, but at it's core I think it's meant to be buttons.

**Please please PLEASE give the option to just move forward, left, right, and back.** Input needs to be consistent in VR. When you do something,t he same thing needs to happen every time. Not almost the same thing, the exact same thing.

I cannot move in a straight line by pointing the controller as intended. Why is that? It's because my thumb is 1" wide. The touchpad is only 1.75" in diameter. **As a result when my thumb feels centered the controls could interpret that anywhere in a range of up to %57 of the trackpad's input.** Worse, my thumb isn't stationary, nor is anyone else's and the minute rolling action of the thumb on the pad results in constant, minute deviations off the desired straight line...

I mean, if you were making a shitfaced drunk simulator, this would be flawless. The only time I walk both forward and sideways is when I'm wasted, and usually when I get to that point I'm hitting the ground right after. The amount of nausea we're talking about here is the hot sweat hold your breath remember to breath style gag-reflex inducing kick in the gut nausea. It's just a no-go.

It's frustrating because I played this game with a keyboard and WSAD would solve the problem here. I wonder if there hadn't been damn consoles if we'd be here on git literally vomiting over analog input. LOL, in a way it's kinda cosmically funny.

**Comment by jaymounes** [comment]
The other thing is, the same concept applies to a thumb rolling forward and back. If you're adding acceleration tot his game you're making a huge mistake. It's a basic rule of.... thumb.... that no acceleration at all works really well in VR. Snap to full speed stop the instant you release.

**Comment by jaymounes** [comment]
Okay, I'm an idiot. vr_strafing 0. I was being a huge dick! I have some interesting perspective on VR and the Vive specifically though so, hopefully this is worth reading.

Food for thought take it or leave it I'm de facto less smart than you but whatevs, there you go.

**Comment by jaymounes** [comment]
hmmmmm... very close but still unplayable. An accel curve is one thing but random accel and decel, random speed, and random cut-off when my finger hits the edge of the pad and it stops reading will make it unplayable.

Just lose the analog though...

**Comment by BielBdeLuna** [comment]
the hell are you talking about? :)

**Comment by jaymounes** [comment]
Read the comments instead of shitposting? It's real, valid constructive criticism. 

I just went through all 16 move mode options. None of them produce one move speed when you push the touch pad button. Sometimes you move fast, sometimes you move slow, sometimes you don't move at all, and it doesn't make sense, because there are two speeds: W and SHIFT + W.

**Comment by BielBdeLuna** [comment]
aw man it was a joke!

**Comment by jaymounes** [comment]
### I ## have some # personal problemsssss~!

LOL. Anyway here's what you do, just set walk and run speed to a speed almost at the game's run speed. It'll be interesting to see where jump challenges break though, but I think I'll be able to spot them. Mode 4-5 works decent for me.

SO that really just leaves the acceleration curve weirdness.

**Comment by DanielGibson** [comment]
As you're talking about VR and everything, I guess you're talking about Codes4Fun's fork of this project with VR enhancements?

The bugtracker of that project can be found at https://github.com/Codes4Fun/RBDOOM-3-BFG/issues ;-)

**Comment by jaymounes** [comment]
Double fooled myself. Thanks for at least explaining.
