### ISSUE TITLE
collision model errors

### ISSUE THREAD

**Issue by y2keeth** [RobertBeckebans/RBDOOM-3-BFG#363]
this is a stock model untouched.  error comes up for some custom models as well, but only occasionally.

Error: idMoveable 'moveable_base_brick_38': cannot load collision model moveable_base_brick_38

**Comment by BielBdeLuna** [comment]
I think that's an error on the level making side, it's not engine related I think

**Comment by y2keeth** [comment]
happens randomly with a custom models tho

**Comment by y2keeth** [comment]
stock maps

**Comment by y2keeth** [comment]
also does not happen in doom 3 enigine

**Comment by y2keeth** [comment]
I think this fixes the issue https://github.com/y2keeth/RBDOOM3BFG-HiDef-Mod/commit/fd43c97615dd24b8f21bb6a5c67a2c5d7d66a698

**Comment by BielBdeLuna** [comment]
you might have to test it yourself this one

**Comment by y2keeth** [comment]
I have, it on my mods page now so someone will tell me for sure

**Comment by y2keeth** [comment]
well this fixed the custom model issue, 

Error: idMoveable 'moveable_base_brick_38': cannot load collision model moveable_base_brick_38

hits on caverns 2 everytime, its a stock model thats what I dont get, thats works in doom 3 and bfg. stock map file, stock everything.

**Comment by BielBdeLuna** [comment]
the stock model might be poorly done or poorly placed in the map, is it game breaking?
in doom3 you can open the level editor and search for that entity

**Comment by y2keeth** [comment]
runs fine in doom 3

**Comment by BielBdeLuna** [comment]
but have you opened the level editor and searched for that entity? you can use the d3 editor and look into the d3bfg map

I don't get any error loading that map in BFG, but it's true that ID enhanced most of the maps (or sometimes cut off some of the maps) from Doom3 and D3XP, so even if it works in Doom3 it might not mean anything compared to D3BFG

**Comment by y2keeth** [comment]
check this out lol.  deleting the caverns2.map file it loads fine from the resource file.  put the extracted caverns2.map file in the game/maps folder and its back to crashing.   makes no sense.

**Comment by BielBdeLuna** [comment]
that's strange indeed, the map was extracted from the resources?

**Comment by y2keeth** [comment]
yep should be the same map extracted lol.

**Comment by y2keeth** [comment]
unless there is some other thing hiding in the resource file, does not make any sense.

**Comment by RobertBeckebans** [comment]
Can't reproduce.
