### ISSUE TITLE
Mouse gets stuck when moving too quickly

### ISSUE THREAD

**Issue by itaranto** [RobertBeckebans/RBDOOM-3-BFG#367]
If I suddenly turn or move the mouse too quickly the mouse gets stuck for a short period of time.

I can see from the logs:
`idUsercmdGenLocal::MouseMove: Ignoring ridiculous mouse delta.`

Another weird behavior I'm seeing is that the mouse speed is increased when entering into a game.

OS: openSUSE Leap 42.2
Compiled using both GCC 4.8.5 and GCC 6.2.1 and SDL 2.0.3

I'm using a high DPI mouse, a Razer "Abyssus", maybe this kind of mouse is the causing  the problem?

**Comment by itaranto** [comment]
I compiled again using SDL 1 instead SDL 2 and the mouse issue is gone.

Maybe that's why the compilation instructions for openSUSE have libSDL-devel by default.

**Comment by ensiform** [comment]
SDL2 uses raw mouse input by default, and should be preferred.

**Comment by itaranto** [comment]
Reviving the dead.... I'm using 2.0.8-lp150.1.1 (openSUSE Leap 15), it works great. I think you can close this now.
