### ISSUE TITLE
r_useShadowMapping draws a black square

### ISSUE THREAD

**Issue by BrendonChung** [RobertBeckebans/RBDOOM-3-BFG#369]
When I enable r_useShadowMapping, a large black square is rendered on the screen:
https://youtu.be/-dK7Ia6e66I

I did some research but was unable to find any other people who had a similar problem. Perhaps it is something specific to my system?

I'm using:
- The RBDOOM-3-BFG 1.1.0-preview3 release
- Windows 7
- Clean install of Steam version of Doom 3 BFG
- NVIDIA GeForce GTX Titan X

**Comment by BielBdeLuna** [comment]
have you copied the base folder from the source?

**Comment by RobertBeckebans** [comment]
It is a new Nvidia driver bug.

2017-05-22 19:44 GMT+02:00 Biel Bestué de Luna <notifications@github.com>:

**Comment by TheVoodoo** [comment]
If you roll back to GeForce v378.78, it's gone.
