### ISSUE TITLE
Doom Classic rendering artefacts

### ISSUE THREAD

**Issue by rigred** [RobertBeckebans/RBDOOM-3-BFG#373]
![image](https://user-images.githubusercontent.com/5716332/27996587-432e2552-64dd-11e7-87d1-618ab38f65b4.png)

When moving around blocks/lines like this smear across the screen.

Tested on Arch Linux (amdgpu Rx 580) Gcc 7 build.

**Comment by mmayfield1** [comment]
I have this issue also. Nvidia Optimus laptop. Happens both with intel graphics and with nvidia (bumblebee).

**Comment by slobberingant** [comment]
Same here. Arch linux, 4.12-amd-staging kernel, Mesa 17.1.8, RX460, r5 1600.

**Comment by hamishpaulwilson** [comment]
Just adding to the chorus. Same problem on Arch Linux with with a Radeon HD 6870 using the R600 Gallium3D drivers.

**Comment by jiri-one** [comment]
Same problem on Arch Linux, kernel 4.13.5, Mesa 17.2.2, Intel HD 4600 and just compiled RBDOOM-3-BFG.
![screenshot from 2017-10-13 16-56-05](https://user-images.githubusercontent.com/32774109/31552862-ebbe4912-b038-11e7-8ad2-35ddc8ffca1b.png)

**Comment by MadDeCoDeR** [comment]
Fixed it on [Classic RBDOOM3BFG](http://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG)

**Comment by rigred** [comment]
Which particular changes should I pull for that? 
I went through your commit log, but am not sure what's applicable since I don't just want everything you've changed.

**Comment by MadDeCoDeR** [comment]
Look for the r_segs.cpp file's history to see what changes you should pull.
 These changes are also including a fix for the tutti-fuity bug of Classic Doom games (that barely shown in vanilla maps)

**Comment by mmayfield1** [comment]
MadDeCoDeR, will these changes get pulled into the normal RBDOOM-3-BFG?

**Comment by MadDeCoDeR** [comment]
mmayfield1, Why is Classic-RBDOOM-3-BFG so bad? It has also full controller support (plug n' play anytime) for both windows and Linux and many other exciting new features.

**Comment by mmayfield1** [comment]
MadDeCoDeR, It isn't bad. From the little tests I've done so far it works well. I didn't know it existed until the response on this thread. I didn't know if it was somehow related to RobertBeckebans RBDOOM-3-BFG or it was a completely unrelated project. I take it by your response it is a whole separate project and your fixes won't be implemented in RobertBeckebans fork?

**Comment by MadDeCoDeR** [comment]
mmayfield1, Well kind of if you read a little above you will see that I already said were the fix is in my repository and why it can't be pulled. RobertBeckbans  and anyone else interested is free and welcome to copy the fix and apply it on their own ports and if they need any help I'm here to provide it.

**Comment by itaranto** [comment]
Why not directly casting to an int? That way, it will work on Linux 32-bit, Linux 64-bit, Windows 32-bit and Windows 64-bit.

**Comment by MadDeCoDeR** [comment]
Well when I first wrote that I was unsure how it will work on 32-bit Linux, 64bit/32-bit Windows. So I left the long cast on it just in case.

**Comment by RobertBeckebans** [comment]
> Why not directly casting to an int? That way, it will work on Linux 32-bit, Linux 64-bit, Windows 32-bit and Windows 64-bit.
That's the correct solution. The fix is in the master.
