### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Keith94** [RobertBeckebans/RBDOOM-3-BFG#385]
Running a GTX 680 and i5-3570K at 1080p results:

* my performance in the first level area is ~60-70 FPS only (with soft shadows on). It seems inconsistent and sometimes tanks into the ~30-40s for some reason.
* with soft shadows off the game runs at ~90-100 FPS fyi.
* in vanilla Doom 3 BFG the game easily runs at 250+ FPS (after removing the cap).

Any clue as to why the performance is degraded so much compared to vanilla?

**Comment by dukenukemx** [comment]
I have a laptop running Mint 18.2 with a AMD Radeon HD 6370M and I'm getting 5-7 fps.  The last time I ran Doom3 was on a Radeon 9500 Pro back in 2004 and that was more than enough to play Doom 3.  I did tests, like I tried Doom3 with whatever Mint came with, then I install Padoka PPA, which made no difference, and then I tried enabling DRI3, which again made no difference and finally I tried "R600_DEBUG=sbcl,hyperz,llvm,sisched,forcedma" with again no difference.

There was texture corruption that I can fix by minimizing and restoring Doom3.  Something must be severely wrong here.  I did just copy the files from my other PC which runs Doom3 just fine, so I don't know if that has any effect.  I'm sure if I run Doom3 via Wine it would run better on this machine.

**Comment by nbohr1more** [comment]
Did you disable HDR?

**Comment by dukenukemx** [comment]
Just tried with HDR off and I got 1 extra fps out of it.  Something far worse must be happening.

**Comment by y2keeth** [comment]
soft shadows are very tasking,  you want to get back to doom 3 fps use the stencil shadows
