### ISSUE TITLE
Change readme to address GOG release of the game

### ISSUE THREAD

**Issue by shmerl** [RobertBeckebans/RBDOOM-3-BFG#387]
GOG now offer DRM-free version, so it's not limited to Steam anymore.

**Comment by spannerman79** [comment]
https://www.gog.com/game/doom_3_bfg_edition

**Comment by BielBdeLuna** [comment]
Is there any difference between GOG's version and Steam's? it seems there is difference in the language options, are there more?

**Comment by shmerl** [comment]
I don't have the Steam version, so I can't compare. May be someone with Steam version can run a binary diff?

**Comment by chungy** [comment]
The language files are modified to say that multiplayer mode is not available (BFG depended on Steam Cloud features for such).

**Comment by BielBdeLuna** [comment]
no multiplayer?! damn

**Comment by shmerl** [comment]
Shouldn't it support LAN multiplayer? Using Steam for it is a wrong method anyway.

**Comment by BielBdeLuna** [comment]
it's strange it doesn't, it doesn't? in Linux without steam active I can create and play in a "quick match" which I assume it's a LAN game, isn't it?

**Comment by shmerl** [comment]
Not sure, I don't use Steam so I can't compare. But other older games from id work with LAN just fine, for example Return to Castle Wolfenstein.

**Comment by shmerl** [comment]
I just saw this comment on PCGaming Wiki:

> Despite the GOG.com version being single-player only. It is possible to play multiplayer by adding seta net_useplatformbackend 0 in default.cfg and use the console command connect in order to join the server.I

**Comment by joder666** [comment]
I can confirm it works with GOG game files, but, for some reason i don't get the game language defaulted to "Japanese".  Since there are no in-game options to change this i had to delete all language files inside "/base/strings" but the one i wanted to use.

Haven't had the chance to test if LAN works though.

**Comment by shmerl** [comment]
No need to delete game files, just set the language in .cfg file manually.

**Comment by joder666** [comment]
just saw that on pcgamingwiki
