### ISSUE TITLE
Build fails with gcc-7

### ISSUE THREAD

**Issue by shmerl** [RobertBeckebans/RBDOOM-3-BFG#388]
```
In file included from ../idlib/Lib.h:295:0,
                 from precompiled.h:48:
../idlib/StrStatic.h: In constructor ‘idStrStatic<_size_>::idStrStatic(bool)’:
../idlib/StrStatic.h:100:23: error: no matching function for call to ‘idStrStatic<_size_>::operator=(const bool&)’
   idStr::operator=( b );
                       ^
```

I suppose I need to force c++03? I generated files with cmake-eclipse-linux-profile.sh and when it's building, it's apparently using C++11.

**Comment by hollunder** [comment]
Hi shmerl, we seem to meet everywhere...

I think it's the same issue as reported here: https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/371

It's been a while since I've dealt with building C/C++ stuff, so if you find a build option that works, please let us know.

**Comment by shmerl** [comment]
Ah, that's indeed a dup, no need to keep this open then. I'll try the patch from @damiel.
