### ISSUE TITLE
Using Shadowmapping kills performance

### ISSUE THREAD

**Issue by LordKane1701** [RobertBeckebans/RBDOOM-3-BFG#395]
Hi, I have a older video card (a ATI Radeon HD 5770) and using soft shadows just murders my performance is there anything I can do about this?

**Comment by BielBdeLuna** [comment]
try r_shadowMapLodBias 4 to reduce the quality of the soft shadows

further than this I don't know any more commands to reduce the quality of the current implementation, the next solution I guess would be to add a lower quality shadowmap algorithm, maybe even disable the soft shadow mapping, it would look ugly but older cards would be able to play it.

**Comment by LordKane1701** [comment]
Will do that, thank you for the suggestion

**Comment by ROCKNROLLKID** [comment]
On my Nvidia 1070 and Ryzen 1700, my fps drops as low as 35fps in some areas with shadow mapping on. Using r_shadowMapLodBias 4 only improved my fps ~10. I guess it just needs more optimization.

**Comment by tuxutku** [comment]
My AMD RX 540 does drops 27~ frames sometimes

**Comment by brazzjazz** [comment]
I was having the same problem. I was puzzled at first because the GPU load was nowhere near 100%. How can this be, that I get 45-60 (but below 60) fps while being under 100% GPU load? Can single shaders / effects screw up the framerate like this without utilizing the GPU 100%? Is it because buggy shaders force the rest of the GPU to wait or something? Just trying to understand low framerates with <100% GPU load (given CPU is not 100%).

**Comment by Calinou** [comment]
@brazzjazz Maybe shadowmapping is constrained by the GPU memory bandwidth, which means the GPU core isn't used at its full potential.

**Comment by DanielGibson** [comment]
dhewm3 doesn't have shadowmaps but uses the old stencil shadows, that's why it's fast, but the shadows are also not "soft"

**Comment by kkuez** [comment]
This problem still persists in 2021. Is it really that no solution was found yet?
I'm not able to play this mod then unfortunately.

**Comment by Calinou** [comment]
> This problem still persists in 2021. Is it really that no solution was found yet?
I'm not able to play this mod then unfortunately.

Try entering `r_shadowMapLodBias 4` in the console to reduce the quality of the soft shadows.

**Comment by BielBdeLuna** [comment]
r_shadowmapsamples down to 2 or 4 for a less sampled bluring on the shadow maps, it will increase shadow map acne though.

**Comment by RobertBeckebans** [comment]
r_shadowMapLoadBias 2 or 4 is not really helpful. I measured this again on my current system in 1440p.

![rbdoom-3-bfg-20210106-163546-002](https://user-images.githubusercontent.com/1278614/103787440-ddd6c880-503d-11eb-93c3-70006645dc12.png)
![rbdoom-3-bfg-20210106-163559-003](https://user-images.githubusercontent.com/1278614/103787453-e16a4f80-503d-11eb-8d81-b47e14ccc892.png)

As you can see with com_showFPS 3 this is one of the heaviest performance penalty corners I can find in the game. About 8100 drawcalls and you only save 0.1 milliseconds by suffering a worse quality. I got a lot of feedback that Nvidia users who have no performance problems at all. I optimized the master branch last year on a RX 580 and I figured that the shadowmap resolution isn't really a problem with the performance. It's simply the poor AMD Windows OpenGL driver and that RBDoom does too many context switches for shadow mapping.

A state of the art performance improvement would be to use a shadowmapping atlas with octahedral projection as shown here:
http://hd-prg.com/tileBasedShadows.html

**Comment by Calinou** [comment]
@RobertBeckebans Would this be more useful?

> r_shadowmapsamples down to 2 or 4 for a less sampled bluring on the shadow maps, it will increase shadow map acne though.

**Comment by BielBdeLuna** [comment]
Another big improvement could be to make "rs_enable 3" or "r_screenfraction 50" a credible solution, all pixel shader effects related to the _currentrender don't understand a _currentrender image with changing resolution.
