### ISSUE TITLE
Add support for XDG base directory specification

### ISSUE THREAD

**Issue by shmerl** [RobertBeckebans/RBDOOM-3-BFG#400]
I made a merge request to support XDG base spec to avoid cluttering `$HOME`: https://github.com/RobertBeckebans/RBDOOM-3-BFG/pull/399

**Comment by shmerl** [comment]
@RobertBeckebans: Can you merge this please? It's a simple change.

**Comment by RobertBeckebans** [comment]
Even it is simple we need to tell the users that their existing savegames have moved.

**Comment by shmerl** [comment]
Yep, users will need to be aware of that. But I wouldn't worry about it much. If users will see their saves lost, they'll figure out something is going on, and either ask about it, or will find them themselves.

Putting it in release notes would be a good start.

**Comment by RobertBeckebans** [comment]
Ok this was merged.
