### ISSUE TITLE
Replace gibs for zombies with ragdolls

### ISSUE THREAD

**Issue by ROCKNROLLKID** [RobertBeckebans/RBDOOM-3-BFG#401]
I really never liked how you shoot a zombie once with a pistol and they just gib and disappear. Is there a way we can change that to just a normal ragdoll system?

**Comment by Keith94** [comment]
Check [Ungibbable mod for Doom 3 BFG Hi Def](http://www.moddb.com/mods/doom-3-bfg-hi-def/addons/ungibbable-mod-for-doom-3-bfg-hi-def)

**Comment by ROCKNROLLKID** [comment]
Thanks, I will use that and close this issue.
