### ISSUE TITLE
Graphical Issues

### ISSUE THREAD

**Issue by slobberingant** [RobertBeckebans/RBDOOM-3-BFG#402]
I have a few graphical issues when playing doom 3. The horizontal bar on top, the white 'shadows' around objects (more noticible when looking around) and the geodesic faces. Not sure how to better articulate my issues so have attached a screenshot. 
Have tried to play with the anti-aliasing settings in game menu with no luck. Changing the shadown settings doesn't help either.
Please let me know if you need any more information.
![screenshot](https://user-images.githubusercontent.com/15314729/30161590-8d4aab4a-9414-11e7-9a5a-0ca5656a8d62.png)

PC Specs include:
On Arch linux, 4.12-amd-staging kernel, Mesa 17.1.8, RX460, R5 1600 cpu.

Log data below.
[qconsole.txt](https://github.com/RobertBeckebans/RBDOOM-3-BFG/files/1284494/qconsole.txt)

**Comment by rigred** [comment]
Could you if possible give mesa 17.2 a try? The new version has just hit arch official repos.
So it should be as easy as `pacman -Syu`

**Comment by slobberingant** [comment]
Everything was fixed with mesa 17.2. Thanks for the tip.
