### ISSUE TITLE
Shadow mapping framerate killer and soft particles

### ISSUE THREAD

**Issue by DropsMJay** [RobertBeckebans/RBDOOM-3-BFG#405]
Shadow Mapping is a heavier function of this source port, literally kills the framerate on my pc. I was thinking:

With shadow mapping, all shadows are generated in real time, correct? Instead of generating everything in real time, why not create a command that bake the static shadows?

Is it possible to add soft particles?

Thanks

**Comment by BielBdeLuna** [comment]
it's possible, to add the soft particles, you can lower the quality of the shadows with their lod bias set to 4 and gain some fps, i think though the real killer here is the HDR not the shadows.

**Comment by y2keeth** [comment]
soft shadows and hdr are both killers, take it from a guy with a crap card lol
