### ISSUE TITLE
White ellipse when using Grabber

### ISSUE THREAD

**Issue by xerus71** [RobertBeckebans/RBDOOM-3-BFG#407]
When I use the grabber in Ressurection of Evil to get something a white ellipse appears in the center of the display.  I'm using SteamOS Brewmaster stable with nvidia drivers 381.22. Not using soft shadows or HDR. Same effect with HDR on. Soft shadows don't render correctly but I think it is the same with them on.

System info:
AMD 8370
16GB RAM
GTX660Ti w/ 2GB RAM

![2017-10-08-085439_1920x1080_scrot](https://user-images.githubusercontent.com/19847370/31316981-8f471e38-ac06-11e7-9290-335895818c5a.png)

**Comment by uzyfeo** [comment]
I got this issue reported on my fork as well, but with some extra details.

Seems like something is wrong with antialiasing, as this appears with no or MSAA set for the person.
With SMAA1x, apparently everything works as expected.

Maybe some weird driver bug?

**Comment by xerus71** [comment]
I tried it with SMAA1x & MSAA2x with no luck.  Same issue persists. Thanks for the info.

**Comment by TheVoodoo** [comment]
If you disable the HUD with cvar "g_showhud 0" does it disappear?

**Comment by RobertBeckebans** [comment]
Does ist change with r_useFilmicPostProcessEffects 0 ?

**Comment by xerus71** [comment]
"g_showhud 0" has no effect.  "r_useFilmicPostProcessEffects 0" resolves it. Thanks. The game looks slightly darker but nothing extreme. The white ellipse is gone and the objects warped (That's an intentional effect I hope)...
