### ISSUE TITLE
HDR black blots

### ISSUE THREAD

**Issue by lazycrypt** [RobertBeckebans/RBDOOM-3-BFG#411]
I've tried playing RBDOOM3BFG (version win10x64 vs2017, compiled from the coded retrieved from github today) and while the game works, HDR doesn't. Specifically, a number of areas on the screen where there should be bright shining light there are just persistent black blots that don't leave the screen until I exit into the main menu. If I turn HDR off the issue no longer persists.

Game settings: https://i.imgur.com/7es1MQ0.jpg
Example 1: https://i.imgur.com/kkkOlnD.jpg
Example 2: https://i.imgur.com/Bz4fSpe.jpg

I am using the latest Radeon drivers (17.12.2) if that matters at all.

**Comment by bryansee** [comment]
Me too. A number of areas on the screen started showing some black blots. Especially screens showing reflective materials such as glass etc.

Entering commands in console clears them, but when I turn off HDR, the issue no longer persists.

I've looked into the code of my currently active RBDOOM3BFG fork, and this black blot issue may be related to either the image or the framebuffers.

Any help appreciated.

**Comment by noabody** [comment]
`%USERPROFILE%\Saved Games\id Software\RBDOOM 3 BFG\base`
```
set r_useSSAO "0"
set r_useSSGI "0"
```

**Comment by lazycrypt** [comment]
Just tried that with a build from source and it did not work. In fact, changing the cfg file is useless because the game will revert back to set `r_useSSAO "0"` on launch. Same if I try to set `set r_useHDR "1"` to `"0"`, it will auto switch back to `"1"`. Setting the file to read-only or using `autoexec.cfg` didn't do anything.

It's just busted.

**Comment by noabody** [comment]
Same here.  I updated my comment.  Seems like this has to be entered in the console as `r_useSSAO 0` as the defaults for the other options are already as shown except `r_useSSAO 1`.

**Comment by RobertBeckebans** [comment]
I cannot reproduce this anymore with the latest master version 1.2.0 and the AMD Radeon driver 19.5.2.
