### ISSUE TITLE
Black Screen with SRGB

### ISSUE THREAD

**Issue by doomhg** [RobertBeckebans/RBDOOM-3-BFG#412]
I can't get SRGB to work. Every time i enable it all i get is a black screen with HUD.
Menus work but opening cut scene and level are black just the HUD shows.

Using the latest preview build.

Appreciate any help

Specs:
OS Windows 10 pro 64 bit
MSI GTX970 
Driver 390.65
RAM 16GB
CPU i7-6700K

 
![rbdoom3bfg exe screenshot 2](https://user-images.githubusercontent.com/35444871/34931584-9d5988f6-fa23-11e7-8a4a-ed69ac5c8686.jpg)

**Comment by RobertBeckebans** [comment]
sRGB is not supported and conflicts with the HDR implementation.
