### ISSUE TITLE
Compilation failure due to -Werror=format-overflow with g++ 8.1.0

### ISSUE THREAD

**Issue by vloup** [RobertBeckebans/RBDOOM-3-BFG#419]
Hey,

I was doing some spring cleaning in the applications directory that automatically compiles code and saw yours did not compile.

```
/home/vloup/applications/doom3/RBDOOM-3-BFG/doomclassic/doom/p_setup.cpp: In function 'void P_SetupLevel(int, int, int, skill_t)':
/home/vloup/applications/doom3/RBDOOM-3-BFG/doomclassic/doom/p_setup.cpp:661:22: error: '%i' directive writing between 2 and 10 bytes into a region of size 6 [-Werror=format-overflow=]
    sprintf (lumpname,"map%i", map);
                      ^~~~~~~
/home/vloup/applications/doom3/RBDOOM-3-BFG/doomclassic/doom/p_setup.cpp:661:22: note: directive argument in the range [10, 2147483647]
/home/vloup/applications/doom3/RBDOOM-3-BFG/doomclassic/doom/p_setup.cpp:661:12: note: 'sprintf' output between 6 and 14 bytes into a destination of size 9
    sprintf (lumpname,"map%i", map);
    ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/home/vloup/applications/doom3/RBDOOM-3-BFG/doomclassic/doom/p_setup.cpp:659:22: error: '%i' directive writing between 1 and 11 bytes into a region of size 5 [-Werror=format-overflow=]
    sprintf (lumpname,"map0%i", map);
                      ^~~~~~~~
/home/vloup/applications/doom3/RBDOOM-3-BFG/doomclassic/doom/p_setup.cpp:659:22: note: directive argument in the range [-2147483648, 9]
/home/vloup/applications/doom3/RBDOOM-3-BFG/doomclassic/doom/p_setup.cpp:659:12: note: 'sprintf' output between 6 and 16 bytes into a destination of size 9
    sprintf (lumpname,"map0%i", map);
    ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
make[2]: *** [CMakeFiles/RBDoom3BFG.dir/build.make:3898: CMakeFiles/RBDoom3BFG.dir/home/vloup/applications/doom3/RBDOOM-3-BFG/doomclassic/doom/p_setup.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:69: CMakeFiles/RBDoom3BFG.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

Turns out that g++ is rather clever and infers the `map` value of this code over the full integer range, indeed bringing possible problems if `map` is negative or bigger than 5 digits in decimal representation:
```
                if (map<10)
                        sprintf (lumpname,"map0%i", map);
                else
                        sprintf (lumpname,"map%i", map);
```

Possible fixes:
1. Replace `map` with `map % 100` and force a 2 digit representation with `sprintf`'s format.
2. Actively check for `map` bounds (`map` >= 0, or convert to unsigned int and `map` < 100) and output an error otherwise.
3. Tweak the `CMakeLists.txt` file to exclude this error.
4. Increase `lumpname` array size so that no problems occur.

I let you pick what fits the best, that's why I didn't do any pull request.

Have a nice sunday.

**Comment by tysegall** [comment]
Wanted to report that I'm running into this issue with gcc/g++ 8.2.0, output below.

[ 61%] Building CXX object CMakeFiles/RBDoom3BFG.dir/home/wls/git/RBDOOM-3-BFG/doomclassic/doom/p_saveg.cpp.o
[ 61%] Building CXX object CMakeFiles/RBDoom3BFG.dir/home/wls/git/RBDOOM-3-BFG/doomclassic/doom/p_setup.cpp.o
/home/wls/git/RBDOOM-3-BFG/doomclassic/doom/p_setup.cpp: In function ‘void P_SetupLevel(int, int, int, skill_t)’:
/home/wls/git/RBDOOM-3-BFG/doomclassic/doom/p_setup.cpp:661:22: error: ‘%i’ directive writing between 2 and 10 bytes into a region of size 6 [-Werror=format-overflow=]
    sprintf (lumpname,"map%i", map);
                      ^~~~~~~
/home/wls/git/RBDOOM-3-BFG/doomclassic/doom/p_setup.cpp:661:22: note: directive argument in the range [10, 2147483647]
/home/wls/git/RBDOOM-3-BFG/doomclassic/doom/p_setup.cpp:661:12: note: ‘sprintf’ output between 6 and 14 bytes into a destination of size 9
    sprintf (lumpname,"map%i", map);
    ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/home/wls/git/RBDOOM-3-BFG/doomclassic/doom/p_setup.cpp:659:22: error: ‘%i’ directive writing between 1 and 11 bytes into a region of size 5 [-Werror=format-overflow=]
    sprintf (lumpname,"map0%i", map);
                      ^~~~~~~~
/home/wls/git/RBDOOM-3-BFG/doomclassic/doom/p_setup.cpp:659:22: note: directive argument in the range [-2147483648, 9]
/home/wls/git/RBDOOM-3-BFG/doomclassic/doom/p_setup.cpp:659:12: note: ‘sprintf’ output between 6 and 16 bytes into a destination of size 9
    sprintf (lumpname,"map0%i", map);
    ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
make[2]: *** [CMakeFiles/RBDoom3BFG.dir/build.make:3898: CMakeFiles/RBDoom3BFG.dir/home/wls/git/RBDOOM-3-BFG/doomclassic/doom/p_setup.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:74: CMakeFiles/RBDoom3BFG.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by in0ni** [comment]
@vloup -- I would like to apply one of your solutions, but unfamiliar with the details. Would you mind suggesting one approach which you feel is the best, or perhaps simplest, solution? Or if you have a patch laying around to apply, that would be great!

Appreciate the help in advance.

**Comment by vloup** [comment]
Hey @in0ni,

I've purposely not given any clear one-fits-all diff since, as I mentioned, there is more than one way to fix it, and all of them are worth their pro and cons.

For my own opinion (which is worth nothing), I'd prefer to keep the error activated in the compiler and fix the code instead. This error is legitimate to my eyes, and should be kept around.

So here's solution 1 I proposed as a diff, I'm not too happy of it since it limits the number of loadable levels to 100. If 100 is not enough, you can increase it up to 10000:
```diff --git a/doomclassic/doom/p_setup.cpp b/doomclassic/doom/p_setup.cpp
index d0aceff..bff2700 100644
--- a/doomclassic/doom/p_setup.cpp
+++ b/doomclassic/doom/p_setup.cpp
@@ -656,9 +656,9 @@ P_SetupLevel
        if ( ::g->gamemode == commercial)
        {
                if (map<10)
-                       sprintf (lumpname,"map0%i", map);
+                       sprintf (lumpname,"map0%i", map % 100);
                else
-                       sprintf (lumpname,"map%i", map);
+                       sprintf (lumpname,"map%i", map % 100);
        }
        else
        {
```

You could have done it yourself, didn't you? :-)

**Comment by in0ni** [comment]
Thanks @vloup! I was not clear what "force a 2 digit representation with sprintf's format" meant :), but after this minor change I was able to finally compile!

**Comment by tuxutku** [comment]
I have the same error too
