### ISSUE TITLE
Hit/damage markers show a white background

### ISSUE THREAD

**Issue by itaranto** [RobertBeckebans/RBDOOM-3-BFG#422]
![screenshot_20180904_210207](https://user-images.githubusercontent.com/11463919/45063881-f2c67a00-b086-11e8-98d9-bd002d382e27.png)
### Environment
RBDOOM version: a05b8cdf02142c247db16173883565e0e1a47cc6
OS: openSUSE Leap 15.0
Video card: NVIDIA GTX 650
Driver version: NVIDIA 390.87

**Comment by RobertBeckebans** [comment]
Should be fixed in the latest master.
