### ISSUE TITLE
stutter when walking or running

### ISSUE THREAD

**Issue by tomtomujf** [RobertBeckebans/RBDOOM-3-BFG#426]
For some reason while walking the character movement  stutters as if the character was tripping on something. At first when the move forward key is pressed the character walks normally but about 1 second later the movement stutters. While this occurs you can hear the characters feet stumbling on something. I compiled the aur  package rbdoom3-bfg-git with gcc 8.2.1.
I have a RX580  with the latest mesa drivers.

**Comment by DanielGibson** [comment]
try removing all occurences of `-ffast-math` in CMakeLists.txt
that compilerflag screws things up and seems to break more things in every new GCC release

**Comment by tomtomujf** [comment]
unfortunately it has not fixed the issue. The stuttering seems to be different now. The time between each stutter is longer but it is still unplayable.

**Comment by RobertBeckebans** [comment]
I experienced the same on Kubuntu 18.04. It was gone with 19.04. You can also try the latest master and see if it still happens.
