### ISSUE TITLE
Update OpenGL backend to use modern OpenGL Direct State Access

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#427]
https://github.com/Fendroidus/Guide-to-Modern-OpenGL-Functions

**Comment by BielBdeLuna** [comment]
interesting, what sort of numbers on the percentage of improvement could we be talking about?

**Comment by BielBdeLuna** [comment]
in Brink they used Textures atlases for all the textures in the level, I guess this would improve on the VRAM usage. I wonder if it could be implemented a way to get a list of all the initial texture files used in every material on the map, and then change the repeated texture usages for references, and then create an atlas with all the unique textures and have the references reference a unique texture in the atlas., do this as a map load process.
