### ISSUE TITLE
add Depth of Field

### ISSUE THREAD

**Issue by FireCulex** [RobertBeckebans/RBDOOM-3-BFG#428]
![image](https://user-images.githubusercontent.com/9983630/51788167-c7285700-212f-11e9-9ea2-9a385ae5a64d.png)

Looks amazing in Doom 4. Any chance for something similar in Doom 3?

**Comment by spannerman79** [comment]
dupe https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/295

**Comment by RinMaru** [comment]
this would be nice

**Comment by RobertBeckebans** [comment]
Won't happen
