### ISSUE TITLE
Any chance we could get more recent snapshots for Windows?

### ISSUE THREAD

**Issue by wodim** [RobertBeckebans/RBDOOM-3-BFG#430]

**Comment by spannerman79** [comment]
You could compile yourself, follow https://github.com/RobertBeckebans/RBDOOM-3-BFG/blob/master/README.txt#L137

**Comment by wodim** [comment]
Yes, I know I can compile it myself.

**Comment by RobertBeckebans** [comment]
This this: https://github.com/RobertBeckebans/RBDOOM-3-BFG/releases/tag/1.2.0-preview1
