### ISSUE TITLE
Missing OpenAL 64-bit library

### ISSUE THREAD

**Issue by lazycrypt** [RobertBeckebans/RBDOOM-3-BFG#431]
When compiling the 64bit build of the game with the option to use OpenAL instead of xaudio the build fails because it can not locate the 64-bit openal32 library. In the project files it's set to look for the openal32.lib file in the `RBDOOM-3-BFG\neo\libs\openal-soft\win64\` which does not exist. Building a 64-bit version of OpenAL from [source](https://github.com/kcat/openal-soft) and placing the lib in the specified folder fixes the problem.

**Comment by RobertBeckebans** [comment]
This is fixed in https://github.com/RobertBeckebans/RBDOOM-3-BFG/commit/d03c4cc398181dce1a563128361d97118ea28f37 and will be in the next update scheduled for mid summer.
