### ISSUE TITLE
Texture Pack Support?

### ISSUE THREAD

**Issue by RinMaru** [RobertBeckebans/RBDOOM-3-BFG#434]
Ive messed around with a few texture packs mainly the Hi Def Texture Mod and once everything is extracted its a pretty big file size is it possible to support packed files like the OG Doom 3 had "PK4"

**Comment by lmills87** [comment]
I'm also trying to figure out how to get texture packs to work like Wulfen & Monoxead's texture packs. Interested if this is possible, and/or if there are any recommendations for texture packs for usage with this source port..

**Comment by RobertBeckebans** [comment]
https://www.moddb.com/mods/doom-3-bfg-ultimate

Doom 3 BFG Ultimate HD is a good example how to make a mod with RBDOOM-3-BFG. You simply extract it into a folder of your current DOOM-3-BFG installation. There won't be support for PK4 files.

**Comment by XASOXA** [comment]
![doom](https://user-images.githubusercontent.com/65764775/83677472-83274b00-a5dc-11ea-846b-9cc1287d9a60.png)


Looks good with this Mod! 

Question : Its possible to make the mirror reflection on the office windows like on the doom 3 alpha leak from 2002 

see on 7:20

https://www.youtube.com/watch?v=ic1-km8MwWE&list=PLnVnWr4MqNWfkvoK7YmkTxrf2RCE6wCpD&index=2

**Comment by BielBdeLuna** [comment]
not in this window in particular because it curves, 2002 Alpha used planar reflections at low res for that planar window (in fact only for that window in the alpha ), in order to make planar reflections you can use the material system to enable planar reflections, and then use that material on that surface.

**Comment by BielBdeLuna** [comment]
> ![doom](https://user-images.githubusercontent.com/65764775/83677472-83274b00-a5dc-11ea-846b-9cc1287d9a60.png)
> 
> Looks good with this Mod!
> 
> Question : Its possible to make the mirror reflection on the office windows like on the doom 3 alpha leak from 2002
> 
> see on 7:20
> 
> https://www.youtube.com/watch?v=ic1-km8MwWE&list=PLnVnWr4MqNWfkvoK7YmkTxrf2RCE6wCpD&index=2



not in this window in particular because it curves, 2002 Alpha used planar reflections at low res for that planar window (in fact only for that window in the alpha ), in order to make planar reflections you can use the material system to enable planar reflections, and then use that material on that surface.

**Comment by XASOXA** [comment]
> 
> 
> > ![doom](https://user-images.githubusercontent.com/65764775/83677472-83274b00-a5dc-11ea-846b-9cc1287d9a60.png)
> > Looks good with this Mod!
> > Question : Its possible to make the mirror reflection on the office windows like on the doom 3 alpha leak from 2002
> > see on 7:20
> > https://www.youtube.com/watch?v=ic1-km8MwWE&list=PLnVnWr4MqNWfkvoK7YmkTxrf2RCE6wCpD&index=2
> 
> not in this window in particular because it curves, 2002 Alpha used planar reflections at low res for that planar window (in fact only for that window in the alpha ), in order to make planar reflections you can use the material system to enable planar reflections, and then use that material on that surface.

Aha thanks good to know, i am noob in this direction.

**Comment by BielBdeLuna** [comment]
For effects like this you would need SSR or raytraced reflections
