### ISSUE TITLE
Startup error - failed to create OpenGL 4.4 context on Intel HD Graphics 4600

### ISSUE THREAD

**Issue by r-a-sattarov** [RobertBeckebans/RBDOOM-3-BFG#440]
When I start the game (RBDOOM-3-BFG version 1.2.0), I get an error related to the inability to initialize the video system:
      Initializing OpenGL driver
      ...creating GL context: failed to create OpenGL 4.4 context
      failed to create OpenGL 5.0 context
      unknown error: 0x5
      failed
      Shutting down OpenGL subsystem

The game is launched in Windows 8.1 (x64) with an Intel Core i7-4770K processor (with an integrated Intel HD Graphics 4600).

On the old version 1.1.0 of the game, such an error did not occur.

I attach the game launch log.
[startupRB_v1.2.0_error_intel-hd-4600.log](https://github.com/RobertBeckebans/RBDOOM-3-BFG/files/3775142/startupRB_v1.2.0_error_intel-hd-4600.log)

**Comment by Calinou** [comment]
According to [this table](https://en.wikipedia.org/wiki/Intel_Graphics_Technology#Capabilities), Intel Haswell IGPs only support OpenGL 4.3 on Windows.

**Comment by r-a-sattarov** [comment]
Yes I know. But the previous version of the game (1.1.0) was launched without problems on this system.

Perhaps this is due to changes in the game codes that this commit "Try to run with OpenGL 4.5 core profile by default on Windows" caused.
- https://github.com/RobertBeckebans/RBDOOM-3-BFG/commit/8cdc4aa99c27293900da116f0260cf8d3d2a99f5

As I understand it, OpenGL 3.2 was used before (in version 1.1.0) at the start of the game.

**Comment by RobertBeckebans** [comment]
I changed the GLSL output along with the Vulkan GLSL output. They are both different but the OpenGL GLSL version is not 1.50 anymore but 4.50.
I'm not sure if I can revert it so easily and change it to OpenGL 4.3. RBDOOM-3-BFG requires an OpenGL core profile of OpenGL 4.5 and changing it requires more testing.

**Comment by Leopard1907** [comment]
Afaik Windows driver lacks it , while Haswell with Mesa has at least ogl 4.5 and partial ( kinda broken ) Vulkan support on Mesa too.

**Comment by r-a-sattarov** [comment]
Current error message on Windows 8.1 (x64) with an Intel Core i7-4770K processor (with an integrated Intel HD Graphics 4600).

`Initializing OpenGL driver`
`... creating GL context: failed to create OpenGL 4.5 context`
`failed to create OpenGL 4.3 context`
`unknown error: 0x5`
`failed`
