### ISSUE TITLE
error: invalid argument '-std=c++11' not allowed with 'C'

### ISSUE THREAD

**Issue by ericwomer** [RobertBeckebans/RBDOOM-3-BFG#444]
Building on XUbuntu 19.10 with clang 9 getting this message first when running cmake, and then with compilation, it fails when compiling png library. 

EDIT!
This is on master, sorry I forgot to mention it.

```
[1/496] Building C object CMakeFiles/RBDoom3BFG.dir/libs/zlib/trees.c.o
FAILED: CMakeFiles/RBDoom3BFG.dir/libs/zlib/trees.c.o 
/usr/bin/cc -DGLEW_STATIC -DUSE_BINKDEC -DUSE_DOOMCLASSIC -DUSE_EXCEPTIONS -DUSE_INTRINSICS -DUSE_OPENAL -D__DOOM__ -I/home/rake/src/Engines/RBDOOM-3-BFG/neo/libs/zlib -I/home/rake/src/Engines/RBDOOM-3-BFG/neo/libs/png -I/home/rake/src/Engines/RBDOOM-3-BFG/neo/libs/jpeg-6 -I/home/rake/src/Engines/RBDOOM-3-BFG/neo/libs/glew/include -I/home/rake/src/Engines/RBDOOM-3-BFG/neo/libs/rapidjson/include -I/home/rake/src/Engines/RBDOOM-3-BFG/neo/libs/libbinkdec/include -I/home/rake/src/Engines/RBDOOM-3-BFG/neo/. -I/home/rake/src/Engines/RBDOOM-3-BFG/neo/idlib -I/usr/include/SDL2 -g -D_DEBUG -O0 -ggdb   -pipe -Werror=format-security -Werror=format -std=c++11 -mmmx -msse -msse2 -Wno-pragmas -Wno-unused-variable -Wno-switch -Wno-unused-value -Winvalid-pch -Wno-multichar -Wno-local-type-template-args -Wno-unknown-warning-option -Wno-inline-new-delete -Wno-switch-enum -fno-strict-aliasing -MD -MT CMakeFiles/RBDoom3BFG.dir/libs/zlib/trees.c.o -MF CMakeFiles/RBDoom3BFG.dir/libs/zlib/trees.c.o.d -o CMakeFiles/RBDoom3BFG.dir/libs/zlib/trees.c.o   -c /home/rake/src/Engines/RBDOOM-3-BFG/neo/libs/zlib/trees.c
error: invalid argument '-std=c++11' not allowed with 'C'
ninja: build stopped: subcommand failed.

```

**Comment by salamanderrake** [comment]
This is with pre-compiled headers disabled, because with precompiled headers enabled it does something weird with the ast files.

**Comment by ericwomer** [comment]
Closing as I know what the issue is and have a fix.

**Comment by BielBdeLuna** [comment]
what is the fix?

**Comment by ericwomer** [comment]
You need to pass -std=c++11 (however RB eventually sets it up) to the build process of the precompiled headers. I have this commit [here](https://github.com/ericwomer/RBDOOM-3-BFG/commit/eeceaba2610ecb9d5c14acb4143e3e08888b820f), part of pr I made, that uses cmakes implementation to set the c++ standard. CMAKE_CXX_EXTENSIONS is set to off so cmake doesn't use gnu++11 and I can use CMAKE_CXX_STANDARD as a variable that is set for cmake, that can also be used to set the standard during the the precompiled header build. I ended up doing this way because add_definition and add_compile_options would cause clang to complain about passing -std=c++11 to C files is problematic and cause cmake to fail configuration.
