### ISSUE TITLE
VR version

### ISSUE THREAD

**Issue by MemeVR** [RobertBeckebans/RBDOOM-3-BFG#449]
Hi,

Any plans to make a VR version of this ? The updated graphics will sure to be very cool in VR.

Thanks

**Comment by johnr14** [comment]
yes, as work on Fully possed seems to be on hold. Merging back into RBDoom3 woul be nice.

If you could add VR support on the .plan, it would be great! 

Actually, with Boneworks out, we have lots of ideas how to improve the gameplay and Alyx will soon show gameplay footage.

**Comment by RobertBeckebans** [comment]
Vulkan seems to allow multiview rendering for VR without rendering the scene twice. It might be an option for the DOOM-3-BFG VR guys however I can't help with the VR stuff really. I get motion sick too quickly.
