### ISSUE TITLE
Questions about installation

### ISSUE THREAD

**Issue by lmills87** [RobertBeckebans/RBDOOM-3-BFG#457]
I am a Windows user. Should I be using the precompiled binaries or the .zip?

Also, I noticed something about FPmpeg DLLs - what are those and do I need them?

I am interested in being able to turn on/off options such as SSAO, HDR, and the like - where do these parameters exist? I don't see them in default.cfg (that's if I'm using the .zip - if I'm using the precompiled binary then I really don't know where to look).

![5JO6HOH](https://user-images.githubusercontent.com/31397270/75636920-85969500-5be8-11ea-935b-d5720f306d99.png)

Is this how my installation folder should look? I followed instructions and copied the base folder from the Steam installed BFG folder to my new folder. The game seems to launch, however, I am unsure if I need the FFmpeg DLLs as mentioned above, and also unsure how to manipulate the various features.

![jgwgWCW](https://user-images.githubusercontent.com/31397270/75636967-cc848a80-5be8-11ea-9417-578686f7fdf1.png)

Furthermore is there any benefit to using the .zip instead of the precompiled binary?

**Comment by Calinou** [comment]
> I am interested in being able to turn on/off options such as SSAO, HDR, and the like - where do these parameters exist? I don't see them in default.cfg (that's if I'm using the .zip - if I'm using the precompiled binary then I really don't know where to look).

The best way to tweak them is to start the game, open the console by pressing <kbd>Tilde</kbd> or <kbd>Shift + Escape</kbd> then enter the cvars that control those settings (such as `r_useSSAO 0|1` if I'm not mistaken). You can use the `cvarlist` command to find cvars based on their name.

> The game seems to launch, however, I am unsure if I need the FFmpeg DLLs as mentioned above, and also unsure how to manipulate the various features.

I think you need FFmpeg DLLs if you want to be able to see in-game movies, but I'm not sure.

> Furthermore is there any benefit to using the .zip instead of the precompiled binary?

No, unless you're a developer and intend to work on RBDOOM-3-BFG's source code.

**Comment by lmills87** [comment]
And if I want to start the game with certain cvars different from their default value, do I have to pass them as parameters when launching the game (such as through a shortcut or batch file), or is there a cvar.cfg list somewhere I can edit?

**Comment by Calinou** [comment]
@lmills87 I think you can create an `autoexec.cfg` file that contains the cvars to set in your user data folder. On Windows, the user data folder might be in `%USERPROFILE%\Documents\My Games` or `%USERPROFILE%\Saved Games` (I don't remember).

**Comment by lmills87** [comment]
Another question - I was playing around in the menu and enabled 3d mode; now my screen is black and I can't figure out how to disable it lol. Where is this setting stored at so that I can turn it off?
