### ISSUE TITLE
HDR Flickering

### ISSUE THREAD

**Issue by lmills87** [RobertBeckebans/RBDOOM-3-BFG#458]
I seem to be experiencing an issue where the lights flicker when I move my character, as seen here:

https://www.youtube.com/watch?v=E9qZm8GHwXU

Disabling HDR autoexposure seems to fix the problem (or disabling HDR altogether). Any ideas?

Edit: I've tried various combinations of settings, but regardless of what I try the flickering persists when HDR autoexposure is enabled.

**Comment by BielBdeLuna** [comment]
I think this has to be about the HDR being frame perfect?

**Comment by lmills87** [comment]
> I think this has to be about the HDR being frame perfect?

Can you elaborate? Is there a setting I can change to fix this?

**Comment by RobertBeckebans** [comment]
It might be caused by r_hdrAutoExposure which tries to adapt the tone mapping to the average scene luminance. The implementation uses glReadPixels and is not optimal.

**Comment by lmills87** [comment]
That does seem to be the case as setting r_hdrautoexposure to 0 fixes the problem. But then, the scene seems a bit too bright at that point. Can I adjust the HDR to make it a bit darker?

**Comment by HoJo215** [comment]
I'm actually having the same problem but not as bad as Imills87's video. Would it have to do with Intel integrated graphics? I'm running from a NUC 8i7beh with Ubuntu 18.04.4 installed.

**Comment by BielBdeLuna** [comment]
as I understand it HDR auto-exposure tries to get the best median exposure for every frame, one might not want a perfect median exposure for every frame, but an evolving one between frames. for this the auto-exposure code should gain complexity in the part that determines what exposure should it have, in order to maintain a pleasurable experience.

**Comment by RobertBeckebans** [comment]
Auto exposure will be disabled in the upcoming update.
