### ISSUE TITLE
How do I compile with XCB instead of XLIB (Vulkan)?

### ISSUE THREAD

**Issue by 10010101001** [RobertBeckebans/RBDOOM-3-BFG#460]
I'm unable to run the game because I don't have VK_KHR_xlib_surface. How can I compile with XCB instead?

**Comment by spannerman79** [comment]
Did you/have you got Vulkan v 1.0.136+ installed? https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html

**Comment by 10010101001** [comment]
Yes, I have Vulkan 1.2.131
