### ISSUE TITLE
Linux Xbox Controller issues

### ISSUE THREAD

**Issue by FireCulex** [RobertBeckebans/RBDOOM-3-BFG#462]
The only time it recognizes the controller is when the controller is activated and when the game is launched.

- If the controller turns off during the game due to idling or low battery, game must be restarted
- If I activate the controller after I've launched the game, the game must be restarted

**Comment by Calinou** [comment]
I suppose this is because the game doesn't support controller hotplugging. Supporting it usually requires integrating libudev into the engine.
