### ISSUE TITLE
Vulkan: is deviceFeatures.depthBounds required?

### ISSUE THREAD

**Issue by cdotstout** [RobertBeckebans/RBDOOM-3-BFG#464]
It's not supported on Intel Gen GPUs.
Disabling it, I can start the game and move around the first level a bit.

Thanks for merging Vulkan!

**Comment by cdotstout** [comment]
Not supported on Intel prior to gen12 looks like:
https://gitlab.freedesktop.org/mesa/mesa/-/blob/master/src/intel/vulkan/anv_device.c#L915

**Comment by RobertBeckebans** [comment]
The depth bounds test is only required for the oldschool stencil shadows.
It won't be required for shadow mapping which isn't completed yet.
