### ISSUE TITLE
Running very slow

### ISSUE THREAD

**Issue by fransorius** [RobertBeckebans/RBDOOM-3-BFG#468]
I just installed the game but everything runs very slow. If I try to play doom 3 it just keeps loading (I don't know if would ever start) and if I play doom 1 and 2 it runs so slow that it's unplayable.

CPU: 2x AMD Opteron 4284 (8 core) 
GPU: GeForce 780ti (with nouveau drivers)
Memory: 8GB

OS: Debian Buster
Kernel: 4.19.0-8-amd64

**Comment by Calinou** [comment]
> GPU: GeForce 780ti (with nouveau drivers)

That's probably where the issue is coming from...

Novueau drivers can provide reclocking for Kepler GPUs, but you need to enable it manually. If you haven't followed any specific steps, then your GPU and VRAM are running at their boot clocks while the game is running.

**Comment by fransorius** [comment]
Thanks for your reply.

I did enable reclocking. Even if I have it in the highest pstate the result is the same. r_shadowMapLodBias doesn't do anything either.

I know NVIDIA drivers are faster but I want to use free drivers.

**Comment by BielBdeLuna** [comment]
you might need r_useOpenGL32 1 or 2 (i don't remember exactly) in order to use core profile of OGL

**Comment by fransorius** [comment]
Thanks, but also no change with r_useOpenGL32.

**Comment by RobertBeckebans** [comment]
r_useOpnGL32 is gone. It is r_useOpenGL45 now with the default value 2.
So the engine will try by default to run OpenGL in a core profile faster which is supposed to be a bit faster in any driver.
