### ISSUE TITLE
State error?

### ISSUE THREAD

**Issue by SEAGitUser** [RobertBeckebans/RBDOOM-3-BFG#477]
https://github.com/RobertBeckebans/RBDOOM-3-BFG/blob/7eddea53f574da860fa36909fe06ad5b37ea2031/neo/renderer/RenderBackend.cpp#L3724

I think this should be:
surfGLState |= GLS_POLYGON_OFFSET;

**Comment by RobertBeckebans** [comment]
Thanks for pointing this out. I think you are right but I need to investigate it a bit more. It might be a bug that also exists in vkDOOM3. I think MF_POLYGONOFFSET is also broken in the original D3 BFG code and only the private polygon offset for the individual shader stages were supported.
