### ISSUE TITLE
pbr2 branch - compile error

### ISSUE THREAD

**Issue by BielBdeLuna** [RobertBeckebans/RBDOOM-3-BFG#481]
I got the following error:
```
[ 98%] Building CXX object CMakeFiles/RBDoom3BFG.dir/renderer/Vulkan/RenderBackend_VK.cpp.o
/home/biel/code/doom3/RBDOOM-3-BFG/neo/renderer/Vulkan/RenderBackend_VK.cpp: In function ‘const char* VK_ErrorToString(VkResult)’:
/home/biel/code/doom3/RBDOOM-3-BFG/neo/renderer/Vulkan/RenderBackend_VK.cpp:124:24: error: ‘VK_RESULT_BEGIN_RANGE’ was not declared in this scope
  124 |    ID_VK_ERROR_STRING( VK_RESULT_BEGIN_RANGE );
      |                        ^~~~~~~~~~~~~~~~~~~~~
/home/biel/code/doom3/RBDOOM-3-BFG/neo/renderer/Vulkan/RenderBackend_VK.cpp:89:58: note: in definition of macro ‘ID_VK_ERROR_STRING’
   89 | #define ID_VK_ERROR_STRING( x ) case static_cast< int >( x ): return #x
      |                                                          ^
/home/biel/code/doom3/RBDOOM-3-BFG/neo/renderer/Vulkan/RenderBackend_VK.cpp:125:24: error: ‘VK_RESULT_RANGE_SIZE’ was not declared in this scope
  125 |    ID_VK_ERROR_STRING( VK_RESULT_RANGE_SIZE );
      |                        ^~~~~~~~~~~~~~~~~~~~
/home/biel/code/doom3/RBDOOM-3-BFG/neo/renderer/Vulkan/RenderBackend_VK.cpp:89:58: note: in definition of macro ‘ID_VK_ERROR_STRING’
   89 | #define ID_VK_ERROR_STRING( x ) case static_cast< int >( x ): return #x
      |                                                          ^
make[2]: *** [CMakeFiles/RBDoom3BFG.dir/build.make:6849: CMakeFiles/RBDoom3BFG.dir/renderer/Vulkan/RenderBackend_VK.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:278: CMakeFiles/RBDoom3BFG.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
any idea how to solve it?

**Comment by RobertBeckebans** [comment]
It looks like some changes in the Vulkan SDK break stuff. I also have these problems with the latest Vulkan SDK and further problems with compiling and linking and running glslang on Windows.

**Comment by BielBdeLuna** [comment]
how can I help in order to solve this? it is an Enum that has changed this value, maybe we can stub for the moment this error macro?

**Comment by BielBdeLuna** [comment]
https://github.com/GStreamer/gst-plugins-bad/commit/dc57fb7095b5041e4f3a4cae2bafd56369e10212

vulkan dropped `VK_*_BEGIN_RANGE`, `VK_*_END_RANGE`, and `VK_*_RANGE_SIZE` This was removed in Vulkan 1.2.140. so this should fall under "unknown" in RenderBackend_VK.cpp

**Comment by r-a-sattarov** [comment]
> vulkan dropped `VK_*_BEGIN_RANGE`, `VK_*_END_RANGE`, and `VK_*_RANGE_SIZE` This was removed in Vulkan 1.2.140. so this should fall under "unknown" in RenderBackend_VK.cpp
> 
> commend out the lines or erase them to oblivion! XD

Did these code changes fix your bug?
- https://github.com/RobertBeckebans/RBDOOM-3-BFG/commit/c8af9c3b0e69fe4aab6dc4b3462e180a8560c750

**Comment by RobertBeckebans** [comment]
No there is still way more to it. I need to get RBDOOM working against the newest glslang compiler.

**Comment by BielBdeLuna** [comment]
the ssGI effect is impressive! sikkmod used to have something very similar
