### ISSUE TITLE
Is it possible to implement the "Advanced Settings" from Classic-RBDOOM-3-BFG?

### ISSUE THREAD

**Issue by r-a-sattarov** [RobertBeckebans/RBDOOM-3-BFG#482]
Is it possible to implement the "Advanced Settings" in main menu, like it was done in https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG?
In my opinion, this is very conveniently and helps to enable/disable new graphic effects in menu, and not through variables in console.
Maybe @MadDeCoDeR can help with this?

![rbdoom-3-bfg-advanced-options_1](https://user-images.githubusercontent.com/51679282/88223426-235e2f80-cc70-11ea-9690-3b8ee95fd3de.png)

![rbdoom-3-bfg-advanced-options_2](https://user-images.githubusercontent.com/51679282/88223474-37a22c80-cc70-11ea-99ff-58d221a218f2.png)

**Comment by RobertBeckebans** [comment]
I'm quite busy with another commercial project at the moment but this is definitely on my todo list for the upcoming 1.3.0 release.

**Comment by r-a-sattarov** [comment]
> I'm quite busy with another commercial project at the moment but this is definitely on my todo list for the upcoming 1.3.0 release.

Thanks a lot!
