### ISSUE TITLE
Request: build profile for FreeBSD

### ISSUE THREAD

**Issue by wsky0csky** [RobertBeckebans/RBDOOM-3-BFG#485]
I'd like to see build profile dedicated for FreeBSD, thank you.

**Comment by danieleftodi** [comment]
a bash script to execute cmake for FreeBSD?

I made one for macOS recently, shouldn't be hard to make one for FreeBSD. 

Though I don't have FreeBSD, ... have you tried the Linux-scripts? Getting any errors?

**Comment by RobertBeckebans** [comment]
FreeBSD isn't supported.
