### ISSUE TITLE
Red screen bug when taken damage, only if motion blur is ON

### ISSUE THREAD

**Issue by wizzardyno** [RobertBeckebans/RBDOOM-3-BFG#493]

**Comment by Calinou** [comment]
Which operating system, graphics card and RBDOOM-3-BFG version are you using? Can you post screenshots (or better, a video) of the issue?

**Comment by wizzardyno** [comment]
> Which operating system, graphics card and RBDOOM-3-BFG version are you using? Can you post screenshots (or better, a video) of the issue?

Win10 x64, I7860, GTX970, 16RAM, RBDOOM-3-BFG 1.2.0 on Steam Doom3 BFG.
![20201008132631_1](https://user-images.githubusercontent.com/72463225/95447693-cdde1880-096a-11eb-88cb-de92d1eab111.jpg)

Video from youtube with BFA mod (based on RBDoom) but I have the same **https://youtu.be/1c0X2MCtQ-g?t=1752**
And I taken answer from BFA mod creator - _"Sadly I really don't know what exactly causes the red screen bug. I am not so good with graphics, I used RBDoom as a base for my port since the guys behind seems to know quite better about graphics than me. Really sorry."_
According to my observations this only when motion blur is ON.

**Comment by RobertBeckebans** [comment]
Motion blur is unsupported in RBDoom.
