### ISSUE TITLE
SSAO doesn't display

### ISSUE THREAD

**Issue by BielBdeLuna** [RobertBeckebans/RBDOOM-3-BFG#500]
with hdr with r_useSSAO 1 you can see the effect with r_ssaodebug 1 and you can toggle it's filtering, but outside the debug mode, the ssao doesn't display at all. com_showfps 2 does show SSAO "wasting" ns but the effect is not displayed.

**Comment by RobertBeckebans** [comment]
SSAO is only used in the PBR IBL ambient pass now. It is correct that you can't see it without the indirect lighting probes but that's going to change soon.

**Comment by BielBdeLuna** [comment]
ok :+1:
