### ISSUE TITLE
Attempted to load %s decl '%s' from game thread! freezes the game

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#502]
If idLib::Error( ) is called from game thread the game does not return to the main menu with the console open and showing the error message.
Instead it freezes the engine because the game thread waits for an infinity for a new signal.

Current workaround is to disable the entire check:
```
if( !idLib::IsMainThread() )
		{
			// we can't load images from a background thread on OpenGL,
			// the renderer on the main thread should parse it if needed
			idLib::Error( "Attempted to load %s decl '%s' from game thread!", GetDeclNameFromType( type ), name );
		}
```

**Comment by BielBdeLuna** [comment]
this has been the bane of my existence in the version of the engine, for sounds you can precache them, maybe there is a lead there? [cache sounds on Modwiki]( https://modwiki.dhewm3.org/CacheSoundShader_%28script_event%29) via script command
