### ISSUE TITLE
Question: Can I reduce the memory usage?

### ISSUE THREAD

**Issue by luigifcruz** [RobertBeckebans/RBDOOM-3-BFG#505]
I'm trying to run the Vulkan version of RBDOOM-3-BFG with the experimental Vulkan driver for the Raspberry Pi's Broadcom GPU (V3D). 

I'm documenting my progress in this blog [post](https://luigi.ltd/2020-12-02/trying-to-run-doom-with-the-raspberry-pi4-vulkan-driver/). I have already applied multiple patches to the Mesa drivers like Texture Compression. I got to a point where the game doesn't crash anymore.

The problem is that I'm limited to 2GB of system memory. This doesn't seem enough to finish loading all textures and assets. Nothing is displayed on the screen.

Is there any particular set of command-line options that I can set to reduce the memory usage and/or reduce the load on the GPU?

**Comment by Calinou** [comment]
I suppose the [Doom 3 Voodoo](https://www.youtube.com/watch?v=KQSIT18bOvg) video might give some helpful tips. :eyes:

**Comment by RobertBeckebans** [comment]
The BFG renderer is very different and all those image_ cvars got removed. There is only one left and that allows you to switch between low or high quality DXT compression when importing new textures to the .bimage format.

The only way to save VRAM with the Vulkan backend would be to introduce a new cvar similar like r_picmic in Quake 3.
When uploading the images into the VRAM you could skip the first 1-2 mip map levels. If you skip the first one you should save ~60% of the VRAM used there.

**Comment by BielBdeLuna** [comment]
couldn't a atlas texture optimize the texture budget and help with it too? an atlas like the one in Brink that, unlike the one used in Rage, store repeating textures in a single instance within the atlas.
I think @jmarshall23 coded a virtual texture that does this

**Comment by RobertBeckebans** [comment]
I think virtual texturing is not worth the trouble. Well RBDOOM-3-BFG should only consume about 65 megs RAM and ~256-400 megs VRAM because of the already used block compression for textures.

**Comment by luigifcruz** [comment]
Unfortunately, I tried all the suggestions posted here but no luck. I will close this issue and try again when I buy a new Raspberry Pi with more DRAM. Thanks everyone!

**Comment by infapi00** [comment]
@luigifcruz pointed me this issue. FWIW, one of the issues is that doom3 do a preloading of all images (or if not, at least of a lot not needed initially). Adding this to the autoexec.cfg:

`seta preLoad_Images "0"`

allowed me to get the game to the main UI. Loading a map later still fails, but not due memory reasons. Will investigate a little this week the problem.
