### ISSUE TITLE
TrenchBroom interop

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#506]
Make some commands to automatically export .def files to Valve FGD format for usage in the TrenchBroom editor.
This will aid the WIP Doom 3 support in TrenchBroom here: https://github.com/RobertBeckebans/TrenchBroom/tree/doom3-support

**Comment by RobertBeckebans** [comment]
First progress on this:

![2021-01-07 23_42_17-mars_city1 map_ - TrenchBroom](https://user-images.githubusercontent.com/1278614/104011310-29a87f80-51ae-11eb-90aa-ef2bc02be53d.jpg)

**Comment by BielBdeLuna** [comment]
this is awesome!
