### ISSUE TITLE
FFmpeg segfault during : 'video/mars_rotation.bik'

### ISSUE THREAD

**Issue by xcom169** [RobertBeckebans/RBDOOM-3-BFG#510]
Hello All!

I compiled the binary on Manjaro Linux but I can't open up the game. 
I have ' loaded ffmpeg file: 'video/mars_rotation.bik', looping=11567x406, 30.000000 fps, 100.000000 secsignal caught: segmentation fault ' error. 

Can I somehow repair this error with skipping the intro movies?

**Comment by xcom169** [comment]
Without CMAKE  FFMPEG flag the binary is working

**Comment by RobertBeckebans** [comment]
You can use libbinkdev instead of FFmpeg. See https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/484

**Comment by xcom169** [comment]
You were right. It was okay with libbinkdev .  
Is it enough to change it in  /build/CMakeCache.txt  and then generate the new Makefile?

**Comment by xcom169** [comment]
Hopefully the new stable ffmpeg will fix this.
