### ISSUE TITLE
Compile error with Mikktspace

### ISSUE THREAD

**Issue by BielBdeLuna** [RobertBeckebans/RBDOOM-3-BFG#511]
I got the following error:

> [  9%] Building C object CMakeFiles/RBDoom3BFG.dir/libs/mikktspace/mikktspace.c.o
cc1: warning: /home/biel/code/doom/doom3/RBDOOM-3-BFG/neo/idlib/precompiled.h.gch: not for GNU C17
In file included from /home/biel/code/doom/doom3/RBDOOM-3-BFG/neo/idlib/precompiled.h:34,
                 from <command-line>:
/home/biel/code/doom/doom3/RBDOOM-3-BFG/neo/idlib/sys/sys_includes.h:145:10: fatal error: typeinfo: El fitxer o directori no existeix
  145 | #include <typeinfo>
      |          ^~~~~~~~~~

**Comment by RobertBeckebans** [comment]
It should be fixed with the latest commit in master.

**Comment by BielBdeLuna** [comment]
it works :)
