### ISSUE TITLE
No graphics options in the game menu? 

### ISSUE THREAD

**Issue by xcom169** [RobertBeckebans/RBDOOM-3-BFG#514]
I built the game on Linux 64bit, but when I enter to the options menu I can't fine tune the graphics options. I have only approx. 4-5 video options and those are all. 
Is it normal?

**Comment by Calinou** [comment]
Can you take a screenshot of the options menu?

The game doesn't offer a whole lot of video options, but many settings can be tweaked using the console.

**Comment by xcom169** [comment]
Sure: 
![image](https://user-images.githubusercontent.com/17802090/103477662-4a915f00-4dc1-11eb-9bf0-79b477039685.png)

**Comment by Calinou** [comment]
> That's all I should have ?

Yes, the system options menu was never significantly expanded in RBDOOM-3-BFG.

**Comment by r-a-sattarov** [comment]
I previously asked about this in this thread https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/482
