### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by Weselton** [RobertBeckebans/RBDOOM-3-BFG#516]
System: Fedora 33 x64
Video Cards: Geforce 1050ti and Intel graphics 630
After compiling according to the instructions at https://github.com/RobertBeckebans/RBDOOM-3-BFG#compile_linux I start the game with the command "__NV_PRIME_RENDER_OFFLOAD = 1 __GLX_VENDOR_LIBRARY_NAME = nvidia ./RBDoom3BFG", a black window appears and disappears after a few seconds. Moreover, the same actions and commands start compile and run the game in Debian Testing successfully.

Console output:

> QA Timing INIT: 000824ms
> RBDOOM 3 BFG 1.3.0.1401 linux-x86_64 Jan  7 2021 11:02:20
> found interface lo - loopback
> found interface enp3s0 - 192.168.0.100/255.255.255.0
> found interface wlo1 - 192.168.0.102/255.255.255.0
> found interface virbr0 - 192.168.122.1/255.255.255.0
> ------ Initializing File System ------
> Loaded resource file _common.resources
> Loaded resource file _ordered.resources
> Loaded resource file _sound_pc.resources
> Loaded resource file _sound_pc_en.resources
> Loaded resource file maps/admin.resources
> Loaded resource file maps/alphalabs1.resources
> Loaded resource file maps/alphalabs2.resources
> Loaded resource file maps/alphalabs3.resources
> Loaded resource file maps/alphalabs4.resources
> Loaded resource file maps/caverns1.resources
> Loaded resource file maps/caverns2.resources
> Loaded resource file maps/comm1.resources
> Loaded resource file maps/commoutside.resources
> Loaded resource file maps/cpu.resources
> Loaded resource file maps/cpuboss.resources
> Loaded resource file maps/d3ctf1.resources
> Loaded resource file maps/d3ctf2.resources
> Loaded resource file maps/d3ctf3.resources
> Loaded resource file maps/d3ctf4.resources
> Loaded resource file maps/d3dm1.resources
> Loaded resource file maps/d3dm2.resources
> Loaded resource file maps/d3dm3.resources
> Loaded resource file maps/d3dm4.resources
> Loaded resource file maps/d3dm5.resources
> Loaded resource file maps/d3xpdm1.resources
> Loaded resource file maps/d3xpdm2.resources
> Loaded resource file maps/d3xpdm3.resources
> Loaded resource file maps/d3xpdm4.resources
> Loaded resource file maps/delta1.resources
> Loaded resource file maps/delta2a.resources
> Loaded resource file maps/delta2b.resources
> Loaded resource file maps/delta3.resources
> Loaded resource file maps/delta4.resources
> Loaded resource file maps/delta5.resources
> Loaded resource file maps/deltax.resources
> Loaded resource file maps/enpro.resources
> Loaded resource file maps/erebus1.resources
> Loaded resource file maps/erebus2.resources
> Loaded resource file maps/erebus3.resources
> Loaded resource file maps/erebus4.resources
> Loaded resource file maps/erebus5.resources
> Loaded resource file maps/erebus6.resources
> Loaded resource file maps/hell.resources
> Loaded resource file maps/hell1.resources
> Loaded resource file maps/hellhole.resources
> Loaded resource file maps/le_enpro1.resources
> Loaded resource file maps/le_enpro2.resources
> Loaded resource file maps/le_exis1.resources
> Loaded resource file maps/le_exis2.resources
> Loaded resource file maps/le_hell.resources
> Loaded resource file maps/le_hell_post.resources
> Loaded resource file maps/le_underground.resources
> Loaded resource file maps/le_underground2.resources
> Loaded resource file maps/mars_city1.resources
> Loaded resource file maps/mars_city2.resources
> Loaded resource file maps/mc_underground.resources
> Loaded resource file maps/monorail.resources
> Loaded resource file maps/phobos1.resources
> Loaded resource file maps/phobos2.resources
> Loaded resource file maps/phobos3.resources
> Loaded resource file maps/phobos4.resources
> Loaded resource file maps/recycling1.resources
> Loaded resource file maps/recycling2.resources
> Loaded resource file maps/site3.resources
> Current search path:
> /home/herman/.local/share/rbdoom3bfg/base
> /home/herman/Games/doom-3-bfg-edition/base
> _common.resources
> _ordered.resources
> _sound_pc.resources
> _sound_pc_en.resources
> maps/admin.resources
> maps/alphalabs1.resources
> maps/alphalabs2.resources
> maps/alphalabs3.resources
> maps/alphalabs4.resources
> maps/caverns1.resources
> maps/caverns2.resources
> maps/comm1.resources
> maps/commoutside.resources
> maps/cpu.resources
> maps/cpuboss.resources
> maps/d3ctf1.resources
> maps/d3ctf2.resources
> maps/d3ctf3.resources
> maps/d3ctf4.resources
> maps/d3dm1.resources
> maps/d3dm2.resources
> maps/d3dm3.resources
> maps/d3dm4.resources
> maps/d3dm5.resources
> maps/d3xpdm1.resources
> maps/d3xpdm2.resources
> maps/d3xpdm3.resources
> maps/d3xpdm4.resources
> maps/delta1.resources
> maps/delta2a.resources
> maps/delta2b.resources
> maps/delta3.resources
> maps/delta4.resources
> maps/delta5.resources
> maps/deltax.resources
> maps/enpro.resources
> maps/erebus1.resources
> maps/erebus2.resources
> maps/erebus3.resources
> maps/erebus4.resources
> maps/erebus5.resources
> maps/erebus6.resources
> maps/hell.resources
> maps/hell1.resources
> maps/hellhole.resources
> maps/le_enpro1.resources
> maps/le_enpro2.resources
> maps/le_exis1.resources
> maps/le_exis2.resources
> maps/le_hell.resources
> maps/le_hell_post.resources
> maps/le_underground.resources
> maps/le_underground2.resources
> maps/mars_city1.resources
> maps/mars_city2.resources
> maps/mc_underground.resources
> maps/monorail.resources
> maps/phobos1.resources
> maps/phobos2.resources
> maps/phobos3.resources
> maps/phobos4.resources
> maps/recycling1.resources
> maps/recycling2.resources
> maps/site3.resources
> file system initialized.
> --------------------------------------
> WARNING: Unable to open resource file maps/_startup.resources
> ----- Initializing Decls -----
> ------------------------------
> Couldn't open journal files
> /proc/cpuinfo CPU processors: 4
> /proc/cpuinfo CPU logical cores: 8
> execing default.cfg
> couldn't exec D3BFGConfig.cfg
> couldn't exec autoexec.cfg
> ----- R_InitOpenGL -----
> Initializing OpenGL subsystem
> Using 8 color bits, 24 depth, 8 stencil display
> Using GLEW 2.0.0
> OpenGL Version   : 4.6
> OpenGL Vendor    : NVIDIA Corporation
> OpenGL Renderer  : GeForce GTX 1050 Ti/PCIe/SSE2
> OpenGL GLSL      : 4.6
> idCommon::VPrintf: truncated to 4094 characters
> OpenGL Extensions: GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_AMD_vertex_shader_viewport_index GL_AMD_vertex_shader_layer GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_fragment_shader_interlock GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_post_depth_coverage GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_locations GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_sparse_texture2 GL_ARB_sparse_texture_clamp GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_filter_minmax GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_trans
>    maxTextureAnisotropy: 16.000000
> ...using GL_EXT_texture_lod_bias
> X..GL_GREMEDY_string_marker not found
> ...using GLEW_KHR_debug
> ...using GL_ARB_framebuffer_object
> ...using GL_EXT_framebuffer_blit
> ----- Initializing Render Shaders -----
> ----- Initializing Sound System ------
> Setup OpenAL device and context... Done.
> OpenAL vendor: OpenAL Community
> OpenAL renderer: OpenAL Soft
> OpenAL version: 1.1 ALSOFT 1.19.1
> OpenAL extensions: AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_EXT_SOURCE_RADIUS AL_EXT_STEREO_ANGLES AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFTX_events AL_SOFTX_filter_gain_ex AL_SOFT_gain_clamp_ex AL_SOFT_loop_points AL_SOFTX_map_buffer AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length AL_SOFT_source_resampler AL_SOFT_source_spatialize
> sound system initialized.
> --------------------------------------
> ------- Initializing renderSystem --------
> Binarize File: '_default' - reason 'generated image'
> Binarize File: '_white' - reason 'generated image'
> Binarize File: '_black' - reason 'generated image'
> Binarize File: '_cyan' - reason 'generated image'
> Binarize File: '_flat' - reason 'generated image'
> Binarize File: '_alphaNotch' - reason 'generated image'
> Binarize File: '_fog' - reason 'generated image'
> Binarize File: '_fogEnter' - reason 'generated image'
> Binarize File: '_noFalloff' - reason 'generated image'
> Binarize File: '_quadratic' - reason 'generated image'
> Binarize File: '_jitter1' - reason 'generated image'
> Binarize File: '_jitter4' - reason 'generated image'
> Binarize File: '_jitter16' - reason 'generated image'
> Binarize File: '_random256' - reason 'generated image'
> Binarize File: '_blueNoise256' - reason 'generated image'
> Binarize File: '_heatmap5' - reason 'generated image'
> Binarize File: '_heatmap7' - reason 'generated image'
> Binarize File: '_grain1' - reason 'generated image'
> Binarize File: '_smaaInput' - reason 'generated image'
> Binarize File: '_smaaArea' - reason 'generated image'
> Binarize File: '_smaaSearch' - reason 'generated image'
> Binarize File: '_imguiFont' - reason 'generated image'
> Binarize File: '_chromeSpec' - reason 'generated image'
> Binarize File: '_plasticSpec' - reason 'generated image'
> Binarize File: '_brdfLut' - reason 'generated image'
> Binarize File: '_scratch' - reason 'generated image'
> Binarize File: '_scratch2' - reason 'generated image'
> Binarize File: '_accum' - reason 'generated image'
> Binarize File: '_currentRender' - reason 'generated image'
> WARNING: Couldn't load cube image: env/testmap_1_amb
> WARNING: Couldn't load cube image: env/testmap_1_spec
> Updating texture filter parameters.
> renderSystem initialized.
> --------------------------------------
> Skipping Intro Videos!
> Reading strings/english.lang as UTF-8
> 9104 strings read
> --------- Initializing Game ----------
> gamename: baseDOOM-1
> gamedate: Jan  7 2021
> Initializing event system
> ...540 event definitions
> Initializing class hierarchy
> ...159 classes, 1010880 bytes for event callbacks
> execing default.cfg
> Initializing scripts
> measured CPU frequency: 2304.28 MHz
> Compiled '/home/herman/Games/doom-3-bfg-edition/base/script/doom_main.script': 871.3 ms
> ---------- Compile stats ----------
> 
> Memory usage:
>      Strings: 120, 15840 bytes
>   Statements: 95386, 3815440 bytes
>    Functions: 3070, 496728 bytes
>    Variables: 239712 bytes
>     Mem used: 6284512 bytes
>  Static data: 6266520 bytes
>    Allocated: 8567312 bytes
>  Thread size: 14064 bytes
> 
> ...6 aas types
> game initialized.
> --------------------------------------
> Loaded FFMPEG file: 'video/intro/introloop.bik', looping=1512x512, 30.000000 FPS, 12.000000 sec
> Binarize File: '_cinematic' - reason 'generated image'
> Loaded FFMPEG file: 'video/mars1.bik', looping=0512x512, 30.000000 FPS, 32.166668 sec
> Binarize File: '_cinematic' - reason 'generated image'
> Loaded FFMPEG file: 'video/mars_rotation.bik', looping=11567x406, 30.000000 FPS, 100.000000 sec
> signal caught: Segmentation fault
> si_code 128
> Trying to exit gracefully..
> session->GetSaveGameManager().CancelToTerminate();
> soundSystem->StopAllSounds();
> Stop();
> --------- Game Map Shutdown ----------
> --------------------------------------
> CleanupShell();
> delete loadGUI;
> ImGuiHook::Destroy();
> delete renderWorld;
> delete soundWorld;
> delete menuSoundWorld;
> session->ShutdownSoundRelatedSystems();
> session->Shutdown();
> game->Leaderboards_Shutdown();
> uiManager->Shutdown();
> soundSystem->Shutdown();
> usercmdGen->Shutdown();
> eventLoop->Shutdown();
> declManager->Shutdown();
> renderSystem->Shutdown();
> idRenderSystem::Shutdown()
> Shutting down OpenGL subsystem
> commonDialog.Shutdown();
> UnloadGameDLL();
> ------------ Game Shutdown -----------
> --------- Game Map Shutdown ----------
> --------------------------------------
> Shutdown event system
> --------------------------------------
> saveFile.Clear( true );
> stringsFile.Clear( true );
> CloseLogFile();
> fileSystem->Shutdown( false );
> Sys_Shutdown();
> console->Shutdown();
> idKeyInput::Shutdown();
> cvarSystem->Shutdown();
> cmdSystem->Shutdown();
> ClearWarnings( GAME_NAME " shutdown" );
> warningCaption.Clear();
> errorList.Clear();
> idLib::ShutDown();

**Comment by RobertBeckebans** [comment]
It is a fixed issue with FFmpeg. See https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/484
