### ISSUE TITLE
error: no matching function for call to `BlueNoise(ivec2, float)';

### ISSUE THREAD

**Issue by r-a-sattarov** [RobertBeckebans/RBDOOM-3-BFG#517]
When starting the game, there is an error message in the console:

`----- Initializing Render Shaders -----`
`While compiling fragment program renderprogs/AmbientOcclusion_AO.ps.hlsl`
`----- Initializing Render Shaders -----`
`...`
`0:143(37): error: no matching function for call to BlueNoise(ivec2, float); candidates are:`
`0:143(37): error:    float BlueNoise(vec2, float)`
`0:143(37): error: operands to arithmetic operators must be numeric`
`0:153(55): warning: randomPatternRotationAngle' used uninitialized`

PC configuration:
Elbrus-4C (4 core up to 800 MHz), Radeon R5 230 1 Gb, OS Elbrus 6 (Linux 5.4, Mesa 20.1.8).

I attach the game launch log.
[startup_RB-Doom3-BFG_pre-1.3.0_e2k_elbrus-4c](https://github.com/RobertBeckebans/RBDOOM-3-BFG/files/5844783/startup_RB-Doom3-BFG_pre-1.3.0_e2k_elbrus-4c.txt)

**Comment by RobertBeckebans** [comment]
It's annoying that Mesa broke it again. It compiles fine with proprietary Nvidia, AMD drivers and glslang.

**Comment by RobertBeckebans** [comment]
This should be fixed now.

**Comment by r-a-sattarov** [comment]
> This should be fixed now.

Danke Robert! Yes, previous errors have been fixed. There are only warnings left, but they are not critical.

`----- Initializing Render Shaders -----`
`While compiling fragment program renderprogs/builtin/SSGI/DeepGBufferRadiosity_radiosity.ps.hlsl`
`----- Initializing Render Shaders -----`
`...`
`0:103(43): warning: 'mipLevel' used uninitialized`
`0:103(54): warning: 'texel' used uninitialized`
`0:151(90): warning: 'Q' used uninitialized`
`0:151(94): warning: 'lambertian_tap' used uninitialized`
`0:151(111): warning: 'n_tap' used uninitialized`
`0:152(93): warning: 'E' used uninitialized`
`0:152(97): warning: 'weight_Y' used uninitialized`
`0:152(108): warning: 'visibilityWeight' used uninitialized`

The configuration of the my PC remains the same.

I attach the game launch log.
[startup_RB-Doom3-BFG_pre-1.3.0_e2k_elbrus-4c.txt](https://github.com/RobertBeckebans/RBDOOM-3-BFG/files/6305887/startup_RB-Doom3-BFG_pre-1.3.0_e2k_elbrus-4c.txt)
