### ISSUE TITLE
Framebuffer code

### ISSUE THREAD

**Issue by SEAGitUser** [RobertBeckebans/RBDOOM-3-BFG#525]
All the code of the renderbufferstorage can be completely removed. If you attach a texture to a framebuffer, then all rendering will go directly to that texture, and adding a renderbufferstorage on top is a waste of memory and bad for performane as the driver moves unused mem back and forth.

**Comment by RobertBeckebans** [comment]
Thanks for the hint. The FBO code is older than a decade and still from my old XreaL project. 
I'll look into it.

**Comment by RobertBeckebans** [comment]
This will be deleted because there is a new NVRHI backend in development.

**Comment by y2keeth** [comment]
hey xreal lol
    On Wednesday, February 17, 2021, 12:13:17 PM EST, Robert Beckebans ***@***.***> wrote:  
 
 


Thanks for the hint. The FBO code is older than a decade and still from my old XreaL project.
I'll look into it.
