### ISSUE TITLE
What version of OpenGL is needed? Mali G-52 GPU

### ISSUE THREAD

**Issue by Chatplosion** [RobertBeckebans/RBDOOM-3-BFG#542]
Dear developers,

I tried to get version 1.30 running on a ARM64 Hardkernel Odroid N2+.
It uses Mali G-52 GPU and supports official OpenGL 1.10, 1.20, 1.30, 1.40, 3.00, 3.10, 1.00 ES and 3.00 ES.
The OS is Ubuntu 20.10 with aa64 mainline Kernel 5.11 with MESA Panfrost video driver.
When I start the engine it just produces a white screen, but music and menu sounds are working.

What causes this?

**Comment by Calinou** [comment]
As far as I know, OpenGL 3.2 Core is required. I'm not sure if RBDOOM-3-BFG has an OpenGL ES renderer.

**Comment by Chatplosion** [comment]
From the error output is seen that the engine tries to start GLSL 4.50.
The DOOM 3 (Not BFG) was definitely below OpenGL 3.3 and was able to run on my SOC. 
On what OpenGL version was the original game running?
All infos about my problems are in the attached files.
[glxinfo.txt](https://github.com/RobertBeckebans/RBDOOM-3-BFG/files/6254919/glxinfo.txt)
[glewinfo.txt](https://github.com/RobertBeckebans/RBDOOM-3-BFG/files/6254921/glewinfo.txt)
[rbdoom3bfg-console.txt](https://github.com/RobertBeckebans/RBDOOM-3-BFG/files/6254922/rbdoom3bfg-console.txt)

**Comment by Calinou** [comment]
> On what OpenGL version was the original game running?

I believe original Doom 3 used OpenGL 2.0 or 2.1.

**Comment by Chatplosion** [comment]
I searched the hardware requirements of the idTech4 and the listed minimum was Nvidia GeForce 3 or ATI Radeon 8500.
These are based on OpenGL 1.3.
Can someone please check if it is possible to get the engine running with OpenGL 3.0?

**Comment by RobertBeckebans** [comment]
This port uses modern OpenGL with the direct state access API. I raised the minimum to OpenGL 4.5

**Comment by Chatplosion** [comment]
I want to make a suggestion.
What do you think about renaming your repo to BRDOOM-3-BFG+ and create a new fork legacy.
The new fork just needs to run without errors on OpenGL 3.1 and doesn't need further development.
I would appreciate it if you or someone of the developers can build a fork that is called legacy.
It can be a nice addition to the Ubuntu/Debian ARM64. I like it, but I am not a programmer.

**Comment by RobertBeckebans** [comment]
You can just download version 1.1. Forking is a bad idea because it splits the development and new stuff won't be merged or causes additional work because the pull requests (if done at all) go into legacy stuff. There were already forks of this port and people don't keep up with the upstream improvements and the users get upset about broken stuff that was already fixed in this repo.
 I can't support all kinds of limited OpenGL drivers.
