### ISSUE TITLE
V1.1.0-preview3 can't get compiled

### ISSUE THREAD

**Issue by Chatplosion** [RobertBeckebans/RBDOOM-3-BFG#543]
At the first try I got following:

> ./cmake-eclipse-linux-profile.sh
> -- The C compiler identification is GNU 10.2.0
> -- The CXX compiler identification is GNU 10.2.0
> -- Could not determine Eclipse version, assuming at least 3.6 (Helios). Adjust CMAKE_ECLIPSE_VERSION if this is wrong.
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- CMAKE_BUILD_TYPE:RelWithDebInfo
> CMake Warning (dev) at idlib/CMakeLists.txt:127 (GET_DIRECTORY_PROPERTY):
>   Policy CMP0059 is not set: Do not treat DEFINITIONS as a built-in directory
>   property.  Run "cmake --help-policy CMP0059" for policy details.  Use the
>   cmake_policy command to set the policy and suppress this warning.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) at /usr/share/cmake-3.16/Modules/FindOpenGL.cmake:275 (message):
>   Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
>   available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
>   cmake_policy command to set the policy and suppress this warning.
> 
>   FindOpenGL found both a legacy GL library:
> 
>     OPENGL_gl_LIBRARY: /usr/lib/aarch64-linux-gnu/libGL.so
> 
>   and GLVND libraries for OpenGL and GLX:
> 
>     OPENGL_opengl_LIBRARY: /usr/lib/aarch64-linux-gnu/libOpenGL.so
>     OPENGL_glx_LIBRARY: /usr/lib/aarch64-linux-gnu/libGLX.so
> 
>   OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
>   compatibility with CMake 3.10 and below the legacy GL library will be used.
> Call Stack (most recent call first):
>   CMakeLists.txt:1480 (find_package)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Found OpenGL: /usr/lib/aarch64-linux-gnu/libOpenGL.so   
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Found SDL2: /usr/lib/aarch64-linux-gnu/libSDL2main.a;/usr/lib/aarch64-linux-gnu/libSDL2.so;-lpthread  
> -- Found OpenAL: /usr/lib/aarch64-linux-gnu/libopenal.so  
> CMake Warning (dev) at CMakeLists.txt:1589 (GET_DIRECTORY_PROPERTY):
>   Policy CMP0059 is not set: Do not treat DEFINITIONS as a built-in directory
>   property.  Run "cmake --help-policy CMP0059" for policy details.  Use the
>   cmake_policy command to set the policy and suppress this warning.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build
> 

And make displayed:

> make
> make[1]: Verzeichnis „/home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build“ wird betreten
> make[2]: Verzeichnis „/home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build“ wird betreten
> Scanning dependencies of target precomp_header_idlib
> make[2]: Verzeichnis „/home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build“ wird verlassen
> make[2]: Verzeichnis „/home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build“ wird betreten
> [  0%] Creating idlib/precompiled.h.gch for idlib
> c++: error: unrecognized command-line option ‘-mmmx’
> c++: error: unrecognized command-line option ‘-msse’
> c++: error: unrecognized command-line option ‘-msse2’
> make[2]: *** [idlib/CMakeFiles/precomp_header_idlib.dir/build.make:58: idlib/CMakeFiles/precomp_header_idlib] Fehler 1
> make[2]: Verzeichnis „/home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build“ wird verlassen
> make[1]: *** [CMakeFiles/Makefile2:211: idlib/CMakeFiles/precomp_header_idlib.dir/all] Fehler 2
> make[1]: Verzeichnis „/home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build“ wird verlassen
> make: *** [Makefile:84: all] Fehler 2

I installed the JRE&JDK to eradicate the eclipse error. But I can't compile it.
It seems that there are errors in the CMakeLists.txt and issues wit cmake policies.
What am I doing wrong?

**Comment by Chatplosion** [comment]
I would be thankful if someone does have interest in my problem. I want to make this game runnable on ARM64 computers.
But as a lone handicapped person without programming experience it is near to impossible.
So please help me to find what is wrong and correct it.

**Comment by r-a-sattarov** [comment]
> I would be thankful if someone does have interest in my problem. I want to make this game runnable on ARM64 computers.
> But as a lone handicapped person without programming experience it is near to impossible.
> So please help me to find what is wrong and correct it.

You need to implement changes in code from this PR - https://github.com/RobertBeckebans/RBDOOM-3-BFG/pull/473

**Comment by Chatplosion** [comment]
Thank you for the first improvement. At least it made a difference on what I got.
I didn't see that the ARM-Architecture was missing completly at all. Maybe I am blind to content.
Now I am trying again with following output:

> odroid@odroid-n2plus:~/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/neo$ ./cmake-linux-release.sh
> -- The C compiler identification is GNU 10.2.0
> -- The CXX compiler identification is GNU 10.2.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- CMAKE_BUILD_TYPE:Release
> CMake Warning (dev) at idlib/CMakeLists.txt:127 (GET_DIRECTORY_PROPERTY):
>   Policy CMP0059 is not set: Do not treat DEFINITIONS as a built-in directory
>   property.  Run "cmake --help-policy CMP0059" for policy details.  Use the
>   cmake_policy command to set the policy and suppress this warning.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) at /usr/share/cmake-3.16/Modules/FindOpenGL.cmake:275 (message):
>   Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
>   available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
>   cmake_policy command to set the policy and suppress this warning.
> 
>   FindOpenGL found both a legacy GL library:
> 
>     OPENGL_gl_LIBRARY: /usr/lib/aarch64-linux-gnu/libGL.so
> 
>   and GLVND libraries for OpenGL and GLX:
> 
>     OPENGL_opengl_LIBRARY: /usr/lib/aarch64-linux-gnu/libOpenGL.so
>     OPENGL_glx_LIBRARY: /usr/lib/aarch64-linux-gnu/libGLX.so
> 
>   OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
>   compatibility with CMake 3.10 and below the legacy GL library will be used.
> Call Stack (most recent call first):
>   CMakeLists.txt:1467 (find_package)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Found OpenGL: /usr/lib/aarch64-linux-gnu/libOpenGL.so   
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
> -- Checking for module 'libavcodec'
> --   Found libavcodec, version 58.91.100
> -- Checking for module 'libavformat'
> --   Found libavformat, version 58.45.100
> -- Checking for module 'libavutil'
> --   Found libavutil, version 56.51.100
> -- Checking for module 'libswscale'
> --   Found libswscale, version 5.7.100
> -- Found FFMPEG or Libav: /usr/lib/aarch64-linux-gnu/libavcodec.so;/usr/lib/aarch64-linux-gnu/libavformat.so;/usr/lib/aarch64-linux-gnu/libavutil.so;/usr/lib/aarch64-linux-gnu/libswscale.so, /usr/include/aarch64-linux-gnu
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Found SDL2: /usr/lib/aarch64-linux-gnu/libSDL2main.a;/usr/lib/aarch64-linux-gnu/libSDL2.so;-lpthread  
> -- Found OpenAL: /usr/lib/aarch64-linux-gnu/libopenal.so  
> CMake Warning (dev) at CMakeLists.txt:1557 (GET_DIRECTORY_PROPERTY):
>   Policy CMP0059 is not set: Do not treat DEFINITIONS as a built-in directory
>   property.  Run "cmake --help-policy CMP0059" for policy details.  Use the
>   cmake_policy command to set the policy and suppress this warning.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build
> 
And the make command gives this:
> odroid@odroid-n2plus:\~/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/neo$ cd ../build
> odroid@odroid-n2plus:\~/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build$ make
> make[1]: Verzeichnis „/home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build“ wird betreten
> make[2]: Verzeichnis „/home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build“ wird betreten
> Scanning dependencies of target precomp_header_idlib
> make[2]: Verzeichnis „/home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build“ wird verlassen
> make[2]: Verzeichnis „/home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build“ wird betreten
> [  0%] Creating idlib/precompiled.h.gch for idlib
> In file included from precompiled.h:37:
> sys/sys_intrinsics.h:33:10: fatal error: emmintrin.h: Datei oder Verzeichnis nicht gefunden
>    33 | #include <emmintrin.h>
>       |          ^~~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [idlib/CMakeFiles/precomp_header_idlib.dir/build.make:58: idlib/CMakeFiles/precomp_header_idlib] Fehler 1
> make[2]: Verzeichnis „/home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build“ wird verlassen
> make[1]: *** [CMakeFiles/Makefile2:211: idlib/CMakeFiles/precomp_header_idlib.dir/all] Fehler 2
> make[1]: Verzeichnis „/home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build“ wird verlassen
> make: *** [Makefile:84: all] Fehler 2

So, what can I learn from it? There are cmake policy errors to correct. And something big else seems to be missing on my system or in this source directory. But what exactly? I am feeling sick and I understand that beeing a programer is not fun.

**Comment by r-a-sattarov** [comment]
>sys/sys_intrinsics.h:33:10: fatal error: emmintrin.h: Datei oder Verzeichnis nicht gefunden
>33 | #include <emmintrin.h>

You need to turn off the use of Intel Intrinsics.

`mkdir build && cd build`
`cmake -DCMAKE_BUILD_TYPE=Release -DSDL2=ON -DONATIVE=ON -DFFMPEG=OFF -DBINKDEC=ON -DUSE_INTRINSICS=OFF ../neo`
`make -j4`

But as far as I know, ARM Mali-G52 GPU supports Vulkan 1.0, so you can try to use the latest version of RBDOOM-3-BFG.

`cmake -DCMAKE_BUILD_TYPE=Release -DSDL2=ON -DONATIVE=ON -DFFMPEG=OFF -DBINKDEC=ON -DUSE_INTRINSICS=OFF -DUSE_VULKAN=ON -DSPIRV_SHADERC=OFF ../neo`

**Comment by Chatplosion** [comment]
I tried to compile with Vulkan, but it is not possible. Only the Andoid OS is rightfully licensed to use Vulkan on Odroid.
It is very unlikely that others do create a Vulkan renderer for linux with Odroid without any manufacturer or vendor support.

The ouput of cmake is:

```
odroid@odroid-n2plus:~/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build$ cmake DCMAKE_BUILD_TYPE=Release -DSDL2=ON -DONATIVE=ON -DFFMPEG=ON -DUSE_INTRINSICS=OFF ../neo
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE:Release
CMake Warning (dev) at idlib/CMakeLists.txt:127 (GET_DIRECTORY_PROPERTY):
  Policy CMP0059 is not set: Do not treat DEFINITIONS as a built-in directory
  property.  Run "cmake --help-policy CMP0059" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/share/cmake-3.16/Modules/FindOpenGL.cmake:275 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/aarch64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/aarch64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/aarch64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  CMakeLists.txt:1467 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL: /usr/lib/aarch64-linux-gnu/libOpenGL.so   
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'libavcodec'
--   Found libavcodec, version 58.91.100
-- Checking for module 'libavformat'
--   Found libavformat, version 58.45.100
-- Checking for module 'libavutil'
--   Found libavutil, version 56.51.100
-- Checking for module 'libswscale'
--   Found libswscale, version 5.7.100
-- Found FFMPEG or Libav: /usr/lib/aarch64-linux-gnu/libavcodec.so;/usr/lib/aarch64-linux-gnu/libavformat.so;/usr/lib/aarch64-linux-gnu/libavutil.so;/usr/lib/aarch64-linux-gnu/libswscale.so, /usr/include/aarch64-linux-gnu
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib/aarch64-linux-gnu/libSDL2main.a;/usr/lib/aarch64-linux-gnu/libSDL2.so;-lpthread  
-- Found OpenAL: /usr/lib/aarch64-linux-gnu/libopenal.so  
CMake Warning (dev) at CMakeLists.txt:1557 (GET_DIRECTORY_PROPERTY):
  Policy CMP0059 is not set: Do not treat DEFINITIONS as a built-in directory
  property.  Run "cmake --help-policy CMP0059" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build
```

And the output of make is:

```
odroid@odroid-n2plus:~/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build$ make -j4
make[1]: Verzeichnis „/home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build“ wird betreten
make[2]: Verzeichnis „/home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build“ wird betreten
Scanning dependencies of target precomp_header_idlib
make[2]: Verzeichnis „/home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build“ wird verlassen
make[2]: Verzeichnis „/home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build“ wird betreten
[  0%] Creating idlib/precompiled.h.gch for idlib
In file included from ../idlib/Lib.h:250,
                 from precompiled.h:48:
../idlib/Heap.h:72:1: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   72 | throw( std::bad_alloc ) // DG: standard signature seems to include throw(..)
      | ^~~~~
../idlib/Heap.h:87:1: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   87 | throw( std::bad_alloc ) // DG: standard signature seems to include throw(..)
      | ^~~~~
In file included from ../idlib/Lib.h:295,
                 from precompiled.h:48:
../idlib/StrStatic.h: In constructor ‘idStrStatic<_size_>::idStrStatic(bool)’:
../idlib/StrStatic.h:100:23: error: no matching function for call to ‘idStrStatic<_size_>::operator=(const bool&)’
  100 |   idStr::operator=( b );
      |                       ^
In file included from ../idlib/Lib.h:294,
                 from precompiled.h:48:
../idlib/Str.h:674:16: note: candidate: ‘void idStr::operator=(const idStr&)’
  674 | ID_INLINE void idStr::operator=( const idStr& text )
      |                ^~~~~
../idlib/Str.h:674:47: note:   no known conversion for argument 1 from ‘const bool’ to ‘const idStr&’
  674 | ID_INLINE void idStr::operator=( const idStr& text )
      |                                  ~~~~~~~~~~~~~^~~~
../idlib/Str.h:153:10: note: candidate: ‘void idStr::operator=(const char*)’
  153 |  void    operator=( const char* text );
      |          ^~~~~~~~
../idlib/Str.h:153:33: note:   no known conversion for argument 1 from ‘const bool’ to ‘const char*’
  153 |  void    operator=( const char* text );
      |                     ~~~~~~~~~~~~^~~~
In file included from ../idlib/Lib.h:295,
                 from precompiled.h:48:
../idlib/StrStatic.h: In constructor ‘idStrStatic<_size_>::idStrStatic(char)’:
../idlib/StrStatic.h:108:23: error: no matching function for call to ‘idStrStatic<_size_>::operator=(const char&)’
  108 |   idStr::operator=( c );
      |                       ^
In file included from ../idlib/Lib.h:294,
                 from precompiled.h:48:
../idlib/Str.h:674:16: note: candidate: ‘void idStr::operator=(const idStr&)’
  674 | ID_INLINE void idStr::operator=( const idStr& text )
      |                ^~~~~
../idlib/Str.h:674:47: note:   no known conversion for argument 1 from ‘const char’ to ‘const idStr&’
  674 | ID_INLINE void idStr::operator=( const idStr& text )
      |                                  ~~~~~~~~~~~~~^~~~
../idlib/Str.h:153:10: note: candidate: ‘void idStr::operator=(const char*)’ (near match)
  153 |  void    operator=( const char* text );
      |          ^~~~~~~~
../idlib/Str.h:153:10: note:   conversion of argument 1 would be ill-formed:
In file included from ../idlib/Lib.h:295,
                 from precompiled.h:48:
../idlib/StrStatic.h: In constructor ‘idStrStatic<_size_>::idStrStatic(int)’:
../idlib/StrStatic.h:116:23: error: no matching function for call to ‘idStrStatic<_size_>::operator=(const int&)’
  116 |   idStr::operator=( i );
      |                       ^
In file included from ../idlib/Lib.h:294,
                 from precompiled.h:48:
../idlib/Str.h:674:16: note: candidate: ‘void idStr::operator=(const idStr&)’
  674 | ID_INLINE void idStr::operator=( const idStr& text )
      |                ^~~~~
../idlib/Str.h:674:47: note:   no known conversion for argument 1 from ‘const int’ to ‘const idStr&’
  674 | ID_INLINE void idStr::operator=( const idStr& text )
      |                                  ~~~~~~~~~~~~~^~~~
../idlib/Str.h:153:10: note: candidate: ‘void idStr::operator=(const char*)’ (near match)
  153 |  void    operator=( const char* text );
      |          ^~~~~~~~
../idlib/Str.h:153:10: note:   conversion of argument 1 would be ill-formed:
In file included from ../idlib/Lib.h:295,
                 from precompiled.h:48:
../idlib/StrStatic.h: In constructor ‘idStrStatic<_size_>::idStrStatic(unsigned int)’:
../idlib/StrStatic.h:124:23: error: no matching function for call to ‘idStrStatic<_size_>::operator=(const unsigned int&)’
  124 |   idStr::operator=( u );
      |                       ^
In file included from ../idlib/Lib.h:294,
                 from precompiled.h:48:
../idlib/Str.h:674:16: note: candidate: ‘void idStr::operator=(const idStr&)’
  674 | ID_INLINE void idStr::operator=( const idStr& text )
      |                ^~~~~
../idlib/Str.h:674:47: note:   no known conversion for argument 1 from ‘const unsigned int’ to ‘const idStr&’
  674 | ID_INLINE void idStr::operator=( const idStr& text )
      |                                  ~~~~~~~~~~~~~^~~~
../idlib/Str.h:153:10: note: candidate: ‘void idStr::operator=(const char*)’ (near match)
  153 |  void    operator=( const char* text );
      |          ^~~~~~~~
../idlib/Str.h:153:10: note:   conversion of argument 1 would be ill-formed:
In file included from ../idlib/Lib.h:295,
                 from precompiled.h:48:
../idlib/StrStatic.h: In constructor ‘idStrStatic<_size_>::idStrStatic(float)’:
../idlib/StrStatic.h:132:23: error: no matching function for call to ‘idStrStatic<_size_>::operator=(const float&)’
  132 |   idStr::operator=( f );
      |                       ^
In file included from ../idlib/Lib.h:294,
                 from precompiled.h:48:
../idlib/Str.h:674:16: note: candidate: ‘void idStr::operator=(const idStr&)’
  674 | ID_INLINE void idStr::operator=( const idStr& text )
      |                ^~~~~
../idlib/Str.h:674:47: note:   no known conversion for argument 1 from ‘const float’ to ‘const idStr&’
  674 | ID_INLINE void idStr::operator=( const idStr& text )
      |                                  ~~~~~~~~~~~~~^~~~
../idlib/Str.h:153:10: note: candidate: ‘void idStr::operator=(const char*)’
  153 |  void    operator=( const char* text );
      |          ^~~~~~~~
../idlib/Str.h:153:33: note:   no known conversion for argument 1 from ‘const float’ to ‘const char*’
  153 |  void    operator=( const char* text );
      |                     ~~~~~~~~~~~~^~~~
In file included from ../framework/../sys/sys_localuser.h:31,
                 from ../framework/../sys/sys_session.h:32,
                 from ../framework/UsercmdGen.h:32,
                 from precompiled.h:66:
../framework/../sys/sys_profile.h: At global scope:
../framework/../sys/sys_profile.h:65:7: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   65 |  std::auto_ptr< idSaveGameProcessorSaveProfile > profileSaveProcessor;
      |       ^~~~~~~~
In file included from /usr/include/c++/10/memory:83,
                 from sys/sys_includes.h:148,
                 from precompiled.h:34:
/usr/include/c++/10/bits/unique_ptr.h:57:28: note: declared here
   57 |   template<typename> class auto_ptr;
      |                            ^~~~~~~~
In file included from ../framework/../sys/sys_localuser.h:31,
                 from ../framework/../sys/sys_session.h:32,
                 from ../framework/UsercmdGen.h:32,
                 from precompiled.h:66:
../framework/../sys/sys_profile.h:66:7: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   66 |  std::auto_ptr< idSaveGameProcessorLoadProfile > profileLoadProcessor;
      |       ^~~~~~~~
In file included from /usr/include/c++/10/memory:83,
                 from sys/sys_includes.h:148,
                 from precompiled.h:34:
/usr/include/c++/10/bits/unique_ptr.h:57:28: note: declared here
   57 |   template<typename> class auto_ptr;
      |                            ^~~~~~~~
make[2]: *** [idlib/CMakeFiles/precomp_header_idlib.dir/build.make:58: idlib/CMakeFiles/precomp_header_idlib] Fehler 1
make[2]: Verzeichnis „/home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build“ wird verlassen
make[1]: *** [CMakeFiles/Makefile2:211: idlib/CMakeFiles/precomp_header_idlib.dir/all] Fehler 2
make[1]: Verzeichnis „/home/odroid/RBDOOM-3-BFG_build/RBDOOM-3-BFG-1.1.0-preview3/build“ wird verlassen
make: *** [Makefile:84: all] Fehler 2
```

The compiling without Vulkan of V1.1.0preview3 is also failing. The code of Doom3BFG has hardcoded x86 and x86_64 instructions. But here is something interesting [https://github.com/simd-everywhere/simde](https://github.com/simd-everywhere/simde), this is able to adapt X86&X86_64 instructions to ARM64 with performance.
Other possibility is that the complete code needs to be rewritten for ARM64 compatibility. SIMDE is something I can imagine to work with minimal changes.

**Comment by r-a-sattarov** [comment]
> The code of Doom3BFG has hardcoded x86 and x86_64 instructions.
> Other possibility is that the complete code needs to be rewritten for ARM64 compatibility.

You are trying to compile a very old version of a game that may contain bugs that may have been fixed in newer versions.
Moreover, this game has already been launched on the ARM64 platform - https://github.com/RobertBeckebans/RBDOOM-3-BFG/pull/473

I highly recommend trying to compile the current development version.
`git clone --recursive https://github.com/RobertBeckebans/RBDOOM-3-BFG.git`
`cd RBDOOM-3-BFG && mkdir build && cd build`
`cmake -DCMAKE_BUILD_TYPE=Release -DSDL2=ON -DONATIVE=ON -DFFMPEG=OFF -DBINKDEC=ON -DUSE_INTRINSICS=OFF ../neo`
`make -j4`

**Comment by Chatplosion** [comment]
I wanted to use the latest, too. But the latest needs OpenGL 4.5 as minimum.
You can look it up here: #542
Some developer decisions can be a pain in the back.
So I am limited to ver1.1.0-preview3 just because of my graphic hardware limitations.
I will try to get people of the Odroid faction on this page, too. Maybe it is possible to
create something working.
