### ISSUE TITLE
Crash when exiting the game if loaded from a savegame

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#553]
Crash in 
```
idSaveLoadParms::~idSaveLoadParms()
{
	for( int i = 0; i < files.Num(); ++i )
	{
		if( files[i]->type & SAVEGAMEFILE_AUTO_DELETE )
		{
			delete files[i];
		}
	}
}
```

Steps to reproduce:
1. Don't use devmap or map. Load a map using a savegame. It does not matter wether it is a quicksave or a regular savegame
2. Quit the program

This is related to #378

**Comment by BielBdeLuna** [comment]
is it just a MAC thing? 
In Linux using OGL I get other segfaults when shutting down the sound after quitting, but none for anything related to the saving system.
Using VK I get a strange segfault but after the "shutdown terminal support" message when all threads are exiting ( segfault in thread 1 )

**Comment by RobertBeckebans** [comment]
Tested on Windows and Linux. Seems to be fixed.
