### ISSUE TITLE
r_ssaofiltering is set to 0 by default

### ISSUE THREAD

**Issue by BielBdeLuna** [RobertBeckebans/RBDOOM-3-BFG#555]
in line:
https://github.com/RobertBeckebans/RBDOOM-3-BFG/blob/b67612c67cd0635d75758ab2552db49346aa69a7/neo/renderer/RenderSystem_init.cpp#L309

shouldn't this be set to 1?

**Comment by RobertBeckebans** [comment]
This is intended because the filtering looked bad and performance was not good. I'll change it later when I have a better filtering technique.
