### ISSUE TITLE
Build fails due to libopenal

### ISSUE THREAD

**Issue by LETIshNick** [RobertBeckebans/RBDOOM-3-BFG#569]
I try to build the opengl-retail profile on macos 11.3. The build fails with the following message

`
[ 99%] Building CXX object CMakeFiles/RBDoom3BFG.dir/renderer/OpenGL/RenderProgs_GL.cpp.o
make[2]: *** No rule to make target '/usr/local/opt/openal-soft/lib/libopenal.dylib', needed by 'RBDoom3BFG'.  Stop.

make[1]: *** [CMakeFiles/RBDoom3BFG.dir/all] Error 2

make: *** [all] Error 2
`

**Comment by raynorpat** [comment]
Did you install openal-soft from Homebrew?

`brew install openal-soft`

**Comment by LETIshNick** [comment]
Now, I compiled it from sources. I can't use Homebrew because I use macports, they don't generally make friends.

**Comment by raynorpat** [comment]
In that case, find where the openal-soft .dylib library and include folder are and update the lines in the cmake-macos-opengl-retail.sh script to match where those are:

`-DOPENAL_LIBRARY=/usr/local/opt/openal-soft/lib/libopenal.dylib -DOPENAL_INCLUDE_DIR=/usr/local/opt/openal-soft/include`

What is in the script works for where Homebrew plops its wares.

**Comment by LETIshNick** [comment]
That worked, thanks. Just in case, the files were to be found at

`
-DOPENAL_LIBRARY=/opt/local/lib/libopenal.dylib 
-DOPENAL_INCLUDE_DIR=/opt/local/include/AL

**Comment by treeshateorcs** [comment]
i'm facing the same issue

```
build make -j9
[  0%] Creating idlib/precompiled.h.gch for idlib
[  0%] Built target precomp_header_idlib
[  9%] Built target idlib
[  9%] Creating idlib/precompiled.h.gch for RBDoom3BFG
[  9%] Built target precomp_header_rbdoom3bfg
make[2]: *** No rule to make target `/opt/local/lib/libopenal.dylib', needed by `RBDoom3BFG'.  Stop.
make[1]: *** [CMakeFiles/RBDoom3BFG.dir/all] Error 2
make: *** [all] Error 2

```


and my `brew list openal-soft`

```
build brew list openal-soft
/opt/homebrew/Cellar/openal-soft/1.21.1/bin/openal-info
/opt/homebrew/Cellar/openal-soft/1.21.1/include/AL/ (6 files)
/opt/homebrew/Cellar/openal-soft/1.21.1/lib/libopenal.1.21.1.dylib
/opt/homebrew/Cellar/openal-soft/1.21.1/lib/cmake/ (2 files)
/opt/homebrew/Cellar/openal-soft/1.21.1/lib/pkgconfig/openal.pc
/opt/homebrew/Cellar/openal-soft/1.21.1/lib/ (2 other files)
/opt/homebrew/Cellar/openal-soft/1.21.1/share/openal/ (9 files)
```
