### ISSUE TITLE
Linux build fails on Manjaro/gcc 11.1.0 with -Werror=format-overflow error

### ISSUE THREAD

**Issue by SRSaunders** [RobertBeckebans/RBDOOM-3-BFG#587]
I just updated my Manjaro install to the latest version including toolchains.  This update brings along gcc 11.1.0, which now causes the linux build to fail with a -Werror=format-overflow error.  Note that RBDoom-3-BFG's CMakeLists.txt is set up to declare build errors on -Wformat warnings.  The offending code is in doomclassic's d_english.h and m_menu.cpp, where variable-length string macros containing savegame names are being written by sprintf() to g->tempstring that is too short (80 characters).

It seems that gcc 11.1 is calculating the range of possible string lengths at build time, and determining that the destination g->tempstring in sprintf() is too short.  A quick fix is to change the tempstring length in vars.h to 128 characters (up from 80 chars).

Is anyone else seeing this issue?  I don't want to create a pull request for this until I know that others are experiencing the same problem.  Note that builds were working fine before I did the Manjaro update.

**Comment by coldtobi** [comment]
Yes, I was seeing that locally on Debian too (but due to the freeze I did not fix it yet)

Maybe the code should be switched to use s**n**printf()?

**Comment by SRSaunders** [comment]
Thanks coldtobi for confirming that gcc 11 seems to cause this build problem, and for the link to your previous issue.

I tried used snprintf() with a limit of 80, but the build still fails.  The error seems to be coming from the formatting aspects of the string macros, i.e. the variable length %s format specifier embedded in the string macros for inserting the savegame names.  I even tried adding a string length limiter in the format string (i.e. %.<len_limit>s) but this didn't work for me - perhaps I was doing something wrong or the gcc 11 error checking is aggressive and still persists since the savegame string length is greater than the format string.  In any case, I can think of a few ways to solve this:

1. Simply extend the g->tempstring size in vars.h from 80 to 128.  This is slightly larger than the max possible string length identified by gcc 11.  I am not sure if there are any side effects to this, but it works for me based on quick testing.
2. Change the setting in CMakeLists to prevent -Wformat warnings from being treated as errors.  This feels more like a band-aid and does not solve the core issue.  It may also prevent proper checking in other areas of the code.
3. Other ideas?

Robert - Have you tried building with gcc 11 on any other linux platforms?  Are you seeing this too?

**Comment by SRSaunders** [comment]
Should be fixed now.
