### ISSUE TITLE
Cmake check for X11_XCB seems broken

### ISSUE THREAD

**Issue by tomgreen66** [RobertBeckebans/RBDOOM-3-BFG#596]
In `CMakeLists.txt` there is a section that adds dependency for x11-xcb.

https://github.com/RobertBeckebans/RBDOOM-3-BFG/blob/d430f6a1fd5b1f6b3c4dd1e88e935d48be24fac5/neo/CMakeLists.txt#L426-L438

This should use variables as defined in the `FindX11_XCB.cmake` module within the `cmake` subdirectory.

https://github.com/RobertBeckebans/RBDOOM-3-BFG/blob/d430f6a1fd5b1f6b3c4dd1e88e935d48be24fac5/neo/cmake/FindX11_XCB.cmake

This module first tries to use `pkg-config` to find the required variables.  Then sets `X11_XCB_INCLUDE_DIR` and `X11_XCB_LIBRARIES` with found packages using the `pkg-config` as a hint.   A couple of problems:

1. The wrong variable is used in `CMakeLists.txt` where `X11_XCB_INCLUDE_DIRS` is used  (see above) when it should be `X11_XCB_INCLUDE_DIR`.
2. It is assumed for users of Mac with use homebrew with pkg-config available.  Xquartz is also a possibility where `PKG_X11_XCB_INCLUDE_DIRS` is unset.
3. The search path in `FindX11_XCB.cmake` only looks for one header `X11/Xlib-xcb.h` which for homebrew users on Mac is only found in one of the required include directories since all X11 packages are independent locations.  The fix implemented is to override in `CMakeLists.txt` with `PKG_X11_XCB_INCLUDE_DIRS` which hides the error in the module.  Maybe move the fix into the module - or make sure all files requires are listed.

Interesting during my testing there is a `X11/X.h` stored in a Mac Framework at `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Tk.framework/Headers/` which I dont think is picked up unless we use `X11/X.h` in find_path.

I tested the following which works but maybe makes the module messier (and would need testing on Linux)

tomgreen66@027ddba

Also tested the following which also worked - just not keen on all the fixes in `CMakeLists.txt` due to the module producing incorrect results.  Could move the logic into the module.

SRSaunders@8f7dbe1

**Comment by DanielGibson** [comment]
Why does RBDoom3BFG even call X11 directly? (does it?)
Shouldn't SDL do all the talking to X11?

**Comment by SRSaunders** [comment]
@DanielGibson - you have a great point.  However, there are a few lingering references to X11 for Vulkan builds that create build dependencies.  Do you know if these references are historical or for debugging reasons?  I must admit that I never looked at this when adding macOS Vulkan support - I just fulfilled the dependencies without determining if they were really necessary - bad on me.

I have found two files in particular:

1. posix_public.h contains an #include reference to <xcb/xcb.h> which looks like a forgotten hold-over providing types for a disabled posixInfo struct in the same file.  Seems like the #include can just be disabled.
2. References inside neo/renderer/Vulkan/qvk.h that respond to CMakeLists defines to control #includes for X11 and xcb (VK_USE_PLATFORM_XLIB_KHR and VK_USE_PLATFORM_XCB_KHR). 

I have tested on Linux & macOS by disabling find_package(X11_XCB) and ensuring  VK_USE_PLATFORM_XLIB_KHR and VK_USE_PLATFORM_XCB_KHR are not defined in CMakeLists, as well as disabling the #include in posix_public.h

RBDoom3BFG builds and runs properly on both Linux Manjaro and macOS without these references.  Just to make sure I uninstalled libx11 (and Xquartz) on macOS and it does not break anything.  Note that VK_USE_PLATFORM_WIN32_KHR is also present in qvk.h, but is absolutely required on the Windows side - it should not be disabled for Windows builds.

Before I submit a pull request for potential changes impacting Linux and macOS (posix_public.h and CMakeLists), can @DanielGibson and/or @tomgreen66 please comment on whether they know why these X11 references were in the code.

**Comment by tomgreen66** [comment]
All I can see is in the commit (message below) for XLIB (and previous use of xcb event handling where comment suggested wasnt sure it was needed:

```
qvk.h:
  * Since VK_USE_PLATFORM_* is defined in the CMakeLists.txt file, for
  now anyways, use them to wrap the correct platform headers instead of
  defining them here.
```

So it looks like it is purely to possibly use platform dependent Vulkan but as suggested SDL seems to handle most of that so it now looks redundant.  If those are undefined then `vulkan.h` just becomes `vulkan_core.h` from the documentation https://www.khronos.org/registry/vulkan/specs/1.2-khr-extensions/html/chap47.html#boilerplate-wsi-header

**Comment by SRSaunders** [comment]
Thanks very much for the pointers to the commit history and Vulkan docs.  It seems like the RBDoom3BFG Vulkan code was initially created with some platform-specific ideas - you can see this in `CreateSurface()` inside RenderBackend_VK.cpp.  `CreateSurface()` also responds to the VK_USE_PLATFORM_* variables, but a bit inconsistently.  The decision tree and the CMakeLists definitions are not well lined up.  For instance, VK_USE_PLATFORM_WIN32_KHR should be used vs. _WIN32.  Also `CreateSurface()` does not test for VK_USE_PLATFORM_XLIB_KHR which CMakeLists defines for UNIX platforms.  Instead it makes an untested assumption that VK_USE_PLATFORM_XCB_KHR is defined if linux (and macOS) are not.  It seems like the platform-specific code was only partially completed.

I could clean up a few things in RenderBackend_VK.cpp and posix_public.h before disabling X11 in CMakeLists, but is the clean-up worth it?  Is the RBDoom3BFG Vulkan code base meant to support X11 platforms directly (discounting linux and macOS since they are SDL2)?  Perhaps @RobertBeckebans could comment on his intent for the project's scope.

**Comment by SRSaunders** [comment]
I decided to submit pull request #600 with the specific changes I am proposing.  These are the minimum changes to remove X11_XCB dependencies for Linux and macOS, while retaining the Vulkan platform-specific code for X11 and reestablishing consistency between CMakeLists and the Vulkan code base.  Comments welcome.

**Comment by tomgreen66** [comment]
All seems to work using `cmake-xcode-opengl-release.sh` and `cmake-xcode-vulkan-release.sh` with 87bbeba.  One thing that caught me out - have updated to Big Sur (long process which resulted in having to do a fresh install) was you have to install Homebrew before installing Vulkan SDK.  Vulkan SDK places files in `/usr/local` which Homebrew doesn't like the permissions.  More of a homebrew issue but confused me for a bit.
