### ISSUE TITLE
Issues building on Mac due to openal-soft

### ISSUE THREAD

**Issue by gfelisberto** [RobertBeckebans/RBDOOM-3-BFG#602]
On Mac I had to edit the CMakeCache.txt to point to the location of the libs:
```
//Path to a file.
OPENAL_INCLUDE_DIR:PATH=/opt/homebrew/opt/openal-soft/include

//Path to a library.
OPENAL_LIBRARY:FILEPATH=/opt/homebrew/Cellar/openal-soft/1.21.1/lib/libopenal.dylib
```

During the installation of openal-soft I get the following info from homebrew:

```
==> Pouring openal-soft--1.21.1.arm64_big_sur.bottle.tar.gz
==> Caveats
openal-soft is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS provides OpenAL.framework.

If you need to have openal-soft first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/openal-soft/bin:$PATH"' >> ~/.zshrc

For compilers to find openal-soft you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/openal-soft/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/openal-soft/include"

For pkg-config to find openal-soft you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/openal-soft/lib/pkgconfig"

==> Summary
🍺  /opt/homebrew/Cellar/openal-soft/1.21.1: 27 files, 1MB
```

**Comment by SRSaunders** [comment]
See pending pull request #601 for README updates, CMakeLists.txt changes, and new universal binary cmake shell scripts for building on or for Apple Silicon.  Note for universal binary builds, I have added proposed documentation for using MacPorts vs. Homebrew.  Homebrew is easy to use and fine for single architecture builds (either x86_64 or arm64), but does not support universal binary libraries (and according to the moderators will never support them).  MacPorts supports universal binaries now and is the only choice other than building the required libs from source.

In the mean time if you want to build an arm64 single architecture binary on Apple Silicon, you should simply update your cmake shell script to specify the location of openal-soft on Apple Silicon machines.  **Do not manually change the CMakeCache.txt file**.  Here are the Homebrew openal-soft path changes for cmake-xcode-opengl-\<buildtype\>.sh:

```
-DOPENAL_LIBRARY=/opt/homebrew/opt/openal-soft/lib/libopenal.dylib
-DOPENAL_INCLUDE_DIR=/opt/homebrew/opt/openal-soft/include
```

**Comment by gfelisberto** [comment]
That fixes it thanks!!!
