### ISSUE TITLE
GUI rendering pass overwrites timestamps from 3D rendering

### ISSUE THREAD

**Issue by SRSaunders** [RobertBeckebans/RBDOOM-3-BFG#607]
In RenderBackend.cpp and RenderBackend_GL.cpp (stereo mode) GUI view rendering (RC_DRAW_VIEW_GUI) calls the same DrawView() used in 3D rending (RC_DRAW_VIEW_3D).  Since 3D rendering happens first for a given frame, the second call to DrawView() for GUI rendering overwrites timestamps from the first call.

This results in the stats for ShaderPass being incorrect in the detailed FPS overlay counter for com_showFPS modes 2 and 3.

This bug applies to OpenGL, Vulkan, and all platforms.  I have a fix which separates the GUI rendering pass which I will submit as a pull request.

**Comment by RobertBeckebans** [comment]
I just tested your branch and it seems to work. The entire frame time computations are a bit confusing and especially for com_smp > 0 however I would merge it that way.

![rbdoom-3-bfg-20210927-161902-002](https://user-images.githubusercontent.com/1278614/134930498-f73feb91-71d4-4305-acd6-abebeb98d997.png)
.

**Comment by SRSaunders** [comment]
Hi Robert - just arrived back from out of town and saw your note above.  Please hold off on the merge until later today.  There is a mistake in the frame time calculation and I now know how to fix and simplify which will make it much more intuitive.  I will send a pull request in a few hours from now.

**Comment by SRSaunders** [comment]
Thanks for merging the fix for timestamp overwrites, etc.

**Comment by RobertBeckebans** [comment]
Thanks for your work :) 👍
