### ISSUE TITLE
CPU timer scaling incorrect for Windows 64

### ISSUE THREAD

**Issue by SRSaunders** [RobertBeckebans/RBDOOM-3-BFG#608]
For Windows the CPU timer scaling shown in the FPS overlay counter for com_showFPS modes 2 and 3 can be incorrect.  For Windows 64 builds, the wrong scale factor is picked in Sys_ClockTicksPerSecond().  The fix is simple - for Win64 just make sure the same high resolution performance counter used by Sys_GetClockTicks() is also used by Sys_ClockTicksPerSecond().

I will submit a simple pull request for this.

**Comment by RobertBeckebans** [comment]
I thought all the time that there is something wrong with the CPU timers but my plan was to investigate it further when I implement better profiling with Remotery or Tracy.

**Comment by SRSaunders** [comment]
I am still testing my fixes on multiple platforms for #607 and this issue.  Will be away for a few days but should be able to submit Monday or Tuesday next week if that's okay.

**Comment by SRSaunders** [comment]
Thanks for merging the fix for Win64 cpu timer scaling, etc.
