### ISSUE TITLE
the application was unable to start correctly 0xc00007b

### ISSUE THREAD

**Issue by y2keeth** [RobertBeckebans/RBDOOM-3-BFG#609]
i build I get this now
the application was unable to start correctly 0xc00007b

**Comment by RobertBeckebans** [comment]
This error message doesn't tell me something I can work with. It sounds like a wrong DLL problem.

**Comment by y2keeth** [comment]
I build the exe from the current build when i try to launch it i get that error    On Friday, September 24, 2021, 06:41:07 AM EDT, Robert Beckebans ***@***.***> wrote:  
 
 


This error message doesn't tell me something I can work with. It sounds like a wrong DLL problem.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by RobertBeckebans** [comment]
WIP baked environment probes and lightgrid data for all BFG single player maps (4.2 GB download): https://drive.google.com/file/d/1wQEb93jV4FT-8KQlZrY3vY0CD-leI7kn/view?usp=sharing

**Comment by y2keeth** [comment]
btw you were right it was a dll problem
