### ISSUE TITLE
Nearest filtering

### ISSUE THREAD

**Issue by CPS2Evolved** [RobertBeckebans/RBDOOM-3-BFG#613]
Nearest filtering is present in most id Software games, I like the pixelated look, but can't seem to get it to work for RBDOOM. Does anyone have an idea?

I've tried:
set r_texturemode GL_NEAREST_MIPMAP_NEAREST
set r_texturemode "GL_NEAREST_MIPMAP_NEAREST"
set image_filter "GL_NEAREST_MIPMAP_NEAREST"

**Comment by AlfredOhNO** [comment]
Hey! I see this is marked as complete. Is the variable in the console in the latest stable release? If so, what is it?

**Comment by RobertBeckebans** [comment]
It's in the latest build in Discord for testers: https://drive.google.com/file/d/1M0HhGfkK1viQz3HktusFjaqNS8lALxDO/view?usp=drive_link

The console variable is image_pixelLook 1
