### ISSUE TITLE
Borderless windowed mode

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#615]

**Comment by MadDeCoDeR** [comment]
Doesn't that work with r_fullscreen -1? FYI if the width and height are the same as your monitor with OpenGL + Win7+ it will be enforced to exclusive fullscreen. One workaround is to add +1 on both the width and height in order to trick it.

**Comment by RobertBeckebans** [comment]
I haven't looked into this yet. The original issue was actually that it had a wrong scaling on 4k screens.
Thanks for the hint.
