### ISSUE TITLE
Request: Subtitles

### ISSUE THREAD

**Issue by ROCKNROLLKID** [RobertBeckebans/RBDOOM-3-BFG#617]
Not sure if it is possible, but would be nice to have subtitles in the game. Sometimes the music or background noise is loud so can be difficulty to fully understand what everyone is saying. Subtitles for what people say as well as the audio logs.

**Comment by tomgreen66** [comment]
I have been looking at this off and on for a while - I was using this as inspiration - https://www.moddb.com/mods/doom3cc/downloads/doom-3-closed-captions-doom-3-cc-v20-no-radar-version but there isn't much to go on source code wise.  This was a couple of year ago I started looking though.  Just spotted https://github.com/dhewm/dhewm3-sdk/issues/12 which looks well developed - might have another look.

**Comment by ROCKNROLLKID** [comment]
Classic RBDoom 3 did this using ccscript. https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/commit/2240357c678552d38282d91e17c05681bdf82fad

**Comment by MadDeCoDeR** [comment]
> Classic RBDoom 3 did this using ccscript. [MadDeCoDeR/Classic-RBDOOM-3-BFG@2240357](https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/commit/2240357c678552d38282d91e17c05681bdf82fad)

Keep in mind that ccscript still requires some adjustments (mainly for multilingual support)

**Comment by BielBdeLuna** [comment]
I guess this requires a modification of the flash files that hold the HUD or a double implementation for the subtitles separated of the HUD

**Comment by MadDeCoDeR** [comment]
> I guess this requires a modification of the flash files that hold the HUD or a second implementation just for the subtitles separated off the HUD

That's cute to think that you need to either edit the existing file or make a new one. You can always manipulate the swf file after is loaded to memory (aka it's memory copy)

**Comment by BielBdeLuna** [comment]
but isn't it more difficult? you could just have a method for displaying the text  over the HUD using the old full-screen GUI system, isn't this far more easier?

**Comment by MadDeCoDeR** [comment]
I wouldn't say it's more difficult. The HUD already has an unused element in Single Player, the respawn message which conveniently enough is on the center of your screen. The only thing you need to do is to move it and expand it. As for the full-screen GUI, I'm really not certain if that works any more. Yes, GUI on other objects is a thing but I am not certain how well it works on full-screen. Finally, the subtitle support on BFA is not just in theory, is already something that works.

P.S.: I'm leaving that commit here to show how I did that https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/commit/b9f582f5ce0d70b4b41d12791ccc24643a645bfb

**Comment by BielBdeLuna** [comment]
of course in case of opting for a full-screen GUI element for the subtitles it should have to be restored first from the vanilla version of the engine.

**Comment by MadDeCoDeR** [comment]
> of course in case of opting for a full-screen GUI element for the subtitles it should have to be restored first from the vanilla version of the engine.

That sounds alot more work than what I did. Just copy pasting won't gonna make it work right away.

**Comment by MadDeCoDeR** [comment]
I'm just leaving this here for anyone interested https://www.moddb.com/mods/classic-rbdoom-3-bfg-edition/addons/subtitle-sample

**Comment by IlDucci** [comment]
If someone actually wants to help developing the Doom3CC version, I am still interested in having someone work on it as the current maintainer (though I know nothing of programming).
