### ISSUE TITLE
linking of openAL in doom-classic is broken

### ISSUE THREAD

**Issue by Arbars** [RobertBeckebans/RBDOOM-3-BFG#623]
In process of linking building is failing:

ld: /usr/src/tmp/ccfgL6s6.ltrans115.ltrans.o: in function `I_StartSound2(int, int, mobj_t*, mobj_t*, int, int) [clone .part.0]':
/usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:344: undefined reference to `g'
ld: /usr/src/tmp/ccfgL6s6.ltrans115.ltrans.o: in function `I_UpdateSound() [clone .part.0]':
/usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:471: undefined reference to `g'
ld: /usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:478: undefined reference to `finecosine'
ld: /usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:483: undefined reference to `finesine'
ld: /usr/src/tmp/ccfgL6s6.ltrans115.ltrans.o: in function `getsfx(char const*, int*)':
/usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:173: undefined reference to `W_CheckNumForName(char const*)'
ld: /usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:176: undefined reference to `W_GetNumForName(char const*)'
ld: /usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:181: undefined reference to `W_LumpLength(int)'
ld: /usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:183: undefined reference to `W_CacheLumpNum(int, int)'
ld: /usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:196: undefined reference to `Z_Free(void*)'
ld: /usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:174: undefined reference to `W_GetNumForName(char const*)'
ld: /usr/src/tmp/ccfgL6s6.ltrans115.ltrans.o: in function `I_GetSfxLumpNum(sfxinfo_struct*)':
/usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:238: undefined reference to `W_GetNumForName(char const*)'
ld: /usr/src/tmp/ccfgL6s6.ltrans115.ltrans.o: in function `I_StartSound(int, mobj_t*, mobj_t*, int, int, int)':
/usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:376: undefined reference to `g'
ld: /usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:382: undefined reference to `PLAYERCOUNT'
ld: /usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:376: undefined reference to `DoomLib::GetPlayer()'
ld: /usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:386: undefined reference to `DoomLib::GetPlayer()'
ld: /usr/src/tmp/ccfgL6s6.ltrans115.ltrans.o: in function `I_ShutdownSound()':
/usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:551: undefined reference to `S_sfx'
ld: /usr/src/tmp/ccfgL6s6.ltrans115.ltrans.o: in function `I_InitSoundHardware(int, int)':
/usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:739: undefined reference to `Timidity_Init(int, int, int, int, char const*)'
ld: /usr/src/tmp/ccfgL6s6.ltrans115.ltrans.o: in function `I_InitSound()':
/usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:667: undefined reference to `S_sfx'
ld: /usr/src/tmp/ccfgL6s6.ltrans115.ltrans.o: in function `I_SubmitSound()':
/usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:704: undefined reference to `DoomLib::GetPlayer()'
ld: /usr/src/tmp/ccfgL6s6.ltrans115.ltrans.o: in function `I_InitMusic()':
/usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:739: undefined reference to `Timidity_Init(int, int, int, int, char const*)'
ld: /usr/src/tmp/ccfgL6s6.ltrans115.ltrans.o: in function `I_ShutdownMusic()':
/usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:780: undefined reference to `Timidity_Shutdown()'
ld: /usr/src/tmp/ccfgL6s6.ltrans115.ltrans.o: in function `I_LoadSong(char const*)':
/usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:807: undefined reference to `W_CacheLumpName(char const*, int)'
ld: /usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:810: undefined reference to `Mus2Midi(unsigned char*, unsigned char*, int*)'
ld: /usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:812: undefined reference to `Timidity_LoadSongMem(unsigned char*, unsigned long)'
ld: /usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:817: undefined reference to `Timidity_Start(_MidiSong*)'
ld: /usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:824: undefined reference to `Timidity_PlaySome(void*, int, int*)'
ld: /usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:828: undefined reference to `Timidity_Stop()'
ld: /usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:829: undefined reference to `Timidity_FreeSong(_MidiSong*)'
ld: /usr/src/tmp/ccfgL6s6.ltrans115.ltrans.o: in function `I_PlaySong(char const*, int)':
/usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:858: undefined reference to `DoomLib::GetPlayer()'
ld: /usr/src/tmp/ccfgL6s6.ltrans115.ltrans.o:/usr/src/RPM/BUILD/rbdoom3bfg-1.2.0/doomclassic/doom/i_sound_openal.cpp:859: undefined reference to `g'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/RBDoom3BFG.dir/build.make:7257: RBDoom3BFG] Error 1
make[2]: Leaving directory '/usr/src/RPM/BUILD/rbdoom3bfg-1.2.0'
make[1]: *** [CMakeFiles/Makefile2:107: CMakeFiles/RBDoom3BFG.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

Compiler: GCC11
SDL2: 2.0.9

**Comment by BielBdeLuna** [comment]
I confirm this issue
