### ISSUE TITLE
Shadow volume error ?

### ISSUE THREAD

**Issue by SEAGitUser** [RobertBeckebans/RBDOOM-3-BFG#625]
https://github.com/RobertBeckebans/RBDOOM-3-BFG/blob/d1d903866a072ade2ab77a415a28bb7b4ca2ac16/neo/idlib/geometry/RenderMatrix.cpp#L4081

I think there should be 'localLightOrigin' instead of 'localPoint' ?

**Comment by RobertBeckebans** [comment]
I'm not sure and the code isn't used anymore.
