### ISSUE TITLE
DOOM_CLASSIC cmake variable is OFF by default

### ISSUE THREAD

**Issue by SRSaunders** [RobertBeckebans/RBDOOM-3-BFG#627]
Should the DOOM_CLASSIC cmake variable be set ON by default?  I am wondering if the recent change to an OFF setting was an oversight when the new STANDALONE variable was defined.  Note that setting STANDALONE to ON will correctly turn DOOM_CLASSIC to OFF.  Is that the functionality that was intended, or is DOOM_CLASSIC truly meant to be off by default?

**Comment by RobertBeckebans** [comment]
Yeah STANDALONE is a helper option for people who want to make new games or total  conversions with RBDOOM-3-BFG.
So STANDALONE ON means DOOM_CLASSIC OFF. However the default should be DOOM_CLASSIC ON if its just the default game.
