### ISSUE TITLE
[NVRHI] scissors aren't properly implemented

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#651]
This leads to a number of irregular rendering bugs especially of the SWF UI.

**Comment by stephenap07** [comment]
I don't think scissor-rects are considered a state change at the moment. We could record the last submitted scissor-rect and then resubmit the graphics state with the new scissor after it changes.

**Comment by RobertBeckebans** [comment]
I can't get it to work. Maybe it has something to do with the with the flipped Y axis.
