### ISSUE TITLE
[NVRHI] Cmake shader compile error about including files while compiling through dxc and cmd works

### ISSUE THREAD

**Issue by CodeLikeCXK** [RobertBeckebans/RBDOOM-3-BFG#654]
Two typical situation:

[build]   [ 36.4%] DXIL FAIL  builtin/post/SMAA_blending_weight_calc.vs.hlsl: 
[build]   ERRORS for builtin/post/SMAA_blending_weight_calc.vs.hlsl: : 
[build]   C:\RBDOOM-3-BFG\neo\shaders\builtin\post\SMAA_blending_weight_calc.vs.hlsl:36:10: fatal error: 'SMAA.inc.hlsl' file not found
[build]   #include "SMAA.inc.hlsl"

[build]   [ 44.5%] DXIL FAIL  builtin/lighting/interactionSM.ps.hlsl: USE_GPU_SKINNING=1 LIGHT_POINT=1 LIGHT_PARALLEL=0 USE_PBR=1 USE_NORMAL_FMT_RGB8=1 
[build]   ERRORS for builtin/lighting/interactionSM.ps.hlsl: USE_GPU_SKINNING=1 LIGHT_POINT=1 LIGHT_PARALLEL=0 USE_PBR=1 USE_NORMAL_FMT_RGB8=1 : 
[build]   C:\RBDOOM-3-BFG\neo\shaders\builtin\lighting\interactionSM.ps.hlsl:32:10: fatal error: 'BRDF.inc.hlsl' file not found
[build]   #include "BRDF.inc.hlsl"

**Comment by RobertBeckebans** [comment]
Did you try to update CMake?

**Comment by CodeLikeCXK** [comment]
> Did you try to update CMake?

Just updated and the problem is still here

**Comment by CodeLikeCXK** [comment]
The problem is fixed. It's a UTF-8 error. Convert related shader files to UTF-8 BOM encoding and it works.
https://github.com/microsoft/DirectXShaderCompiler/issues/3204

**Comment by RobertBeckebans** [comment]
Oh good that you could find the problem.
