### ISSUE TITLE
minImageCount used on vkCreateSwapChain too small for Linux under x11/wayland with mesa drivers

### ISSUE THREAD

**Issue by infapi00** [RobertBeckebans/RBDOOM-3-BFG#658]
RBDOOM-3-BFG uses NUM_FRAME_DATA, defined at precompiled.h, as the minImageCount when calling vkCreateSwapChain. On linux the value is 2.

But for Mesa drivers the minImageCount returned by vkGetPhysicalDeviceSurfaceCapabilities for x11 and wayland is greater that that, 3 and 4 respectivelly. This raises the following vulkan validation layer error:

`      VUID-VkSwapchainCreateInfoKHR-minImageCount-01271(ERROR / SPEC): msgNum: -511412493 - Validation Error: [ VUID-VkSwapchainCreateInfoKHR-minImageCount-01271 ] Object 0: handle = 0x564ea062b030, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xe18476f3 | vkCreateSwapchainKHR() called with minImageCount = 2, which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR() (i.e. minImageCount = 3, maxImageCount = 0). The Vulkan spec states: minImageCount must be greater than or equal to the value returned in the minImageCount member of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://github.com/KhronosGroup/Vulkan-Docs/search?q=)VUID-VkSwapchainCreateInfoKHR-minImageCount-01271)`

although fwiw, the application works fine even with that warning.

The options that I see here to avoid the error are:
* Make NUM_FRAME_DATA a dynamic value that comes from checking first the value returned by vkGetPhysicalDeviceSurfaceCapabilities. I have briefly checked the code and this doesn't seems a small change at all, as it is assumed to be a constant.
* Increase the value for linux, in the same way that it is increased to 3 for apple. I have a wip branch with that solution here [1]. The problem with that is that ideally we would like 3 for x11, and 4 for wayland, and I didn't any definition for each one, so we would need to increase it to 4.
* Add a driconf exception for RB-DOOM3BFG: mesa includes a procedure to add exception to some specific applications. There is already a way to specify the minImageCount for apps, so it would be just about including an exception for RBDOOM-3-BFG. Will create an issue soon on Mesa to show what that means.

Final comment: I found this issue but not with the app directly. I work for the mesa v3dv driver (Broadcom, for the rpi4), and we use some gfxreconstruct traces to check if there are performance differences after some change on the driver. gfxreconstruct on debug build just raises an assert (so crashes) due this. On release builds it works fine though. The last option mentioned (driconf exception) would not fix the assertion on debug builds.

[1] https://github.com/infapi00/RBDOOM-3-BFG/tree/wip/apinheiro/vulkan-minImageCount-validation-error

**Comment by infapi00** [comment]
> Will create an issue soon on Mesa to show what that means.

Just created:
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/16001

**Comment by SRSaunders** [comment]
I can confirm this issue as well.  See my final comments in merged pull request #633 - regarding remaining validation errors (ref comment 1).  As you say above, this issue could be fixed by increasing NUM_FRAME_DATA to 3 for linux but needs additional testing across a range of distros.  The Wayland issue is interesting as the game only knows about SDL and not the underlying windowing system.  However, you might be able to use something like `SDL_SetHint(SDL_HINT_VIDEODRIVER, "x11,wayland")` (or vice versa) before `SDL_Init()` to force alignment of the underlying windowing system with the value of NUM_FRAME_DATA.

**Comment by infapi00** [comment]
> I can confirm this issue as well. See my final comments in merged pull request https://github.com/RobertBeckebans/RBDOOM-3-BFG/pull/633 - regarding remaining validation errors (ref comment 1)

Just read it. It is a pity that I was correct on my conclusion that making NUM_FRAME_DATA dynamic was not trivial (I was still hoping to be wrong).

About testing, FWIW, I manually set NUM_FRAME_DATA to 3, and things seemed to work, although I didn't do a extensive testing.

> The Wayland issue is interesting 

FWIW, I didn't test the game under Wayland. I just found what would be the minImageCount on that scenario checking the Mesa code.

> However, you might be able to use something like SDL_SetHint(SDL_HINT_VIDEODRIVER, "x11,wayland") (or vice versa) before calling SDL_Init() to force alignment of the underlying windowing system with the value of NUM_FRAME_DATA.

Well, but if I understand it properly, this is just a hint that sets a preference, and not a way to ensure that we get an x11 environment, right? 

In any case, as I mentioned, I didn't test myself on Wayland. So perhaps we are just trying to fix an issue too much in advance. 

Taking into account that at #633 you mentioned that in the long term the proper fix would be to have  a dynamic NUM_FRAME_DATA, perhaps a reasonable plan would be : 
* Short term: increase NUM_FRAME_DATA to 3 on Linux too (assuming testing showed everything is correct), don't do anything for Wayland yet.
* Long term: NUM_FRAME_DATA dynamic, respecting the minImageCount requirement returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR()

**Comment by infapi00** [comment]
> Yes, the short term NUM_FRAME_DATA = 3 solution for linux Vulkan should be fine as long as sufficient testing can be done across a set of important distros. As you saw from my pull request comments, I was hesitant to make this change by myself without input from daily linux users. Is this something you could do?

Will try to do it this weekend, assuming that for sufficient testing you mean doing some quick testing on some levels, and do some real playing for some time (line an hour?). Do you have some specific testing in mind?

> However, Robert is currently porting the back end to the NVRHI abstraction layer (for DirectX and Vulkan) and I am not sure how this change might interact with that. I suppose you could push the change and let Robert decide what he wants to do with the legacy Vulkan back end. That is what I have done with a few other pending Vulkan fixes.

Ok.

**Comment by SRSaunders** [comment]
Regarding testing, I suggest you test on a few popular distros, e.g. Debian, Ubuntu or Kubuntu (I know Robert uses this one), etc. to pick up differences in the windowing environment (i.e. X11 plus window managers like Gnome, KDE, XFCE, ...).  I have tested NUM_FRAME_DATA = 3 on Manjaro/XFCE and it seems to work fine there.  Perhaps Robert or others could indicate which distros are important to test from their perspective.

**Comment by RobertBeckebans** [comment]
The old Vulkan backend has been deprecated.

**Comment by infapi00** [comment]
Hi sorry, in the end I was too busy to extend my testing beyond Raspbian, that was the one I was using for testing this port.

> The old Vulkan backend has been deprecated.

I understand that it got deprecated NVRHI. Skimming it also seems that now there are more advanced rendering. So probably this means that it would be somewhat harder to get this working on the rpi4 (where even before we were getting ~11fps). In any case, will write down on my TODO to try the newer port with rpi4.

And again thanks for welcoming some of my patches, even when coming for a platform that was barely running this port. FWIW, even if not really playable, we were able to use this port to test the driver and go into some improvements:

https://blogs.igalia.com/apinheiro/2021/03/improving-v3dv-pipeline-caching/
