### ISSUE TITLE
[NVRHI] Memory leak in Framebuffer::ResizeFramebuffers()

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#664]
Especially reloading the Framebuffer render target images which switching between MSAA and non-MSAA caused severe memory problems up until the need to restart Windows.

**Comment by stephenap07** [comment]
I noticed this leak every time I do a `vid_restart`. This seemed to have fixed it:
```c++
Framebuffer::~Framebuffer()
{
	apiObject.Reset();
}
```
It might be due to some other object that has not released its shared ownership over the Framebuffer. I did not look too much into it.
