### ISSUE TITLE
no strings

### ISSUE THREAD

**Issue by cll00** [RobertBeckebans/RBDOOM-3-BFG#666]
Hi...

donwload game form steam and  install lastest version of rbdoom and i have problem whith strings ...

please heeelp!!!

![Esta es una imagen](https://camo.githubusercontent.com/c9fb7bafdbef3613d07ba1b759c901ad5f79051ca5d429b4f355d4c1606fe4cf/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f333436333639352f3132313930362f34353362393664382d366530652d313165322d396162332d3337613834373930373537322e706e67)

**Comment by RobertBeckebans** [comment]
You installation is probably broken and you haven't installed the loca packages.

**Comment by RobertBeckebans** [comment]
Maybe sys_lang is set to "" or "english" and your installation is in another language.
You can fix that with e.g. a shortcut to the .exe and add +set sys_lang "german" if it's German.

Supported languages are:
#define ID_LANG_ENGLISH		"english"
#define ID_LANG_FRENCH		"french"
#define ID_LANG_ITALIAN		"italian"
#define ID_LANG_GERMAN		"german"
#define ID_LANG_SPANISH		"spanish"
#define ID_LANG_JAPANESE	"japanese"

**Comment by cll00** [comment]
thanks!!!!
