### ISSUE TITLE
Failed to compile with gcc 12

### ISSUE THREAD

**Issue by runlevel5** [RobertBeckebans/RBDOOM-3-BFG#672]
With GCC 12, the `-Werror=format-overflow=` has caused few errors with `sprintf()`:

```
/home/tle/RBDOOM-3-BFG/doomclassic/doom/hu_stuff.cpp:330:39: error: ‘%.3d’ directive writing between 3 and 11 bytes into a region of size 4 [-Werror=format-overflow=]
  330 |                 sprintf(buffer, "STCFN%.3d", j++);
      |                                       ^~~~
```

```
/home/tle/RBDOOM-3-BFG/doomclassic/doom/f_finale.cpp:769:23: error: ‘%i’ directive writing between 1 and 10 bytes into a region of size 7 [-Werror=format-overflow=]
  769 |     sprintf (name,"END%i",stage);
      | 
```

So the compiler suspects string concatenation might overflow buffer. This is false positive since we are positive it does not. We either disable the Format Overflow warnings or just guard them against unintended memory write

**Comment by coldtobi** [comment]
snprintf() ?

**Comment by runlevel5** [comment]
@coldtobi what about `snprintf()`?

**Comment by coldtobi** [comment]
Just meant as an idea to use snprintf instead. e.g `snprintf(buffer, sizefod(buffer), "STCFN%.3d", j++);`

**Comment by auledoom1** [comment]
> Just meant as an idea to use snprintf instead. e.g `snprintf(buffer, sizefof(buffer), "STCFN%.3d", j++);`
> 

Using snprint does not solve compiler warnings, changing the buffer size to suggested values allows me to compile on Arch linux
