### ISSUE TITLE
[NVRHI] Failed to grow a descriptor heap!

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#676]
I think this is cause for the sudden freezes and crashes after playing 1-2 single player maps.

However for some unknown reason it isn't captured to the qconsole.log and the console window with the error message doesn't show up in the release build.

![2022-06-01 10_21_50-DOOM 3_ BFG Edition](https://user-images.githubusercontent.com/1278614/171370767-8723125b-97ea-4a28-a605-ae6e2d53719a.jpg)

![2022-06-01 11_03_15-RBDoom3BFG (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/1278614/171370788-d5ba65b6-01b6-4800-ae21-dc675d1aa922.jpg)

**Comment by y2keeth** [comment]
could this be my problem?
