### ISSUE TITLE
[glTF2] bgltf checks fail for skeletal models

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#704]
@HarrievG

model character_mcneil
{
	mesh						models/characters/mcneil/mcneil.doom_skel.glb
}
The model path is models/characters/mcneil/mcneil.glb. 
After loading it saves the cached model to 
generated\rendermodels\models\characters\mcneil\mcneil.doom_skel.bglb.
When loading a second time the check for changes in the source .glb fails because it checks for mcneil.doom_skel.glb instead of mcneil.glb resulting in a sourceTimestamp == -1.

**Comment by HarrievG** [comment]
Can be assigned to me. Should be a straight forward fix
