### ISSUE TITLE
Compile error in "f_finale.cpp:887:39: error:" with GCC 12

### ISSUE THREAD

**Issue by xcom169** [RobertBeckebans/RBDOOM-3-BFG#706]
Hello All!

I'm trying the compile the master branch in Arch Linux , however I get this error: 

<code>
[ 82%] Building CXX object CMakeFiles/RBDoom3BFG.dir/home/csabesz/Documents/RBDOOM-3-BFG/doomclassic/doom/f_finale.cpp.o
/home/csabesz/Documents/RBDOOM-3-BFG/doomclassic/doom/f_finale.cpp: In function ‘void F_BunnyScroll()’:
/home/csabesz/Documents/RBDOOM-3-BFG/doomclassic/doom/f_finale.cpp:887:39: error: ‘%i’ directive output may be truncated writing between 1 and 10 bytes into a region of size 7 [-Werror=format-truncation=]
  887 |         snprintf( name, name_len, "END%i", stage );
      |                                       ^~
/home/csabesz/Documents/RBDOOM-3-BFG/doomclassic/doom/f_finale.cpp:887:35: note: directive argument in the range [-429496729, 6]
  887 |         snprintf( name, name_len, "END%i", stage );
      |                                   ^~~~~~~
/home/csabesz/Documents/RBDOOM-3-BFG/doomclassic/doom/f_finale.cpp:887:17: note: ‘snprintf’ output between 5 and 14 bytes into a destination of size 10
  887 |         snprintf( name, name_len, "END%i", stage );
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
make[2]: *** [CMakeFiles/RBDoom3BFG.dir/build.make:6334: CMakeFiles/RBDoom3BFG.dir/home/csabesz/Documents/RBDOOM-3-BFG/doomclassic/doom/f_finale.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:159: CMakeFiles/RBDoom3BFG.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

</code>

**Comment by RobertBeckebans** [comment]
GCC breaks the build every few months. I recommend to compile the project with clang.

**Comment by xcom169** [comment]
Yes. 
<code>
export CC=clang
export CXX=clang++
</code>

Did the trick.
