### ISSUE TITLE
[NVRHI] SSAO does not work with Vulkan

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#710]
Calling MipMapGenPass::Dispatch will lead to a crash.

**Comment by SRSaunders** [comment]
I now have the new NVRHI compute shader SSAO code working with Vulkan on macOS.  Should also work on linux and with DX12 on windows but haven't tested it yet.  Finished the implementation of `DrawScreenSpaceAmbientOcclusion2()`, changed the AO image to be generated as res native linear with the UAV attribute set, and fixed the blur compute shader to write back to the image.  I will do some cross platform testing over the next few days to make sure it works cross platform.

Assuming it checks out, are you interested in a pull request with this change?

**Comment by RobertBeckebans** [comment]
I'm definitely interested in the SSAO alternative. Fixing AO is crucial for
the upcoming release because otherwise the prebaked GI data is too bright.
There was still something wrong with the current implementation as it
looked like normals were ignored. The old code is based on an outdated
paper from 2014 so the new code should look good. I might tweak it further
to output the least occlusion direction as normal so we can use bent
normals during the GI lookup but that will be another ticket. Do my last
changes still work on macOS? I cleaned up the CMakeLists.txt a bit. I still
need to rename USE_NVRHI_VULKAN to USE_VULKAN. Unfortunately it still shuts
down after getting into the main menu for a few frames using Nvidia's
driver on Linux. I made another ticket for that.

SRSaunders ***@***.***> schrieb am Sa., 26. Nov. 2022, 05:21:

**Comment by SRSaunders** [comment]
Good news re your CMakeLists.txt changes - still works fine on macOS.  However, I have a pending pull request for your nvrhi fork (AppleClang fix for shaderCompiler CMakeLists.txt) that is still not merged and blocks the build for macOS.  See https://github.com/RobertBeckebans/nvrhi/pull/2.  Perhaps you could review and merge.

Unfortunately I was a little too quick in declaring success for the new SSAO work.  It was using the default AO image and not the new compute shader output.  I need to do a bit more investigation to figure out what is happening and why the compute shader output is blank.

**Comment by SRSaunders** [comment]
I am planning to have another look at SSAO soon, but I did find one error via code inspection and comparing to the donut examples.  In **SsaoPass.cpp**, the following code:

```
	ssaoConstants.clipToView = idVec2(
		viewDef->projectionMatrix[2 * 4 + 3] / viewDef->projectionMatrix[0 * 4 + 0],
		viewDef->projectionMatrix[2 * 4 + 3] / viewDef->projectionMatrix[0 * 4 + 1] );
```
should probably be:

```
	ssaoConstants.clipToView = idVec2(
		viewDef->projectionMatrix[2 * 4 + 3] / viewDef->projectionMatrix[0 * 4 + 0],
		viewDef->projectionMatrix[2 * 4 + 3] / viewDef->projectionMatrix[1 * 4 + 1] );
```

**Comment by SRSaunders** [comment]
Hi Robert - I have a test branch with both the legacy and new SSAO shaders working for Vulkan.  I was able to fix the HiZ **mipmapgen.cs.hlsl** compute shader for the legacy stuff (strange binding problem for UAV arrays - but with simple solution in the end), and I wired up an implementation for the new Donut SSAO compute shader.  You can turn on SSAO via the UI or using `r_useSSAO = 1`.  You can dynamically toggle between old and new by using `r_useNewSSAOPass = 0/1`.

A few issues/limitations:

1. The legacy implementation is very subtle - I had to double the intensity setting in the **AmbientOcclusion_AO.ps.hlsl** shader to really notice any difference:  `static const float intensity = 0.6 * 2.0;`. This is not done in my branch, but only in my local copy.  FYI in case you want to fiddle with it yourself.
2. Both new and old shaders seem to be very distance sensitive for the AO effect. More noticeable at distance and less so as you get closer.  Perhaps this is just the way the algorithms are supposed to work.  However, I am left wondering whether the legacy `DOOM_TO_METERS = 0.0254;` setting is correct for NVRHI.  Could something have changed in the calibration with the new back end?  Note this setting is used all around the code, even in the sound system.
3. The legacy option of `r_ssaoFiltering` does not work and crashes both for DX12 and Vulkan.  I tried to fix it for Vulkan but can't seem get past an extra descriptor set binding problem with the **AmbientOcclusion_blur.ps.hlsl** shader.  I may try again to solve tomorrow, but not sure if this is important to you or not.

If you want to try it out, see https://github.com/SRSaunders/RBDOOM-3-BFG/tree/ssao-testing

**Comment by RobertBeckebans** [comment]
Thank you, I'm going to try to review the changes this week.
I had all kinds of problems with the blur passes in the old shader so I usually disabled them. The old implementation is by McGuire from 2014 and usually pretty outdated although it was cool that it supported normalmaps. I still have to look how it compares to the Donut sample however I expect that the sample uses the latest research and should be better in general.
