### ISSUE TITLE
[NVRHI] renderprogs Buffer Problem with Vulkan

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#712]
We really need to fix this:
<pre>in void idRenderProgManager::Init( nvrhi::IDevice* device )

        if( deviceManager->GetGraphicsAPI() == nvrhi::GraphicsAPI::VULKAN )
	{
		// RB: FIXME this is ugly - DOUBLECHECK this
		constantBuffer = device->createBuffer(
							 nvrhi::utils::CreateVolatileConstantBufferDesc( uniforms.Allocated(),
									 "RenderParams", 1024 ) );
	}
	else
	{
		constantBuffer = device->createBuffer(
							 nvrhi::utils::CreateVolatileConstantBufferDesc( uniforms.Allocated(),
									 "RenderParams",
									 c_MaxRenderPassConstantBufferVersions ) );
	}</pre>

Loading a map and moving around results into this error:
Volatile constant buffer RenderParams has maxVersions = 1024, which is insufficient.

**Comment by SRSaunders** [comment]
This is indeed nasty.  I have looked around the code and don't see an obvious logic problem.  I believe the issue is related to performance, i.e. how fast volatile buffer version slots are cleared and can be reused.  The problem is made less severe when r_useValidationLayers and Metal API checking (on macOS) are disabled.  I can make the game run indefinitely on macOS (with my AMD 6600XT graphics card) if I boost the maxVersions to 4096.

**Comment by RobertBeckebans** [comment]
I asked the NVRHI maintainer for this issue:

> AlexP any hint on that issue?
I can boot into the main menu
Bild
basic room rendering without SSAO works too
Bild
however there are tons of Vulkan validation errors
AlexP
 — 
25.10.2022
If that constant buffer is used in every draw call and gets overwritten every time, that error makes sense
in this case, you need as many versions as there are draw calls. The error only happens on Vk because the DX12 backend doesn't need the version limit
but it's better to have one CB that is infrequently updated and then put any per-draw constants into push constants
Takeshi Kovacs
 — 
25.10.2022
yeah it's updated for every draw call
I also tried to just treat it as push constants but the buffer is way too big
right now it works almost the same as the vkDoom3 backend
AlexP
 — 
25.10.2022
can you split the buffer into a common part and a per-draw part?
Takeshi Kovacs
 — 
25.10.2022
https://github.com/RobertBeckebans/RBDOOM-3-BFG/blob/b12379e1af5089245f381d955f1da8ed9878b845/neo/renderer/RenderProgs.h#L73
it is that collection of float4 parms
difficult

AlexP
 — 
25.10.2022
ok then... use a ton of versions, I suppose
Takeshi Kovacs
 — 
25.10.2022
and that's ok?
AlexP
 — 
25.10.2022
I need to check the implementation, but I think that's fine
yeah that should be OK. There's a linear cost wrt the number of versions actually used in a few places, but not the max version count - that only affects the buffer size
still, take a look with a profiler
