### ISSUE TITLE
[Vulkan] Validation Error fillModeNonSolid feature is not enabled

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#713]
[Vulkan] ERROR location=0xfffffffff35c5127 code=0, layerPrefix='Validation'] Validation Error: [ VUID-VkPipelineRasterizationStateCreateInfo-polygonMode-01413 ] Object 0: handle = 0x249b4c46690, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xf35c5127 | vkCreateGraphicsPipelines parameter, VkPolygonMode pCreateInfos[0]->pRasterizationState->polygonMode cannot be VK_POLYGON_MODE_POINT or VK_POLYGON_MODE_LINE if VkPhysicalDeviceFeatures->fillModeNonSolid is false. The Vulkan spec states: If the fillModeNonSolid feature is not enabled, polygonMode must be VK_POLYGON_MODE_FILL (https://vulkan.lunarg.com/doc/view/1.3.224.1/windows/1.3-extensions/vkspec.html#VUID-VkPipelineRasterizationStateCreateInfo-polygonMode-01413)

**Comment by SRSaunders** [comment]
Pretty easy solution for this one:  add `.setFillModeNonSolid( true )` to deviceFeatures in DeviceManager_VK.cpp

I have this included in a pending pull request.
