### ISSUE TITLE
[Vulkan] Validation Error vkCmdPipelineBarrier(): .srcStageMask must not be 0 unless synchronization2 is enabled

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#715]
[Vulkan] ERROR location=0xffffffff80883de8 code=0, layerPrefix='Validation'] Validation Error: [ VUID-vkCmdPipelineBarrier-srcStageMask-03937 ] Object 0: handle = 0x249bd8a8530, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x80883de8 | vkCmdPipelineBarrier(): .srcStageMask must not be 0 unless synchronization2 is enabled. The Vulkan spec states: If the synchronization2 feature is not enabled, pname:srcStageMask must not be 0 (https://vulkan.lunarg.com/doc/view/1.3.224.1/windows/1.3-extensions/vkspec.html#VUID-vkCmdPipelineBarrier-srcStageMask-03937)

**Comment by SRSaunders** [comment]
Investigated this one and there are two possible solutions:
1. Enable the synchronization2 feature.  Depending on platform and availability of `VK_KHR_SYNCHRONIZATION_2`, this may require enabling the `VK_LAYER_KHRONOS_synchronization2` layer (for instance - needed with MoltenVK).  Need to check on linux and Windows - TBD.
2. Modify NVRHI in `vulkan-state-tracking.cpp` to eliminate placing a pipeline barrier in situations where an image barrier/texture barrier has beforeState = Unknown.

I have tried both solutions on macOS and they both work, but need to test on multiple platforms for compatibility.  However, I am nervous about option 2 as I don't want to touch NVRHI unless I really understand the implications.  Perhaps there is a way to eliminate this case in the game code, i.e. outside of NVRHI.
