### ISSUE TITLE
Unable to compile latest Vulkan build on Switchroot Ubuntu 18.04.6 ("‘VK_KHR_DRIVER_PROPERTIES_EXTENSION_NAME’ was not declared" etc)

### ISSUE THREAD

**Issue by Danfun64** [RobertBeckebans/RBDOOM-3-BFG#716]
I have recently attempted compiling the latest build to run on my Nintendo Switch (which of course is based on the Nvidia Tegra X1 ARM64 chip) using the latest provided version of Ubuntu on Switchroot's website (18.04.6) .

Compile log can be found at https://paste.debian.net/1258629

**Comment by SRSaunders** [comment]
What version of Vulkan SDK are you using to compile against?  `VK_KHR_DRIVER_PROPERTIES_EXTENSION_NAME` has been defined in vulkan_core.h for quite a while (at least since 2020, likely earlier).  This area of the code is optional and could be guarded by `#if defined(VK_KHR_driver_properties)` and would be easy to do, but I never thought that would be necessary.  Can you try using a recent SDK build?

**Comment by Danfun64** [comment]
The libvulkan-dev version installed is 1.1.70+dfsg1-1ubuntu0.18.04.1. If the version is too old, I'm not sure whether it would be better to backport from a newer version of Ubuntu or compile straight from the source... or if I need to also backport/compile a newer version Mesa and/or the Linux Kernel.

**Comment by mrcmunir** [comment]
> The libvulkan-dev version installed is 1.1.70+dfsg1-1ubuntu0.18.04.1. If the version is too old, I'm not sure whether it would be better to backport from a newer version of Ubuntu or compile straight from the source... or if I need to also backport/compile a newer version of Mesa ~and/or the Linux Kernel~.
> 
> Edit: So backporting the kernel isn't really possible. The Switchroot devs are stuck on 4.9.x for now because of NVidia. Never mind about that.

You tried with update Vulkan headers? 

```
git clone https://github.com/KhronosGroup/Vulkan-Headers
cd Vulkan-Headers
cmake . 
sudo make install 
```

**Comment by RobertBeckebans** [comment]
The old Vulkan backend has been deprecated. Please try the new NVRHI one with DXC as SPIR-V compiler.
