### ISSUE TITLE
[Vulkan] SDL platforms (linux, macOS) won't run if r_useStateCaching = 1

### ISSUE THREAD

**Issue by SRSaunders** [RobertBeckebans/RBDOOM-3-BFG#720]
Have to set r_useStateCaching = 0 on SDL platforms (linux, macOS) to get beyond game selection screen and enter a game type (Doom3 or Classic).  Also need r_useStateCaching = 0 to support com_showFPS = 2 on game selection screen.

Otherwise issue #714 arises and application crashes on SDL platforms.

**Comment by RobertBeckebans** [comment]
That is a good catch. r_useStateCaching is a port of the OpenGL backend but it might be the case that we can just skip it. I need to look further into this but this is a good tip. 👍
