### ISSUE TITLE
[Vulkan] maxMemoryAllocationCount limit hit on Windows for AMD cards

### ISSUE THREAD

**Issue by SRSaunders** [RobertBeckebans/RBDOOM-3-BFG#724]
[Vulkan] ERROR location=0x4e9256cc code=0, layerPrefix='Validation'] Validation Error: [ VUID-vkAllocateMemory-maxMemoryAllocationCount-04101 ] Object 0: handle = 0x1b21eab0200, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x4e9256cc | vkAllocateMemory: Number of currently valid memory objects is not less than the maximum allowed (4096). The Vulkan spec states: There must be less than VkPhysicalDeviceLimits::maxMemoryAllocationCount device memory allocations currently allocated on the device (https://vulkan.lunarg.com/doc/view/1.3.231.1/windows/1.3-extensions/vkspec.html#VUID-vkAllocateMemory-maxMemoryAllocationCount-04101)
Assertion failed!

This is potentially a difficult issue for Windows Vulkan on AMD cards.  My 6600XT has a maxMemoryAllocationCount limit of 4096 on Windows, but no such limit on Linux and macOS.  The game runs well using Vulkan on Linux and macOS, but I can't proceed on Windows due to this limit.  This is a blocking failure mode with an in-game assert.

**Comment by SRSaunders** [comment]
There are two problems here:
1. The number of texture (image) allocations for any given level exceeds the Vulkan device/driver limits on Windows for AMD cards.  In my case that means > 4096 image allocations.
2. The number of buffer object allocations is around 1600 after a level load, and grows by that amount again after each successive level load.  This results in many thousands of buffer allocations that can easily exceed Vulkan device limits for AMD cards on Windows.

The first problem is due to the NVRHI bundled Vulkan allocator.  It does not attempt any allocation management and assumes the driver will take care of it.  This may be ok for Nvidia cards and drivers, but is not ok for AMD, at least on Windows.  Linux and macOS appear to be a bit more lax about this but it is a bad assumption nonetheless.

Initially I thought the second problem was due to the same issue as above for rendering buffer objects (vertex, index, uniform buffers), but the real issue turned out to be excessive allocation of small Vulkan staging buffers by NVRHI.

I have solutions ready for both of these issues:
1. I have integrated AMD's GPUOpen VMA allocator library (https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator) using a side-by-side approach with NVRHI's allocator, but well integrated into the Texture and Buffer object framework of NVRHI.  Fortunately NVRHI has a few key library calls that allow you to wrap native image and buffer objects as ref counted NVRHI ITextures and IBuffers.  However, you are still responsible for manually managing the life cycle of the underlying native objects.  Fortunately this is possible for images and rendering buffers using VMA, and that is all you really need to solve the first problem.  Other buffer types (e.g. constant buffers, etc) can be left alone as native NVRHI objects will full lifecycle control.  There are many fewer of these object types and the NVRHI native vulkan allocator can handle those side-by-side to the VMA allocator without exceeding device limits.
2. The second problem is easier to solve and simply involves increasing the size of the NVRHI staging buffers.  This is accomplished when creating command lists by using a parameter setting `setUploadChunkSize`.  There is a new cvar setting to control the size, which is now set to a default of 64 MB (vs. NVRHI's 64 KB default).

The result of these two changes allows the game to run with the Vulkan renderer on Windows with AMD cards.  The changes are fully compatible with linux and macOS.

FYI - I briefly though about taking a different approach for VMA integration by wiring it in underneath NVRHI's vulkan allocator, but ran into problems with that approach - both with code structuring and stateless vs. stateful behaviour.   What I have done requires no changes to NVRHI, although I have an optional NVRHI enhancement that enables debug naming of wrapped native objects for use in tools like RenderDoc.  I could push this as an optional change later.

If you are interested in these fixes, I could prepare a PR.  Let me know.

**Comment by RobertBeckebans** [comment]
Sure that sounds great. 
VMA was already used in the Vulkan backend and if we can improve the compatibility with AMD then that's cool. 
I expected NVRHI to do the memory management on its own and if it doesn't manage it like VMA then it's a serious design flaw.
I haven't looked deeply into NVRHI concerning that issue.

Wasn't the size for staging buffers also 64 MB in the vkDoom 3 backend? I also wouldn't mind if VMA was integrated into NVRHI although it might cause trouble when doing pull requests into Nvidia's NVRHI repo.

DX12 is the prefered backend on Windows as it is also faster than Vulkan with Nvidia cards at the moment. However AMD + Vulkan on Windows is something that should just work if someone wants to use it.

I'm looking forward to your pull request.

**Comment by SRSaunders** [comment]
Thanks Robert.  Pull request now submitted.  I had to test on all platforms and fix some VMA + PCH oddities with linux and Windows (mismatched Vulkan header versions causing build time issues on linux/Windows and runtime problems on linux).
