### ISSUE TITLE
[Question] How to switch to OpenGL renderer?

### ISSUE THREAD

**Issue by runlevel5** [RobertBeckebans/RBDOOM-3-BFG#735]
It's seems to me the `r_graphicsAPI` does not have option for OpenGL. So how could we go about from tell the app to load such renderer?

**Comment by runlevel5** [comment]
Nvm, I misunderstood the change. The default renderer is still OpenGL, it's just that now it is possible to switch to Vulkan without compiling from scratch different binary

**Comment by xcom169** [comment]
For me the default is Vulkan.  How to switch back to OpenGL?
