### ISSUE TITLE
 Cannot find a SPIR-V capable DXC executable

### ISSUE THREAD

**Issue by aminvandh** [RobertBeckebans/RBDOOM-3-BFG#737]
Cannot find a SPIR-V capable DXC executable, os is  debian, vulkan already installed

**Comment by ericwomer** [comment]
You have to build it yourself, from https://github.com/microsoft/DirectXShaderCompiler and you may need to set it up to have a bash script in your ~/bin or ~/.local/bin called dxc so you can set up its environment in the bash script to have it run. https://gist.github.com/ericwomer/63383d7029e9f83d3c8b92c4f0a79184
I also had to symlink the libdxcompiler.so file to its versioning name, cd to the dxc's library path, /what/ever/dxc/lib/x64 and run ln -sv libxcompiler.so libdxcompiler.so.3.7, it should work now.

**Comment by mkschreder** [comment]
You can download the binary from the provided link above and just extract it into your root (/)

**Comment by Calinou** [comment]
It probably makes sense to write a script to install DXC and expose it to `PATH` in the current session, so you can build RBDOOM-3-BFG more easily.

**Comment by SRSaunders** [comment]
FYI - I recently added some logic to CMakeLists to look for dxc (for SPIRV) via the OPTIONAL_COMPONENTS capability within FindVulkan.cmake. If it isn't found via this method, it falls back to using FindDXCspirv.cmake, and finally to the DXC_SPIRV_EXECUTABLE CMake variable.  This should help with some linux distributions, and works well with macOS where the VULKAN_SDK packages the dxc executable.

**Comment by nickbailuc** [comment]
could someone explain what is the purpose of this .so or the dxc for the game if it is running in vulkan or OpenGL?

I'm having serious trouble compiling DXC on my ARM64 laptop.

I'm also looking at Debian's dfsg version of rbdoom3 but can't find what they modified to get accross this issue. Is the Debian package using DXC as well, or is it one of the things they cut from the package before posting their version?

**Comment by SRSaunders** [comment]
DXC is the new shader compiler for the 1.5 and later versions of RBDoom3BFG, which targets DX12 and Vulkan only (not OpenGL).  DXC is available publicly at the GitHub link above.

DXC is not needed for the 1.4 and earlier versions of the game that offers OpenGL and partial Vulkan support.  I believe the Debian package is the 1.4 version.

**Comment by ericwomer** [comment]
> You have to build it yourself, from https://github.com/microsoft/DirectXShaderCompiler and you may need to set it up to have a bash script in your ~/bin or ~/.local/bin called dxc so you can set up its environment in the bash script to have it run. https://gist.github.com/ericwomer/63383d7029e9f83d3c8b92c4f0a79184 I also had to symlink the libdxcompiler.so file to its versioning name, cd to the dxc's library path, /what/ever/dxc/lib/x64 and run ln -sv libxcompiler.so libdxcompiler.so.3.7, it should work now.

When I wrote this I think the binaries were outdated or didn't work, I now use the latest binary builds from the https://github.com/microsoft/DirectXShaderCompiler/releases link which works now with the latest git master branch of RBDoom3BFG.
