### ISSUE TITLE
Build/run without vulkan?

### ISSUE THREAD

**Issue by mkschreder** [RobertBeckebans/RBDOOM-3-BFG#739]
Is it possible to run with legacy support?

Getting this on an older laptop:

Installed Vulkan doesn't implement the VK_KHR_surface

**Comment by Calinou** [comment]
> Getting this on an older laptop:

What graphics card model do you have in that laptop? Does it have hybrid graphics (NVIDIA Optimus)?

**Comment by mkschreder** [comment]
Intel 4600.

I have installed mesa support. Now the issue is this:

MESA-INTEL: warning: Haswell Vulkan support is incomplete
Sys_Error: Cannot find a Vulkan device that supports all the required extensions and properties.
Intel(R) HD Graphics 4600 (HSW GT2):
  - cannot support the requested swap chain size: requested 1280x720,  available 617x1023 - 617x1023
llvmpipe (LLVM 12.0.0, 256 bits):
  - does not support samplerAnisotropy
  - cannot support the requested swap chain size: requested 1280x720,  available 617x1023 - 617x1023

What would be a good way to get around this?

**Comment by RobertBeckebans** [comment]
OpenGL has been deprecated but you also try DX12 on Windows with that card.
