### ISSUE TITLE
Just compiled on Linux, unable to launch RBDoom3BFG 

### ISSUE THREAD

**Issue by vide0hanz** [RobertBeckebans/RBDOOM-3-BFG#740]
I can't seem to get the newly compiled binary to run on my system. 

OS: Arch Linux, kernel version 6.1.9
GPU: Nvidia GeForce RTX 2080 SUPER
Display: HP Omen GSync Compatible Display, 1440p 165hz refresh rate 

When attempting to run the `RBDoom3BFG` binary from the command line, I was getting the following output near the end:

```
Enabled Vulkan layers:
Sys_Error: Cannot find a Vulkan device that supports all the required extensions and properties.
NVIDIA GeForce RTX 2080 SUPER:
  - cannot support the requested swap chain size: requested 1280x720,  available 1273x700 - 1273x700
```

This seemed to suggest the game was requesting to be launched at 720p but couldn't, due to the window size the game was inheriting (for context, I'm running a tiling window manager which generally will restrict graphical applications to the size of the terminal window it is launched from)

So, okay, fine - I created an `autoexec.cfg` file in `/base` with the following lines:

```
set r_vidMode "-1"
set r_displayRefresh "165"
set r_customWidth "2560"
set r_customHeight "1440"
set r_fullscreen "1"
```

Now, `Sys_Error` message I'm getting is this:

```
Created Vulkan device: NVIDIA GeForce RTX 2080 SUPER
----- Initializing Render Shaders -----
Unknown command 'vid_restart'
Sys_Error: Couldn't read the binary file for shader renderprogs2/spirv/builtin/gui.vs.bin
```

Not sure what I seem to be missing or doing wrong. 

Here is the full logfile I created in case there's something I'm not seeing?
[log.log](https://github.com/RobertBeckebans/RBDOOM-3-BFG/files/10689947/log.log)

**Comment by vide0hanz** [comment]
Eh, scratch that - I didn't realize what I was missing was in the `/base` directory provided in the repo, lol. It's working now.

**Comment by RobertBeckebans** [comment]
I also have this again. I think the resolutions that SDL report don't match.
`
----- R_InitOpenGL -----
Initializing Vulkan subsystem
Enabled Vulkan instance extensions:
    VK_EXT_debug_utils
    VK_KHR_xlib_surface
    VK_KHR_surface
    VK_KHR_get_physical_device_properties2
Enabled Vulkan layers:
Sys_Error: Cannot find a Vulkan device that supports all the required extensions and properties.
NVIDIA GeForce RTX 2070 SUPER:
  - cannot support the requested swap chain size: requested 2560x1440,  available 2560x1367 - 2560x1367
llvmpipe (LLVM 13.0.1, 256 bits):
  - cannot support the requested swap chain size: requested 2560x1440,  available 2560x1367 - 2560x1367
  - does not support the requested swap chain format
  - cannot present
trebor@Linux-Workstation:~/Projects/RBDOOM-3-BFG/build$
`

**Comment by RobertBeckebans** [comment]
This is what Kubuntu 22.04 shows me concerning the resolutions for 120 Hz:

![Screenshot_20230305_111336](https://user-images.githubusercontent.com/1278614/222954363-f676b5d3-0f7e-4cab-8baf-022d53fcd98d.png)

**Comment by SRSaunders** [comment]
The 2560x1367 vs. 2560x1440 dimensions look suspiciously like the difference between a menu bar being present or not.  Does this error only occur when starting up in fullscreen mode?  It's almost as if there is confusion at startup between windowed-mode dimensions (for window creation) with fullscreen-mode display (for swap chain).

I will have a look to see if there is something wrong with the initialization of `parms.fullScreen` and/or `glConfig.isFullscreen` and the implications on window & swap chain creation.

**Comment by vide0hanz** [comment]
Ah, good catch - Turns out there was, in fact, some sort of bug? I guess I was able to resolve my initial issue with the aformentioned autoexec params, but I didn't think to test without forcing the resolution after ensuring all of the necessary files were in place.

**Comment by RobertBeckebans** [comment]
This is referering to #759 as the bug still persists in that branch.

Another issue this goes with I think the same issue is that every time I want to select a different full screen mode from the graphics options or I just try to go to windowed mode using Alt + Enter it crashes the engine.

BDoom3BFG: /home/trebor/Projects/RBDOOM-3-BFG/neo/sys/DeviceManager_VK.cpp:1272: virtual void DeviceManager_VK::BeginFrame(): Assertion `res == vk::Result::eSuccess || res == vk::Result::eSuboptimalKHR' failed.
signal caught: Aborted
si_code -6
Trying to exit gracefully..
session->GetSaveGameManager().CancelToTerminate();
soundSystem->StopAllSounds();
Stop();

**Comment by SRSaunders** [comment]
Hi @vide0hanz, the fix for this is now merged into the head stream. If it solves your problem, would you please close this issue? Thx.

**Comment by vide0hanz** [comment]
> Hi @vide0hanz, the fix for this is now merged into the head stream. If it solves your problem, would you please close this issue? Thx.

I'd love to check, but I am pretty sure my GPU failed on me last night! So unfortunately I won't be able to verify this is resolved for a while. Feel free to close it for now, if it crops up again I will open a new issue.

**Comment by naggie** [comment]
I can confirm this is fixed based on https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/884
