### ISSUE TITLE
Engine does not start on some Windows 10/11 laptops

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#743]
This has been reported several times and also applies for the original BFG edition. It seems to be a bug in the Display enumerator code.

**Comment by Calinou** [comment]
With Vulkan, this could be similar to https://github.com/godotengine/godot/issues/57708 if the issue is scoped to AMD integrated + NVIDIA dedicated GPU configurations.

**Comment by RobertBeckebans** [comment]
Thanks for the hint. I have a new notebook where I can finally reproduce the problem.

I think the problem in the BFG code is here:
```
       if( !( device.StateFlags & DISPLAY_DEVICE_ATTACHED_TO_DESKTOP ) )
        {
            continue;
        }
```

**Comment by RobertBeckebans** [comment]
Well in my case it was that my notebook display only supports 165 Hz and the BFG edition usually discards all resolutions that don't support 60 and 120 Hz.

I also extended the code to check for: 
```
if( !( device.StateFlags & ( DISPLAY_DEVICE_ATTACHED_TO_DESKTOP | DISPLAY_DEVICE_PRIMARY_DEVICE ) ) )
```
