### ISSUE TITLE
New SSAO pass flickers when Temporal Anti-aliasing (TAA) is off

### ISSUE THREAD

**Issue by SRSaunders** [RobertBeckebans/RBDOOM-3-BFG#744]
With TAA off, if you move around a map the new SSAO pass intensity changes significantly, almost like a flickering effect.

Setting `r_useNewSsaoPass = 0` stops this from happening.  Interestingly, if you then switch back to `r_useNewSsaoPass = 1` without restarting, then the flickering _does not reappear_.  It seems there is an initialization problem at startup with the combo of `r_useNewSsaoPass = 1` and `r_antiAliasing = 0`.

Issue: `rpWindowCoord` is not being initialized **before the Ambient Lighting IBL shaders are called within** `DrawSingleInteraction()` via `AmbientPass()` and `DrawInteractions()`.

**Comment by RobertBeckebans** [comment]
I commited a fix for this into the vma-integration branch.

**Comment by SRSaunders** [comment]
Thanks for fixing this. Works fine now.
