### ISSUE TITLE
[NVRHI] Slow performance on AMD GPUs with DX12

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#746]
This referes to #742 

Very interesting Vulkan seems to be a lot faster in most cases on AMD. DX12 has really much worse GPU timers.

DX12 1080p:
![rbdoom-3-bfg-20230222-195308-004](https://user-images.githubusercontent.com/1278614/220851555-72ae5d04-68d8-45ae-9c8d-02a04b04935d.png)

Vulkan 1080p:
In Vulkan each renderpass is better but it has some ridiculous high timing in the shadowmap atlas rendering.
![rbdoom-3-bfg-20230222-211323-001](https://user-images.githubusercontent.com/1278614/220851797-e34502b2-eded-40e5-b371-75509bdee373.png)

Going back to the old rendering method like in RBDoom 1.4 by disabling the shadowmap atlas results in a much better performance: 34 FPS (DX12) vs. 81 FPS (Vulkan)
![rbdoom-3-bfg-20230222-211821-001](https://user-images.githubusercontent.com/1278614/220852107-e0ce01e4-f884-4722-a59e-be2348a22de3.png)

This is also unfortunate because the shadowmap atlas was a preparational step that is required for faster Forward+ rendering so we could render all interactions without rendering the objects for each light.

Maybe the performance problems go away if I further optimize the shadowmap allocation using a smaller shadowmap atlas.
Currently it is 16384^2 because Doom 3 has so many dynamic lights but I already figured that many point lights also have empty allocations in that atlas because some of the 6 pyramids don't contain any occluder.
Maybe switching to a different rendertarget like FLOAT16RG and using some kind exponential shadowmaps or VSM might also help.

**Comment by Calinou** [comment]
> Maybe switching to a different rendertarget like FLOAT16RG and using some kind exponential shadowmaps or VSM might also help.

16-bit shadows (compared to 24-bit) should help quite a bit in performance, without impacting quality too much as most point lights in Doom 3 are small enough.

**Comment by RobertBeckebans** [comment]
Ah well I found a significant bug in the shadow atlas code. It allocated 6 pyramids for all points lights and not only the shadow casting ones. 8192^2 works fine now.

**Comment by RobertBeckebans** [comment]
@Calinou your hint with the integrated vs. dedicated GPU was good. It is the same case here. The notebook has 2 GPUs.
One Radeon Graphics (TM) and another dedicated Radeon 6600M.
NVRHI DX12 prefers the first one and Vulkan seems to be faster because it prefers the second.
