### ISSUE TITLE
Add support for original Doom 3 and Doom III: Resurrection of Evil and their multiplayer

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [RobertBeckebans/RBDOOM-3-BFG#747]
Doom 3 BFG is not that popular because of its graphics, some questionable choices, and cut content but the engine itself is more advanced.

Modders still use original Doom 3 (2004).

Is there a chance we get support for original Doom III and Doom III: Resurrection of Evil?

I know about dhewm3, but I'd like to see something more advanced for the original game and its multiplayer.

**Comment by Calinou** [comment]
This is out of scope for the engine – this is something the modders should do :slightly_smiling_face:

**Comment by RobertBeckebans** [comment]
If you buy Doom 3 on Steam you get Doom 3, ROE and the BFG edition.
However as Calinou said that the request is out of scope of this project. I agree with id Software with most changes in the BFG edition (steady flashlight, more ammo, more lights) and my baked global illumination continues that direction.
For me it is more important to have proper gamepad and 16:9 support than some cut content.

**Comment by YevheniiPokhvalii** [comment]
> If you buy Doom 3 on Steam you get Doom 3, ROE and the BFG edition. However as Calinou said that the request is out of scope of this project. I agree with id Software with most changes in the BFG edition (steady flashlight, more ammo, more lights) and my baked global illumination continues that direction. For me it is more important to have proper gamepad and 16:9 support than some cut content.

The new re-release of Doom 3 BFG does not have multiplayer as far as I know. So, that's another negative point for Doom 3 BFG edition.

**Comment by RobertBeckebans** [comment]
Doom 3 BFG is an entirely different or very different engine. Supporting the old GUIs for the menus would completely clash in the code. Also the entire network stack was replaced with id Tech 5 code so you can't make it compatible with vanilla D3 in an easy way.
The multiplayer has been dead for a decade in my opinion and so it is not surprising that id Software removed it from the 2019 version.
