### ISSUE TITLE
Add support for gravity anomalies like in Prey 2006

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [RobertBeckebans/RBDOOM-3-BFG#748]
Prey 2006 was a unique game that remains unique even in 2023. 
It has such things like transparent portals, variable gravity, wall walking, etc. All those things even work properly in Multiplayer.
And it's on idTech 4.

I'm not sure how it is difficult to implement into the engine itself but it would allow modders to create some crazy stuff.

P.S. As far as I remember, the first[ Serious Sam engine 2001](https://github.com/Croteam-official/Serious-Engine) was also capable of doing those things (it is opensource now) and they are not supported in their later engine versions.
You can also find this repo: https://github.com/jmarshall23/PreyDoom

**Comment by davidebeatrici** [comment]
In addition to integrating Prey's unique mechanics, being able to play the levels themselves with this engine would be awesome.

The official SDK:

[prey_sdk_2006-10-09.zip](https://github.com/RobertBeckebans/RBDOOM-3-BFG/files/10845301/prey_sdk_2006-10-09.zip)
[PREY_SDK_2006-10-13.zip](https://github.com/RobertBeckebans/RBDOOM-3-BFG/files/10845305/PREY_SDK_2006-10-13.zip)
[preytutorialmaps.zip](https://github.com/RobertBeckebans/RBDOOM-3-BFG/files/10845306/preytutorialmaps.zip)

Please note that the license is not open-source, on the other hand Human Head Studios went under (unfortunately) and the game itself is in theory considered abandonware.

**Comment by ericwomer** [comment]
> In addition to integrating Prey's unique mechanics, being able to play the levels themselves with this engine would be awesome.
> 
> The official SDK:
> 
> [prey_sdk_2006-10-09.zip](https://github.com/RobertBeckebans/RBDOOM-3-BFG/files/10845301/prey_sdk_2006-10-09.zip) [PREY_SDK_2006-10-13.zip](https://github.com/RobertBeckebans/RBDOOM-3-BFG/files/10845305/PREY_SDK_2006-10-13.zip) [preytutorialmaps.zip](https://github.com/RobertBeckebans/RBDOOM-3-BFG/files/10845306/preytutorialmaps.zip)
> 
> Please note that the license is not open-source, on the other hand Human Head Studios went under (unfortunately) and the game itself is in theory considered abandonware.

ZeniMax Media -> Bethesda Softworks own's the IP still and I highly doubt they would opensource a game they buried when they white-washed the IP and rebooted it.

**Comment by davidebeatrici** [comment]
Definitely not. We can only hope the studio's works prior to the (hostile) acquisition by Bethesda are not covered by whatever license the IP has right now.

**Comment by ericwomer** [comment]
Bethesda took Prey down soon after acquisition, buried the real sequel to Prey and released some carbon copy of every other game like it out there as a reboot. Who ever buys the IP owns the rights to those IP unless that IP is separated off to some other entity or its own product. The fact Bethesda released Prey 2017 proves they own the IP and are the reason why the original will never be open sourced. The X-Real engine already implemented some of the cool features from Prey but I don't know what ever happened to that engine. Maybe it can be ported to this engine, since they share the same codebase those several generations off. There are a lot of games that vanish that I wish would get re-released by never do because some third party acquisition publisher sits on it.

**Comment by davidebeatrici** [comment]
https://github.com/QuakeEngines/ET-XreaL

This one?

**Comment by RobertBeckebans** [comment]
XreaL and ET:XreaL were my previous projects. However those features were implemented from scratch. I don't want to repeat this for this project and mixing non-GPL code by the Prey SDK is just illegal. It does not even have anything to do with the IP itself.
Justin has a different attitude concerning the non-GPL issue but I want to keep this repository clean from this.

**Comment by ericwomer** [comment]
> XreaL and ET:XreaL were my previous projects. However those features were implemented from scratch. I don't want to repeat this for this project and mixing non-GPL code by the Prey SDK is just illegal. It does not even have anything to do with the IP itself. Justin has a different attitude concerning the non-GPL issue but I want to keep this repository clean from this.

What about implementing an interface to a third party physics library like jolt?
