### ISSUE TITLE
Set up continuous integration to provide nightly builds/PR builds

### ISSUE THREAD

**Issue by Calinou** [RobertBeckebans/RBDOOM-3-BFG#751]
I'd like to have access to daily Windows/Linux builds of this repository for testing the `master` branch, but also pull requests like https://github.com/RobertBeckebans/RBDOOM-3-BFG/pull/750. I'd be willing to work on this (likely using GitHub Actions) if desired :slightly_smiling_face: 

The GI data will have to be kept a separate download to keep artifacts size low. I assume the CI artifacts will contain only executables and libraries, since GitHub Actions limits storage to 10 GB in total (artifacts expire in 90 days by default, but it can be shortened). We can embed a `README.txt` in the artifacts telling the user to download the GI data and install it.

**Comment by RobertBeckebans** [comment]
Doom BFA based on this source port has automatic builds using Github actions.

https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/blob/c811433c29efea5b954a6afc4105e99cc18e3e82/.github/workflows/cmake.yml

Maybe this helps as a starting point.

**Comment by RobertBeckebans** [comment]
I still prefer to roll out builds in Discord so I get feedback for the new features.
