### ISSUE TITLE
Does this support HDR on linux?

### ISSUE THREAD

**Issue by romulasry** [RobertBeckebans/RBDOOM-3-BFG#753]
See:
https://www.reddit.com/r/linux_gaming/comments/10m2gyx/guide_alpha_test_hdr_on_linux/

**Comment by RobertBeckebans** [comment]
No it uses HDR internally for correct light calculations but the final output tonemapped back to sRGB R8G8B8.

**Comment by Calinou** [comment]
It might be worth checking if on Windows 11 using D3D12, you can get Auto HDR to work: https://support.microsoft.com/en-us/windows/use-auto-hdr-for-better-gaming-in-windows-0cce8402-3de5-4512-a742-e027ca7aa79c
