### ISSUE TITLE
Add Masked Software Occlusion Culling

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#756]
This will be an experiment for a weekend. Code and paper can be found here: https://github.com/GameTechDev/MaskedOcclusionCulling

I think this can be very handy for all big BSP areas where it's complicated to place proper vis portals.
We could just render the BSP area models which are low poly into the software depth buffer of just 779 kb for 1920x1080 in the renderer frontend. Then during the multithreaded culling of the models we do additional visibility testing by drawing and querying their bounding box against this depth buffer.

The API seems to be trivial and everything can be implemented in a few hours.

**Comment by Calinou** [comment]
For reference, Godot 4 uses this approach. It works well but there are two caveats:

- No easy support for dynamic occluders (a different approach needs to be used).
- Gaps between geometry can cause false negatives in occlusion: https://github.com/godotengine/godot/issues/53288

**Comment by RobertBeckebans** [comment]
Thanks for pointing at that issue.

**Comment by stephenap07** [comment]
I wonder how this would compare against handling occlusion against Hierarchical depth buffer like in UE5. We already render a HiZ for SSAO. Their method uses the previous visible surfaces as occluders for the current rendered frame which sounds simpler.

**Comment by RobertBeckebans** [comment]
I must say that I really like this technique. I can not only cull individual draw surfaces from entities but also lights by testing the volume against the software occlusion buffer.  It's a perfect fit for the complicated BFG architecture where you can't really use GPU occlusion queries because of the frame delayed renderer frontend/backend

Here is one of the worst demanding scenes. I have stable 120 fps without Masked Software Occlusion Culling and 140 with. 
 
**It is _7200 vs 4700_ draw calls.**

Normal rendering:
![rbdoom-3-bfg-20240826-222918-002](https://github.com/user-attachments/assets/6ed9089a-87a1-4032-9b22-a549e0fd0878)

With Masked Occlusion Culling:
![rbdoom-3-bfg-20240826-222922-003](https://github.com/user-attachments/assets/af033b96-b7ad-46b0-add7-398462931561)
