### ISSUE TITLE
Read-write depth attachment warnings when depth-stencil is read-only

### ISSUE THREAD

**Issue by SRSaunders** [RobertBeckebans/RBDOOM-3-BFG#760]
When creating a new graphics pipeline, there are warnings that the framebuffer depth attachment is read-write, but the depth-stencil state is read-only.  The warning message is: _"The depth-stencil state indicates read-only depth and stencil, but the framebuffer has a read-write depth attachment, which is suboptimal."_

I have found a way to eliminate these, but the solution is a bit of a hack.  Inside `PipelineCache::GetRenderState( )` you can do the following:

```
if( ( stateBits & ( GLS_STENCIL_FUNC_BITS | GLS_STENCIL_OP_BITS | GLS_SEPARATE_STENCIL ) ) != 0 ||
    // SRS - Eliminate r/w depth attachment validation warnings when depth-stencil is read-only
    ( depthStencilState.depthTestEnable && !depthStencilState.depthWriteEnable ) )
{
	depthStencilState.enableStencil();
}
else
{
	depthStencilState.disableStencil();
}
```

This sets the `renderState.depthStencilState.stencilEnable` boolean when depth is read-only, which indicates to `DeviceWrapper::validateRenderState()` that the depth-stencil state is still read-write, and thus no validation warnings are emitted.  In my testing I see no rendering or performance impact of doing this.  Interestingly, the donut example has the same problem and emits these same warnings.

As an aside, I could not find any way to modify the read-write state of the depth attachment (i.e. the `isReadOnly` boolean) following framebuffer creation, so that angle was a dead-end for me.

I have not yet submitted this as a pull request since others may have a better solution.  Feedback?

**Comment by RobertBeckebans** [comment]
Well I removed the stencil shadows but the stencil buffer is still important to render the FLash based UIs in the main menu correctly.
I think I had to call enableStencil() or all stencil operations will be ignored. If it also happens in the Donut samples then it's probably best to make a bug report there and keep it here as it is.

**Comment by SRSaunders** [comment]
`enableStencil` is still being called at the right time and the game + flash UIs render properly.  The warning kind of makes sense - indicating that a depth-stencil read-only state does not match a read-write framebuffer attachment.  My workaround simply forces the stencil part to be read-write when the depth part is read-only, and avoids the warning condition.  However, if you would prefer to punt this over to the NVRHI guys that's fine by me.
