### ISSUE TITLE
How to reproduce what's in the moddb tarball

### ISSUE THREAD

**Issue by scaronni** [RobertBeckebans/RBDOOM-3-BFG#762]
Hi, linux user here,  I would like to replay this game with the best settings possible based on the documentation provided and the tarballs that are on moddb. I'm not interested in the modding/editor part.

I've compiled the binary and used the official game data from GOG, game runs fine. Now I'm at the new lighting effects.

Looking at the documentation it seems the only thing I need to do to reproduce the moddb tarballs is load every map from the console and then run `bakeLightGrids` and `bakeEnvironmentProbes`, but then I saw this under "Known issues": https://github.com/RobertBeckebans/RBDOOM-3-BFG#known-issues-

> Some shadows in the original campaigns might almost disappear due to bad light properties like light center near outside of the bounding box. This has been partially fixed by patching those light entities.

Which ones are those? Which are the files I should pick up from your Mod DB tarball? Is there anything else I need to copy over?

Thanks & keep up the great work!

**Comment by RobertBeckebans** [comment]
You can just extract the base/ folder from the 1.3.0 full release over your git base/ folder. Then you have all the prebaked light data. To make sure you don't override newer files with older ones just do git checkout . in the base/ folder.

That is way easier than loading each map and compiling the light data.
Most light problems were fixed using base/maps/game/*.extra_ents.map files which override the original .map entity properties.

**Comment by scaronni** [comment]
Super, thank you!

**Comment by scaronni** [comment]
Sorry to revive an old ticket. I have these from the Mod DB tarball:
```
base/env/maps/game
base/maps/game/*.lightgrid
```
That seems to do the work just fine for the new files.

I got a few errors though:
```
------------- Warnings ---------------
during game/mars_city1...
WARNING: Couldn't load image: env/maps/game/mars_city1/area6_lightgrid_amb : env/maps/game/mars_city1/area6_lightgrid_amb#__2200
WARNING: Couldn't load image: env/maps/game/mars_city1/area14_lightgrid_amb : env/maps/game/mars_city1/area14_lightgrid_amb#__2200
WARNING: Couldn't load image: env/maps/game/mars_city1/area52_lightgrid_amb : env/maps/game/mars_city1/area52_lightgrid_amb#__2200
WARNING: Couldn't load image: env/maps/game/mars_city1/area53_lightgrid_amb : env/maps/game/mars_city1/area53_lightgrid_amb#__2200
WARNING: Couldn't load image: _cinematicY : _cinematicY#__0200
WARNING: Couldn't load image: _cinematicCr : _cinematicCr#__0200
WARNING: Couldn't load image: _cinematicCb : _cinematicCb#__0200
WARNING: Couldn't load image: _cinematic : _cinematic#__0200
WARNING: Couldn't load image: _emptyname : _emptyname#__0200
9 warnings
```

On top of that I'm shipping the entire game on a few computers at work (:smile:) under `/usr/share/doom3bfg`, and it's not clear you need to have a writable game folder to generate additonal assets:
```
Binarize File: 'env/maps/game/mars_city1/area1_envprobe_1131__1293_75_amb#__2206' - reason 'binarize: binary file not found 'env/maps/game/mars_city1/area1_envprobe_1131__1293_75_amb#__2206''
Binarize File: 'env/maps/game/mars_city1/area1_envprobe_1131__1293_75_amb#__2206' - reason 'binarize: binary file not found 'env/maps/game/mars_city1/area1_envprobe_1131__1293_75_amb#__2206''
writing to: /usr/share/doom3bfg/base/generated/images/env/maps/game/mars_city1/area1_envprobe_1131__1293_75_amb#__2206.bimage
Writing generated/images/env/maps/game/mars_city1/area1_envprobe_1131__1293_75_amb#__2206.bimage: 32x32
```

Would it be possible to have those generated in `~/.local/share/rbdoom3bfg/base` instead? If not, can I copy those over from one system to the other or are they system unique like shaders and silmilar stuff?
