### ISSUE TITLE
Add Optick GPU profiling for Vulkan

### ISSUE THREAD

**Issue by SRSaunders** [RobertBeckebans/RBDOOM-3-BFG#766]
I have a pending PR for adding Optick GPU profiling for Vulkan, but did not push/submit before going away on vacation.

Not sure if you would want this included in the 1.5 release or left for a future enhancement.  I will be back on April 30 and could submit then.

**Comment by RobertBeckebans** [comment]
That's cool but I only plan to push another minor glTF2 fix and we are basically in feature freeze mode. There will be a 1.6.0 after this. Enjoy your vacation :)

**Comment by SRSaunders** [comment]
Thanks Robert.  I’ll put this in later.  Good luck with the 1.5 release.
