### ISSUE TITLE
ERROR: GL_ARB_uniform_buffer_object not available

### ISSUE THREAD

**Issue by zCrasher** [RobertBeckebans/RBDOOM-3-BFG#771]
Hi
 I have just installed, falls straight back to commandline and I get the above error, . This is an old system so maybe its just not capable....Are there any commandline extensions to enable a more basic start to the game?
Running Ubuntu 23.04

graphics hardware is - 
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Mobile Intel® GM45 Express Chipset (CTG) (0x2a42)
    Version: 23.0.2
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Mobile Intel® GM45 Express Chipset (CTG)
OpenGL version string: 2.1 Mesa 23.0.2
OpenGL shading language version string: 1.20

**Comment by RobertBeckebans** [comment]
OpenGL isn't supported anymore. We moved the renderer to Vulkan for Linux. But you can try the Doom BFA port and see if you have luck with that.
