### ISSUE TITLE
[QOL feature] Option to disable in-game music.

### ISSUE THREAD

**Issue by CortexReaver** [RobertBeckebans/RBDOOM-3-BFG#777]
subj

**Comment by Calinou** [comment]
In general, there's no volume slider at all, which I find very strange. Was the vanilla game like that too?

**Comment by CortexReaver** [comment]
> In general, there's no volume slider at all, which I find very strange. Was the vanilla game like that too?

BFG edition? the volume slider is in "system" tab, I've checked it - same with the original exe, that is next to the RBDoom one. Though I can't remember about older 2004 version.

**Comment by RobertBeckebans** [comment]
I think this is an asset problem. There isn't really ingame music in Doom 3. The music and theme is mostly done by many smaller local sound emitters.
