### ISSUE TITLE
Can't capture game in fullscreen DX12 with OBS.

### ISSUE THREAD

**Issue by CortexReaver** [RobertBeckebans/RBDOOM-3-BFG#779]
Only "Window capture" while running game in window mode works. Vulkan is capturing fine.

Was tested on...
GPU: nVidia GTX 1050 Ti
OS: Windows 10 22H2
OBS version: 29.1.1 64 bit

**Comment by CortexReaver** [comment]
Oh, I see. So it was not fixed in 1.5.1. Just have to wait for that one I guess.

**Comment by CortexReaver** [comment]
OBS can't capture borderless fullscreen either. As I said, only "window capture" (and apperently desktop capture) is working, no matter how I run the game. I woulg gladly use Vulkan, but it seems to have perfomance issues.

**Comment by RobertBeckebans** [comment]
I used OBS with desktop capture in that video.

**Comment by CortexReaver** [comment]
Yeah, this way it doesn't matter in which mode game is running.

**Comment by CortexReaver** [comment]
I found what caused this issue - I have leaved vsync in nVidia panel turned on. Now it's disabled, everything's capturing perfectly.
