### ISSUE TITLE
Security cameras not working

### ISSUE THREAD

**Issue by rg3** [RobertBeckebans/RBDOOM-3-BFG#782]
I can observe this in the CPU Complex map, in the Security Monitoring area. In this part of the game the feature is a bit more important, because you're supposed to see the security code for one of the doors through these cameras (eventhough the code is available from other sources). The game displays a black image.

![rbdoom-3-bfg-20230524-201246-001](https://github.com/RobertBeckebans/RBDOOM-3-BFG/assets/53487/7b367385-260e-4a22-9cc0-365715898fcc)

**Comment by RobertBeckebans** [comment]
Well I already answered this on ModDB:

[treborator](https://www.moddb.com/members/treborator) May 3 2023
I played through almost every map of the campaign to make sure there are no gameplay breakers.
There is a another small interactive screen on the other side of that room. It opens a security hatch where you can find the PDA of Tony Bates.

It is here: [Imgur.com](https://imgur.com/ttc6T0C)

The first audio log contains the access code to the CPU Lab A.

This ticket is also a duplicate of #741

**Comment by rg3** [comment]
Ah, I knew about the other code sources but somehow didn't manage to find issue #741. Thanks!
