### ISSUE TITLE
error running on linux (leftwm)

### ISSUE THREAD

**Issue by Oreolek** [RobertBeckebans/RBDOOM-3-BFG#783]
first run went fine but on the second run this happens:

latest git commit [39ae120](https://github.com/RobertBeckebans/RBDOOM-3-BFG/commit/39ae1202b4e61ccb8d8e59609f5cd62b04a62a58), ArchLinux 64bit

```
----- R_InitOpenGL -----
Initializing Vulkan subsystem
Enabled Vulkan instance extensions:
    VK_EXT_debug_utils
    VK_KHR_xlib_surface
    VK_KHR_surface
    VK_KHR_get_physical_device_properties2
Enabled Vulkan layers:
Sys_Error: Cannot find a Vulkan device that supports all the required extensions and prope
rties.
AMD Radeon RX 5500 XT:
  - cannot support the requested swap chain size: requested 3838x2118,  available 1918x704 - 1918x704
  ```

UPD: it's a tiling [leftwm](https://github.com/leftwm/leftwm) window manager. It sees a new window and auto-resizes it to 1918x704. RBRoom3 runs in windowed mode by default, doesn't expect the window size to be different and bails. The solution is to run `./RBDoom3BFG +set r_windowWidth 1918 +set r_windowHeight 704` like the window manager expects.

This bug is present every time game runs, even if the game settings are set to "Fullscreen". Setting `r_fullscreen` doesn't help.

**Comment by SRSaunders** [comment]
In DeviceManager_VK.cpp, would you try replacing the following code:

```
if( surfaceCaps.minImageExtent.width > requestedExtent.width ||
	surfaceCaps.minImageExtent.height > requestedExtent.height ||
	surfaceCaps.maxImageExtent.width < requestedExtent.width ||
	surfaceCaps.maxImageExtent.height < requestedExtent.height )
{
	errorStream << std::endl << "  - cannot support the requested swap chain size:";
	errorStream << " requested " << requestedExtent.width << "x" << requestedExtent.height << ", ";
	errorStream << " available " << surfaceCaps.minImageExtent.width << "x" << surfaceCaps.minImageExtent.height;
	errorStream << " - " << surfaceCaps.maxImageExtent.width << "x" << surfaceCaps.maxImageExtent.height;
	deviceIsGood = false;
}
```

with:

```
m_DeviceParams.backBufferWidth = std::clamp( m_DeviceParams.backBufferWidth, surfaceCaps.minImageExtent.width, surfaceCaps.maxImageExtent.width );
m_DeviceParams.backBufferHeight = std::clamp( m_DeviceParams.backBufferHeight, surfaceCaps.minImageExtent.height, surfaceCaps.maxImageExtent.height );
```

and let me know the result.  Thanks.

**Comment by SRSaunders** [comment]
Hi @Oreolek, the fix for this is now merged into the head stream.  If it solves your problem, would you please close this issue?  Thx.
