### ISSUE TITLE
Crash when trying to load a quicksave on "Alpha Labs Sector 2".

### ISSUE THREAD

**Issue by CortexReaver** [RobertBeckebans/RBDOOM-3-BFG#785]
Subj
Specs are;
GPU: nVidia GTX 1050 Ti
OS: Windows 10 22H2
Playing on DX12 API

**Comment by CortexReaver** [comment]
And seems like it's loading just fine through the game menu, but not with F key.

**Comment by RobertBeckebans** [comment]
Cannot be replicated.
