### ISSUE TITLE
Unreasonably low performance and high GPU utilization at any settings

### ISSUE THREAD

**Issue by jelazual** [RobertBeckebans/RBDOOM-3-BFG#789]
![image](https://github.com/RobertBeckebans/RBDOOM-3-BFG/assets/127602282/ef9e1b4a-26d3-475d-9264-992f92c6d660)

Not sure how this is happening, but GPU usage always reports 99% at any resolution, framerates remain unchanged, settings barely do anything. No antialiasing on or anything. Just runs inexplicably bad with inexplicably high GPU utilization.

Running archlinux 6.2, RADV, Mesa 23.1
GPU is 6700XT. Should not be seeing 76fps looking at this hallway with 99% utilization across all resolutions.

Also of note, the GPU power is only about 40w the whole time, meaning it's not really being taxed, but is somehow being limited by utilization.
Some kind of weird nvidia jank maybe? It seems to be worse the further away the furthest surface is.

**Comment by RobertBeckebans** [comment]
Can you open the console and set com_showFPS 3 and take a screenshot? Do
you have multiple GPUs in your system?

Am So., 18. Juni 2023 um 10:48 Uhr schrieb jelazual <
***@***.***>:

**Comment by jelazual** [comment]
![image](https://github.com/RobertBeckebans/RBDOOM-3-BFG/assets/127602282/68579eba-f117-4fde-9f35-c37a8cd8a51a)
Looks like the majority of it is in shadowatlas and interactions.

I have a 1030 with no loaded driver that's sitting idle because I'm too lazy to remove it.

**Comment by Calinou** [comment]
Can you try forcing the highest power state on the GPU manually? This is often required to get the best possible performance on AMD graphics cards, especially on Linux. See https://gitlab.freedesktop.org/drm/amd/-/issues/1500.

**Comment by jelazual** [comment]
X11. I have not tested wayland with this software at this time, and in general do not use wayland as vertical sync is not a viable option for my work.
It happens fullscreen or windowed, at any resolution. 
The GPU in the screenshot is in the higher power state of 2500mhz. 
The compositor is disabled fully in my XFCE desktop, as it always is.

**Comment by RobertBeckebans** [comment]
We can't really do anything about that.
