### ISSUE TITLE
In-Game console does not work on Steam Deck

### ISSUE THREAD

**Issue by VortexAcherontic** [RobertBeckebans/RBDOOM-3-BFG#790]
Hello there,

while I was gathering some info about another issue I have with version 1.5.x on deck (low performance) I noticed that the in-game console does not take any inputs on Deck.

You can open it using the respective shortcut `Shift + ^` and also play the game using Keyboard + Mouse either with physical devices or with emulated KB + Muse using the Steam Deck Controller + Steam Input.  
But the in-game console does not take any inputs at all.

Input methods I tired:

- physical keyboard using a USB-C HUB
- virtual on-screen keyboard provided by the Steam Deck UI
- Keyboard inputs via Steam Link from my PC.
- Setting the Steam Input to emulate KB + Mouse when using the Steam Deck controller

Is there anything I could do to provide some useful logs you guys might be able to spot whats the issue?

I'm running RBDoom3BFG via Luxtorpeda on Steam Deck using [their engine build](https://github.com/luxtorpeda-dev/packages/tree/master/engines/rbdoom-3-bfg). It might be that the issue is on them not on the engine itself.

But at this point I don't know.

Engine version 1.5.1
OS: SteamOS 3.x
Steam Client: Beta (But happens also with the stable Steam Client)

Edit: Counter tested Classic-RBDoom3BFG, there the in-game console does work.

**Comment by RobertBeckebans** [comment]
I have no Steam Deck and can't reproduce it
