### ISSUE TITLE
Last OpenGL version?

### ISSUE THREAD

**Issue by VinnyVicious** [RobertBeckebans/RBDOOM-3-BFG#796]
Since NVRHI seems to be quite buggy and slower, what is the last version of the engine with OpenGL support? 4dbb4bd114cf6ab057d261ffec2697f3d14994c5 ?

**Comment by y2keeth** [comment]
RBDOOM-3-BFG 1.3.0 i think

**Comment by Calinou** [comment]
> RBDOOM-3-BFG 1.3.0 i think

1.4.0 actually: https://github.com/RobertBeckebans/RBDOOM-3-BFG/releases/tag/v1.4.0

**Comment by VinnyVicious** [comment]
So far, 1.4.0 has been working great on Linux. Thank you, all.

**Comment by mbugni** [comment]
> So far, 1.4.0 has been working great on Linux. Thank you, all.

This version is available also [on Flathub](https://flathub.org/it/apps/io.github.RobertBeckebans.RBDoom3BFG-GL).
