### ISSUE TITLE
Mac Xcode and non-Xcode builds don't work

### ISSUE THREAD

**Issue by airuike88** [RobertBeckebans/RBDOOM-3-BFG#797]
I was wrong.. had the wrong nvrhi submodule checked out

**Comment by SRSaunders** [comment]
Yes, the release game should be using commit 1cbc9e9: [nvrhi](https://github.com/RobertBeckebans/nvrhi/tree/1cbc9e9d16f997948c429739b1a1886fb4d0c796)

I have put some fixes in for the head version but these are not merged yet: https://github.com/RobertBeckebans/nvrhi/pull/4
