### ISSUE TITLE
Unable to initialize OpenGL

### ISSUE THREAD

**Issue by bageraz88** [RobertBeckebans/RBDOOM-3-BFG#800]
Have issues with initializing OpenGL(?) Have tried rbdoom1.3 full package and had no problems
Windows 11
i3-4130
Nvidia GTX750 

----- R_InitOpenGL -----
...registered window class
...calling CDS: ok
...created window @ 0,0 (1920x1080)
...releasing DC: success
...destroying window
...resetting display
...calling CDS: ok
...created window @ 0,0 (1280x720)
...releasing DC: success
...destroying window
...resetting display
Unknown command 'vid_restart'
Unable to initialize OpenGL

**Comment by saehan-suh** [comment]
Which version of RBDoom are you experiencing this issue with? 1.4 or 1.5?

**Comment by bageraz88** [comment]
1.5.1

**Comment by RobertBeckebans** [comment]
Duplicate of #844
