### ISSUE TITLE
Problem compiling RBDoom

### ISSUE THREAD

**Issue by Silver-will** [RobertBeckebans/RBDOOM-3-BFG#806]
When I run cmake-vs2022-win64-no-ffmpeg.bat i get an error saying:

> -- Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR) (found version "")
>CMake Error at CMakeLists.txt:390 (message):
>Could not find Vulkan library!

I've tried adding the bin directory  of vulkan sdk to my system Path, but no luck.
OS: windows 11

**Comment by VinnyVicious** [comment]
Try installing with chocolatey: https://community.chocolatey.org/packages/vulkan-sdk
