### ISSUE TITLE
Metainfo summary repeats app name

### ISSUE THREAD

**Issue by bragefuglseth** [RobertBeckebans/RBDOOM-3-BFG#807]
The current app summary is « RBDOOM-3-BFG is a modernization effort of DOOM-3-BFG». In app store frontends like Flathub, this summary is usually displayed next to / close to the app name, which makes mentioning the name redundant. I’d change it to a «A modernization effort of DOOM-3-BFG» or «Play a modernized DOOM-3-BFG».

**Comment by mbugni** [comment]
Flathub metainfo are not managed here, but in [this repo](https://github.com/flathub/io.github.RobertBeckebans.RBDoom3BFG-GL).
Anyway, this issue has been [already discussed](https://github.com/flathub/io.github.RobertBeckebans.RBDoom3BFG-GL/issues/1).

**Comment by bragefuglseth** [comment]
All right, then. I’ll close this 😁
