### ISSUE TITLE
appimage

### ISSUE THREAD

**Issue by legluondunet** [RobertBeckebans/RBDOOM-3-BFG#813]
Hello,
could you provide an easy solution to install and use RBDOOM-3-BFG for Linux users?
Provide an appimage will be a nice solution.

**Comment by mbugni** [comment]
An OpenGL version is already [available on Flathub](https://flathub.org/apps/io.github.RobertBeckebans.RBDoom3BFG-GL).

**Comment by legluondunet** [comment]
It's a good start toward Linux users that just want to install an app without having compile skills. But i saw the version available on Flathub is older than the one available here for Windows users and is OpenGL only.  It will be nice if you provide an AppImage to Linux users for each new version, with same feature as the Windows one.

**Comment by mbugni** [comment]
[Comment on isse #719](https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/719#issuecomment-1301964431)
Isse #804

**Comment by legluondunet** [comment]
From issue #719:
> I usually have the opinion that everybody who wants to run RBDoom3BFG on Linux should just compile it because it is so easy
Not so easy, I spent all day yesterday trying to compile the program, I got there after several hours of research to resolve two major issues. However, I have already used Linux for several years, I am an advanced user, it was not the first github app I compiled.
