### ISSUE TITLE
[TrenchBroomBFG] Extend convertMapToValve220 to support "light_origin"

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#825]
It really sucks that Doom 3 lights can have models and those models/brushes are at the "origin" and the light then renders at "light_origin".

Lights with brushes have be split into 2 entities I guess. One light entity and one func_static entity for the model and flares and they probably should be put together into a func_group.

This is actually important if someone wants to edit the original maps with TrenchBroomBFG.

**Comment by nbohr1more** [comment]
Don't you mean "light_center" which controls the projection origin rather than the entity location origin?
