### ISSUE TITLE
Add FOV support for ultrawide resolutions?

### ISSUE THREAD

**Issue by smeep0** [RobertBeckebans/RBDOOM-3-BFG#833]
Will this game get similar support for ultrawide displays (i.e. 21:9 and 32:9 aspect ratios) as DOOM3BFA Edition did? I see the FOV cap out to 100, but was wondering if it could go as far as FOV 120.

**Comment by RobertBeckebans** [comment]
I have a 21:9 monitor and the engine supports it out of the box. Increasing the FOV further looks bad and we need a separate weapon FOV first.

**Comment by Calinou** [comment]
> Increasing the FOV further looks bad and we need a separate weapon FOV first.

Can we lower the weapon model at high FOV (like in Quake 3) or stretch it as a workaround?

**Comment by RobertBeckebans** [comment]
Yes the weapon FOV should be lower than the regular FOV. I already have a patch by Admer but it didn't work with the displays on the weapons. When that's fixed then we have a separate weapon FOV like in the Source engine.

**Comment by RobertBeckebans** [comment]
Here is the commit: https://github.com/RobertBeckebans/RBDOOM-3-BFG/commit/2cd483b849a920e84aba5429e77f3471388cb2a8

**Comment by RobertBeckebans** [comment]
There is already a ticket for the weapon FOV.
