### ISSUE TITLE
Integrate some DOOM3BFA (Classic-RBDOOM-3-BFG) features?

### ISSUE THREAD

**Issue by smeep0** [RobertBeckebans/RBDOOM-3-BFG#834]
It would be nice if a collaboration with MadDeCoDer would be to bring some of the feature sets of the current version of DOOM3BFA into RBDOOM3 such as half-lambert lighting, bloom effects and some of its gameplay feature sets such as being able to use the flashlight in its original fashion along with restoring content that had been cut from (Vanilla) DOOM3 into the BFG Edition (the version now being the default DOOM3 installed), and other QoL improvements like aiming for weapons. Meanwhile, DOOM3BFA could use the more recent version of RBDOOM3BFG, which now runs in Vulkan.

**Comment by RobertBeckebans** [comment]
Half-Lambert lighting was originally in RBDoom before it was replaced by the PBR solution.
However I ported the original flash light code. It didn't require to add any assets because the BFG edition already shipped the original flash light.
