### ISSUE TITLE
Need more memory allocation to compile scripts with a large number of variables.

### ISSUE THREAD

**Issue by RolledNodes** [RobertBeckebans/RBDOOM-3-BFG#835]
RBDOOM-3-BFG fails to compile [my mod](https://www.moddb.com/mods/runners-doom-3/downloads/runnersdoom3bfg-v24) scripts with an error "Exceeded global memory size".
This error occurs in the idProgram::ReserveDefMemory function in [master/neo/d3xp/script/Script_Program.cpp](https://github.com/RobertBeckebans/RBDOOM-3-BFG/blob/master/neo/d3xp/script/Script_Program.cpp), and seems to be caused by the size of the array "variables" being smaller than "numVariables".
The size of the array "variables" is defined in
`#define MAX_GLOBALS	296608`
in [master/neo/d3xp/script/Script_Program.h](https://github.com/RobertBeckebans/RBDOOM-3-BFG/blob/master/neo/d3xp/script/Script_Program.h), so increasing this value should solve the problem.
Does this number have any meaning? If not, I would like to increase this value more.

**Comment by RobertBeckebans** [comment]
I think this is related to https://github.com/dhewm/dhewm3/issues/204 and https://github.com/dhewm/dhewm3/issues/303
I'm going to merge the fixes from Dhewm3 into a branch and then you can test it again

**Comment by RobertBeckebans** [comment]
You can get the changes by 
> git checkout 671-imgui-docking
and compile a new binary. This is the 1.6.0 development branch.

**Comment by RolledNodes** [comment]
Sorry, but the same error occurred.
There is no indication that anything in particular has improved.

**Comment by RobertBeckebans** [comment]
If the last changes don't help then I would suggest to just double the MAX_GLOBALS value.

**Comment by RolledNodes** [comment]
Tried it.
`#define MAX_GLOBALS			999999`
Now it all worked out. :D
There appears to be no particular problem.
