### ISSUE TITLE
Support for DOOM 3 (2019) / Doom 3: Bethesda.net Edition?

### ISSUE THREAD

**Issue by ViperAcidZX** [RobertBeckebans/RBDOOM-3-BFG#856]
Is it possible for this source port to become compatible with data files from the 2019 Panic Button version of DOOM 3 on Epic Games Store, Microsoft Store for Windows 10/11, and for those who had the game on Bethesda.net which was later migrated to Steam for previous owners of the former's storefront? The only port that supports that version of the game is the DOOM: BFA Edition fork but it has some issues relating to gameplay for the Doom 3 portion of Doom 3: BFG Edition / Doom 3 (2019) that I don't agree with t which I doubt will ever be fixed.

**Comment by RobertBeckebans** [comment]
You can use RBDOOM with Doom 3 of the Microsoft Store. It tested it and that works but I don't want to make it official to support that because it is a different product and we have no documentation what they changed.
