### ISSUE TITLE
cmake error 

### ISSUE THREAD

**Issue by y2keeth** [RobertBeckebans/RBDOOM-3-BFG#867]
![cmake error](https://github.com/RobertBeckebans/RBDOOM-3-BFG/assets/9625773/7a87f6b1-5c3d-4388-b2ef-431f734fda73)

**Comment by y2keeth** [comment]
C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\neo>cd ..

C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master>del /s /q build
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeCache.txt
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\cmake.check_cache
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\CMakeConfigureLog.yaml
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CMakeCCompiler.cmake
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CMakeCXXCompiler.cmake
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CMakeDetermineCompilerABI_C.bin
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CMakeDetermineCompilerABI_CXX.bin
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CMakeRCCompiler.cmake
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CMakeSystem.cmake
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\VCTargetsPath.txt
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\VCTargetsPath.vcxproj
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdC\CMakeCCompilerId.c
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdC\CompilerIdC.exe
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdC\CompilerIdC.vcxproj
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdC\Debug\CMakeCCompilerId.obj
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdC\Debug\CompilerIdC.exe.recipe
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdC\Debug\CompilerIdC.tlog\CL.command.1.tlog
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdC\Debug\CompilerIdC.tlog\CL.read.1.tlog
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdC\Debug\CompilerIdC.tlog\CL.write.1.tlog
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdC\Debug\CompilerIdC.tlog\CompilerIdC.lastbuildstate
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdC\Debug\CompilerIdC.tlog\link.command.1.tlog
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdC\Debug\CompilerIdC.tlog\link.read.1.tlog
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdC\Debug\CompilerIdC.tlog\link.write.1.tlog
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdCXX\CMakeCXXCompilerId.cpp
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdCXX\CompilerIdCXX.exe
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdCXX\CompilerIdCXX.vcxproj
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdCXX\Debug\CMakeCXXCompilerId.obj
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdCXX\Debug\CompilerIdCXX.exe.recipe
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdCXX\Debug\CompilerIdCXX.tlog\CL.command.1.tlog
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdCXX\Debug\CompilerIdCXX.tlog\CL.read.1.tlog
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdCXX\Debug\CompilerIdCXX.tlog\CL.write.1.tlog
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdCXX\Debug\CompilerIdCXX.tlog\CompilerIdCXX.lastbuildstate
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdCXX\Debug\CompilerIdCXX.tlog\link.command.1.tlog
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdCXX\Debug\CompilerIdCXX.tlog\link.read.1.tlog
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\CompilerIdCXX\Debug\CompilerIdCXX.tlog\link.write.1.tlog
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\x64\Debug\VCTargetsPath.recipe
Deleted file - C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build\CMakeFiles\3.29.0-rc2\x64\Debug\VCTargetsPath.tlog\VCTargetsPath.lastbuildstate

C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master>mkdir build
A subdirectory or file build already exists.

C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master>cd build

C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build>cmake -G "Visual Studio 17" -A x64 -DFFMPEG=OFF -DBINKDEC=ON ../neo
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
-- The C compiler identification is MSVC 19.35.32216.1
-- The CXX compiler identification is MSVC 19.35.32216.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using module to find Vulkan and components
CMake Warning at C:/Program Files/CMake/share/cmake-3.29/Modules/FindVulkan.cmake:526 (message):
  Library dxc for Debug configuration is missing, imported target Vulkan::dxc
  may not be able to link when targeting this build configuration due to
  incompatible MSVC ABI.  Consider re-installing the Vulkan SDK and request
  debug libraries to fix this warning.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.29/Modules/FindVulkan.cmake:544 (_Vulkan_set_library_component_found)
  CMakeLists.txt:386 (find_package)


-- Found Vulkan: C:/VulkanSDK/1.3.275.0/Lib/vulkan-1.lib (found version "1.3.275") found components: dxc glslc glslangValidator
-- Using Vulkan: C:/VulkanSDK/1.3.275.0/Lib/vulkan-1.lib
CMake Error at CMakeLists.txt:443 (add_subdirectory):
  The source directory

    C:/Users/bheadr/Desktop/RBDOOM-3-BFG-master/neo/extern/nvrhi

  does not contain a CMakeLists.txt file.


-- Found DXCdxil: C:/Program Files (x86)/Windows Kits/10/bin/10.0.22000.0/x64/dxc.exe (found version "10.0.22000.0")
-- Found DXCspirv: C:/VulkanSDK/1.3.275.0/Bin/dxc.exe
-- Shader include path C:/Users/bheadr/Desktop/RBDOOM-3-BFG-master/neo/shaders
-- Configuring incomplete, errors occurred!

C:\Users\bheadr\Desktop\RBDOOM-3-BFG-master\build>pause
Press any key to continue . . .

**Comment by RobertBeckebans** [comment]
Just run in the RBDOOM-3-BFG-master directory:
> git submodule update --init --recursive

**Comment by y2keeth** [comment]
not using git just downloaded the zip

**Comment by ericwomer** [comment]
> not using git just downloaded the zip

For projects that depend on git submodule you should always use the git and not the zip.

**Comment by RobertBeckebans** [comment]
Yes just downloading the zip isn't supported because then you miss the external dependencies.

**Comment by y2keeth** [comment]
oh ok guess I will have to re learn hoe to do that lol
