### ISSUE TITLE
Mac OS X port

### ISSUE THREAD

**Issue by kode54** [RobertBeckebans/RBDOOM-3-BFG#87]
It would be really neat if this could also be ported to Mac OS X. I'm not sure what help I could be in that effort, though.

**Comment by tnull** [comment]
I experience the same error on macOS which @JanSimek described above:

> When taking the elevator from Mars City to Underground, game throws me back into the main menu with the following error:
> 
> `idSoundSample_OpenAL::CreateOpenALBuffer: error loading data into OpenAL hardware buffer`

This error still crashes the game. How do I fix that? I installed openal-soft via homebrew and even manually force-linked it. However, CMake does not seem to pick it up:
`-- Found OpenGL: /System/Library/Frameworks/OpenGL.framework`

I also manually changed the Error into a Warning as temporary workaround, but this is not the only (but the only crashing) openal error I get.
