### ISSUE TITLE
(Improvement) The Linux compilation instructions don't recommend the Vulkan SDK.

### ISSUE THREAD

**Issue by hardBSDk** [RobertBeckebans/RBDOOM-3-BFG#887]
Currently it show the Direct3D shader compiler as the only option, while the Vulkan SDK is also supported and come with more options.

**Comment by DistantThunder** [comment]
What would this change exactly?
The Vulkan SDK itself is using DXC : 

* https://vulkan.lunarg.com/doc/sdk/1.3.283.0/linux/spirv_toolchain.html

**Comment by hardBSDk** [comment]
@DistantThunder Update the documentation to recommend the Vulkan SDK instead of DXC on the Linux build instructions.

**Comment by ericwomer** [comment]
> @DistantThunder Update the documentation to recommend the Vulkan SDK instead of DXC on the Linux build instructions.

Are you just trying to be contentious? For Doom3/BFG you still need dxc on Linux as the Vulkan SDK would depend on it for the compilation of the HLSL shader code for Vulkan consumption. Pay attention to what people are telling you and don't push issues on a misguided agenda. You can learn both HLSL and Spir-V so you can manually translate every HSLS shader into Spir-V so we won't be dependent on dxc, or, you can let the tool chain work as designed and automatically convert the HLSL shader code into a working shader binary blob that Vulkan can use, therefore freeing up valuable time and resources that can be better used elsewhere.

**Comment by hardBSDk** [comment]
@ericwomer When I opened this issue I was not aware that DXC worked on Linux.

I can imagine that the Doom 3 shaders are written in HLSL.
