### ISSUE TITLE
Explicit declare char is signed in /doomclassic/doom/d_ticcmd.h

### ISSUE THREAD

**Issue by glKarin** [RobertBeckebans/RBDOOM-3-BFG#893]
forwardmove and sidemove type is `char`, but it's default unsigned on Android arm.

**Comment by glKarin** [comment]
And DOOM3BFG's CPUSTRING macro support 32bits CPU with __arm__ macro on linux GCC/clang

**Comment by glKarin** [comment]
And in /neo/renderer/Font.h, char idFont::glyphInfo_t::top, char idFont::glyphInfo_t::left should be also signed.

**Comment by RobertBeckebans** [comment]
Can you make a pull request for those changes?

**Comment by RobertBeckebans** [comment]
This might be the cause of the bugs found with the font rendering code in #533

**Comment by glKarin** [comment]
> This might be the cause of the bugs found with the font rendering code in #533

Yes, The character 'A''s offset is large, and some other characters. Because type `char` is unsigned by some OS and compiler, but it should be signed. In /neo/renderer/Font.h, char idFont::glyphInfo_t::top, char idFont::glyphInfo_t::left.

**Comment by glKarin** [comment]
Thank your for your great job. I port the project of ver1.4.0 to Android that lastest OpenGL renderer supported, and looks like fine, so found these issues.
And shadow mapping, obj/dae model, some shaders, I add to original DOOM3 2004 OpenGLES version too, thanks for your work.

**Comment by RobertBeckebans** [comment]
yeah it shouldn't be too hard to get 1.4 running with GLES 3. I ported the renderer in 2013 to Android in another project which was a mix of D3 and BFG but I never released it. Here is the backup of the code: https://github.com/RobertBeckebans/TEKUUM-D3

**Comment by glKarin** [comment]
Thanks, main problem is GLES not support DXT compression texture. I re-decompress these compressed texture to standard data format now, and I will try using your TEKUUM-D3's OES compression texture.

**Comment by glKarin** [comment]
I have pull request of these issues, so close it.
