### ISSUE TITLE
Install questions

### ISSUE THREAD

**Issue by lmills87** [RobertBeckebans/RBDOOM-3-BFG#902]
I was playing around in the menu and enabled 3d mode; now my screen is black and I can't figure out how to disable it lol. Where is this setting stored at so that I can turn it off? I've even tried completely redoing my install, and my screen is _still_ black.

Also, after installing the patch, I now have the two following folders: @UltimateHD and mod_ultimateHD -- What's the difference between these two and is one of them antiquated? To install the patch I simply dragged and dropped the files into my RBDoom3 folder and overwrote files when asked. I actually tried completely redoing my install and my screen is still black when I launch...

Finally, is it possible to launch directly in to Doom 3 instead of having to choose it from the in-game menu each time you launch?

**Comment by RobertBeckebans** [comment]
mod_ultimateHD is just a small patch for the original @UltimateHD mod from 2017. You need to patch it manually with those files.

The 3D mode options have already been removed in the current 1.6 preview builds however for 1.5.1 you need to start it with +set stereoRender_enable 0. You can either put that into a shortcut, .bat file or into a autoexec.cfg for base or a mod folder.

**Comment by lmills87** [comment]
This makes sense! I wasn't sure what exactly I should do with it but now I know; thanks.
