### ISSUE TITLE
TSM v2.0E Custom map for (RBDOOM-3-BFG Version)

### ISSUE THREAD

**Issue by SimoK1080** [RobertBeckebans/RBDOOM-3-BFG#918]
hi, i ported my TSM mod for ( RBDOOM-3-BFG ) long time ago. and  It is only playable for ( RBDOOM-3-BFG 1.3.0 version. )
when i try to play the latest version is ( RBDOOM-3-BFG 1.5.1 ).... it crashes down my desktop....

- https://www.moddb.com/mods/doom-3-tsm/addons/tsm-v20a-bfg-edition

I don't know what to do now... it trying to load my level and it crashes down.... no error message or anything else...
i tested DX12 and Vulkan.... no help me....

**Comment by RobertBeckebans** [comment]
Please try the newest RBDoom 1.6 preview build: https://drive.google.com/file/d/1lMQxVRNah87ezMBuaX8d4PnEYRGWeiB0/view?usp=drive_link

It has a couple of crashfixes.

**Comment by SimoK1080** [comment]
RBDoom 1.6 preview build...
- Unfortunately, it doesn't fix anything. my level is still crashing on the desktop...

**Comment by RobertBeckebans** [comment]
Ok I'm going to check it out in the debugger next week.

**Comment by RobertBeckebans** [comment]
It's working for me with this new preview test build: https://drive.google.com/file/d/1IZmi18rhS7CUl10TnTVQsa8JCHpNxeol/view?usp=drive_link

**Comment by RobertBeckebans** [comment]
I'm closing this because it moved to the master branch.
