### ISSUE TITLE
clang: Missing function prototype warnings for zlib since jpeg/png->stb replacement

### ISSUE THREAD

**Issue by SRSaunders** [RobertBeckebans/RBDOOM-3-BFG#922]
clang issues many deprecation warnings for zlib since commit 2262599707f68e2f480f28064928c2ecb0eea1e6.

For example:

```
/Users/steve/XcodeProjects/RBDOOM-3-BFG/neo/libs/zlib/adler32.c:65:15: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
uLong ZEXPORT adler32(adler, buf, len)
              ^

and so on for many zlib source files...
```

This warning was previously suppressed for minizip, but re-emerged for zlib itself following the restructuring.

I will submit a PR to suppress this one for now.  Perhaps zlib/minizip should be updated in the future.

**Comment by RobertBeckebans** [comment]
I saw the warnings but I wasn't sure what change caused them. Good that you could figure it out.
Maybe it is the best to update zlib or to replace it with miniz like it was done for dhewm3. That way we have a zlib API implementation that is at least compatible with the modified minizip implementation.

**Comment by RobertBeckebans** [comment]
Here is the link: https://github.com/dhewm/dhewm3/tree/master/neo/framework/miniz

**Comment by SRSaunders** [comment]
Thanks for the info.  I'll come back to this when I have more time in a few weeks.
