### ISSUE TITLE
Game crashed and won't start after enabling the first option in Settings/Rendering

### ISSUE THREAD

**Issue by unfa** [RobertBeckebans/RBDOOM-3-BFG#927]
Hi!

I've just installed Doom 3 BFG via Lutris using purchased GOG's files. The Lutris installation script also downloaded RBDOOM-3-BFG.

I've run the game, selected Doom 3 and wanted to enable fullscreen and my screen resolution.
The very first option in the Rendering submenu looked interesting so I clicked on it.

The frame buffer got corrupted and the game froze. now it won't start up again.

How can I reset the problematic setting to be able to run the game?
I've been searching for a config file, but I found nothing so far.

I'm running on Arch Linux with X11, AMD RX6800XT, dual monitor setup (no VR).

**Comment by SRSaunders** [comment]
The **D3BFGConfig.cfg** and **autoexec.cfg** files are located in `/home/<yourlogin>/.local/share/rbdoom3bfg/base`

However, if you changed the fullscreen mode and think this is the issue, you can leave the config files alone and run the following command from your build dir.  This is will run the game and set the fullscreen mode back to windowed mode.

$ ./RBDoom3BFG +set r_fullscreen 0

FYI - I am running on Manjaro (Arch) Linux with an AMD 6600XT card and things work properly there.

**Comment by unfa** [comment]
I found that what I enabled was VR (3D) display, which I don't have.
I have found the config files using the `fzf` utility and after deleting all config files I was able to get it working again.
Maybe it'd be good to add some failsafe in case the user enables this but has no VR interfaces connected? Or at least ask them for confirmation before proceeding?

**Comment by SRSaunders** [comment]
Are you using the 1.5 release?  The 1.6 preview version built from master removes the 3D/VR menu, so hopefully you won't be able to get into the situation you faced above.  I believe @RobertBeckebans has a different branch with VR capabilities.

**Comment by unfa** [comment]
@SRSaunders I'm using whatever comes with this Lutris installation script:
https://lutris.net/games/doom-3-bfg-edition/

Maybe they could update it or something?

**Comment by Calinou** [comment]
Lutris seems to be using an old version:

> - Using RBDOOM-3-BFG engine (compiled 25 september 2023 from Github - commit a51833e - 64 bits)

**Comment by RobertBeckebans** [comment]
Yeah I can't support all third party builds and will provide a Flatpak build soon.
