### ISSUE TITLE
WARNING: Couldn't load image: guis/assets/splash/legal_english : guis/assets/splash/legal_english#__0200

### ISSUE THREAD

**Issue by Shell-reversecpp** [RobertBeckebans/RBDOOM-3-BFG#933]
Setup OpenAL device and context... Done.
OpenAL vendor: OpenAL Community
OpenAL renderer: OpenAL Soft
OpenAL version: 1.1 ALSOFT 1.19.1
OpenAL extensions: AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_EXT_SOURCE_RADIUS AL_EXT_STEREO_ANGLES AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFTX_events AL_SOFTX_filter_gain_ex AL_SOFT_gain_clamp_ex AL_SOFT_loop_points AL_SOFTX_map_buffer AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length AL_SOFT_source_resampler AL_SOFT_source_spatialize
sound system initialized.
--------------------------------------
------- Initializing renderSystem --------
WARNING: Couldn't load image: textures/loadingicon2 : textures/loadingicon2#__0200
WARNING: Couldn't load image: textures/loadingicon3 : textures/loadingicon3#__0200
WARNING: Couldn't load image: textures/loadingicon2 : textures/loadingicon2#__0200
WARNING: Couldn't load image: textures/loadingicon3 : textures/loadingicon3#__0200
renderSystem initialized.
--------------------------------------
WARNING: Couldn't load image: guis/assets/splash/legal_english : guis/assets/splash/legal_english#__0200
WARNING: Couldn't load image: guis/assets/splash/legal_english : guis/assets/splash/legal_english#__0200
Skipping Intro Videos!
Reading strings/english.lang as ASCII
Sys_Error: Language file strings/english.lang is supposed to be plain ASCII, but has byte values > 127!
AL lib: (EE) alc_cleanup: 1 device not closed
Segmentation fault (core dumped)

**Comment by RobertBeckebans** [comment]
This seems to be an installation / asset problem.
