### ISSUE TITLE
aligned_alloc() portability concerns in MOC branch

### ISSUE THREAD

**Issue by SRSaunders** [RobertBeckebans/RBDOOM-3-BFG#934]
Following my PR for the MOC branch, I had a second look at `aligned_alloc()` in **CompilerSpecific.inl**.  I think my change using `posix_memalign()` is fine for linux and macOS, but may not be fine if using gcc on Win32 (e.g. MinGW).  The `#ifdef` in this file groups Win32 with MSVC, the Intel Compiler and clang.  However, It looks like gcc on Win32 falls through to the second condition which is `#elif defined(__GNUG__)	|| defined(__clang__) // G++ or clang`.  If `posix_memalign()` is not available for gcc on Win32, then my current code will fail to compile:

```
FORCE_INLINE void* aligned_alloc( size_t alignment, size_t size )
{
	void* ret;
	posix_memalign( &ret, alignment, size );
	return ret;
}
```

Here is a possible improvement for Win32 gcc portability, but I cannot test this since I don't have a MinGW environment:

```
FORCE_INLINE void* aligned_alloc( size_t alignment, size_t size )
{
#if defined(__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__)
	return malloc_zone_memalign( malloc_default_zone(), alignment, size );
#else
	return memalign( alignment, size );
#endif
}
```

@RobertBeckebans are you concerned about this?  Do you have a test setup that could check my two solutions for gcc on Win32?  Note that on macOS `posix_memalign()` is implemented using `malloc_zone_memalign()` so on macOS the two are essentially equivalent.

**Comment by RobertBeckebans** [comment]
GCC on Win32 is not my concern. I only use msvc on Windows and I would only consider clang to be an alternative. I used gcc on Windows in the past and I never liked it.

**Comment by SRSaunders** [comment]
Thanks @RobertBeckebans.  Then it’s fine as is.

I will close this now
