### ISSUE TITLE
Location of the configuration file of rbdoom3bfg on Debian ?

### ISSUE THREAD

**Issue by jebez1** [RobertBeckebans/RBDOOM-3-BFG#936]
I maybe set to on a 3D glasses setting , now black screen ...

How to reset ?

I reinstalled rbdoom3bfg , same .

**Comment by RobertBeckebans** [comment]
Just do this ./RBDoom3BFG +set stereoRender_enable 0

**Comment by jebez1** [comment]
rbdoom3bfg +set stereoRender_enable 0 worked ! Thanks . But I still wonder in which file is it ?

New issue : same as https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/412 , what to do ?

**Comment by RobertBeckebans** [comment]
It's in ~/.local/share/rbdoom3bfg/
